#!/bin/sh

# Xcode Cloud post-clone hook. Runs right after Xcode Cloud clones the repo,
# BEFORE it resolves/builds the Xcode project. The Capacitor `ios/` project is
# gitignored (regenerated by `cap`), so generate it + the web bundle here so
# Xcode Cloud can archive ios/App/App.xcodeproj.
set -e

# Repo root (Xcode Cloud sets this).
cd "$CI_PRIMARY_REPOSITORY_PATH"

# Node isn't preinstalled on the Xcode Cloud image — install via Homebrew.
brew install node
node -v
npm -v

# Web bundle + native iOS project.
npm ci
npm run build
npx cap add ios
npx cap sync ios

# Keep the AVAudioSession AppDelegate patch in place (cap regenerates ios/).
cp ios-patches/App/AppDelegate.swift ios/App/App/AppDelegate.swift

echo "ci_post_clone: iOS project generated at ios/App/App.xcodeproj"
