[build]
  command = "npx vite build"
  publish = "dist"

[[redirects]]
  from = "/voice-packs/*"
  to = "/voice-packs/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
