// GothamChess Black: Caro-Kann (8) + Scandinavian (5) — real 8-ply lines from his wins.
const { apply } = require('../apply-plan-narration.cjs');

const narr = {
  // ===== Caro-Kann =====
  'mp-progothamchess-caro-bf5-trade': {
    title: 'Caro-Kann: Queenside Counter-Race',
    intro: 'A real GothamChess win. Black undermines White’s queenside clamp and rolls a passed pawn.',
    overview: 'A real GothamChess win: Black challenges the c5-wedge with …b6, undermines b4 with …a5, and emerges with a rolling passed c-pawn and the better queenside play.',
    pawnBreaks: [{ move: '...a5 and ...c4 undermining', explanation: 'Black hits b4 with …a5 and pushes the passed pawn to c4.', fen: '' }],
    pieceManeuvers: [{ piece: 'Pawn', route: '...b6-...bxc5 break', explanation: 'Black breaks the queenside clamp with …b6 and …bxc5.' }],
    strategicThemes: ['Undermine White’s queenside pawn clamp.', 'Roll the passed c-pawn.'],
    endgameTransitions: ['The passed pawn is an asset into the endgame.'],
    greenArrowIdx: [3, 7],
    annotations: [
      'c5 — White clamps with c5, grabbing queenside space.',
      '…b6 — Black challenges the c5-wedge at once.',
      'b4 — White props up the clamp.',
      '…a5 — Black undermines the b4-pawn.',
      'b5 — White pushes past.',
      '…bxc5 — Black captures, opening the b-file.',
      'bxc6 — White grabs a pawn, but the structure loosens.',
      '…c4 — Black’s passed c-pawn rolls forward; the queenside play favours Black.',
    ],
    cues: ['c5 — White clamps', 'b6 — challenge the wedge', 'b4 — prop it up', 'a5 — undermine b4', 'b5 — push past', 'bxc5 — open the b-file', 'bxc6 — structure loosens', 'c4 — passed pawn rolls'],
  },
  'mp-progothamchess-caro-advance-c5': {
    title: 'Caro-Kann Advance: Blunt the Kingside',
    intro: 'A real GothamChess win vs honza123455. Black reroutes to defend and snuffs out White’s attack.',
    overview: 'A real GothamChess win (vs honza123455): Black connects with …Qe7, reroutes the knight to defend, and kicks back the g5-knight before grabbing kingside space to blunt White’s attack.',
    pieceManeuvers: [{ piece: 'Knight', route: '...Nc6-d8 defence', explanation: 'The knight reroutes to d8 to shore up the kingside.' }],
    pawnBreaks: [{ move: '...h6 and ...g5 kingside', explanation: '…h6 and …g5 kick White’s knight and seize kingside space.', fen: '' }],
    strategicThemes: ['Reroute to defend the kingside.', 'Kick White’s pieces back and take space.'],
    endgameTransitions: ['Once the attack is blunted, the solid structure tells.'],
    greenArrowIdx: [5, 7],
    annotations: [
      'Qf4 — White’s queen eyes the kingside.',
      '…Qe7 — Black connects and prepares to castle.',
      'Ng5 — White’s knight probes g5.',
      '…Nd8 — Black reroutes the knight to defend.',
      'O-O-O — White castles long.',
      '…h6 — Black kicks the g5-knight.',
      'Nf3 — the knight retreats.',
      '…g5 — Black grabs kingside space, blunting White’s attack.',
    ],
    cues: ['Qf4 — eye the kingside', 'Qe7 — connect', 'Ng5 — probe g5', 'Nd8 — reroute to defend', 'O-O-O — White castles long', 'h6 — kick the knight', 'Nf3 — retreat', 'g5 — blunt the attack'],
  },
  'mp-progothamchess-caro-classical-bd6': {
    title: 'Caro-Kann Classical: Active Pieces Trump Material',
    intro: 'A real GothamChess win vs tactic. White grabs the exchange, but Black’s active pieces take over.',
    overview: 'A real GothamChess win (vs tactic): White sacrifices into the kingside and grabs the exchange, but Black recaptures with active pieces and a loose White king — the engine gives Black the edge (~+1.7).',
    pieceManeuvers: [{ piece: 'Queen', route: '...Qe8-g6 active', explanation: 'The queen swings to g6, eyeing White’s loosened king.' }],
    pawnBreaks: [{ move: '...f-file opening', explanation: '…fxg6 opens the f-file for Black’s pieces.', fen: '' }],
    strategicThemes: ['Use active pieces against the loose White king.', 'Let the initiative outweigh the material.'],
    endgameTransitions: ['The activity converts before any endgame.'],
    greenArrowIdx: [7],
    annotations: [
      'Nxg6 — White sacrifices the knight to grab a pawn and open lines.',
      '…fxg6 — Black recaptures, opening the f-file.',
      'Bxg6 — White snatches a second pawn.',
      '…Nf8 — Black defends and kicks the bishop.',
      'Bxe8 — White grabs the rook for the bishop.',
      '…Qxe8 — Black recaptures; the pieces are active and White’s king is loose.',
      'Qf3 — White regroups.',
      '…Qg6 — Black centralises the queen, with the better game.',
    ],
    cues: ['Nxg6 — White sacs', 'fxg6 — open the f-file', 'Bxg6 — grabs a pawn', 'Nf8 — kick the bishop', 'Bxe8 — grabs the rook', 'Qxe8 — active pieces', 'Qf3 — regroup', 'Qg6 — Black is better'],
  },
  'mp-progothamchess-caro-exchange-fianchetto': {
    title: 'Caro-Kann Exchange: Grab the Loose Rook',
    intro: 'A real GothamChess win vs TomasKapitanchuk. Black’s queen raids a1 and the material piles up.',
    overview: 'A real GothamChess win (vs TomasKapitanchuk): Black’s queen swings into a1 to grab the rook, defends accurately, and snatches a knight too — winning huge material (~+5).',
    pieceManeuvers: [{ piece: 'Queen', route: '...Qb2xa1 raid', explanation: 'The queen raids the corner to win the rook on a1.' }],
    pawnBreaks: [{ move: '...d5 central anchor', explanation: 'The d5-pawn anchors Black’s solid centre during the raid.', fen: '' }],
    strategicThemes: ['Snatch the loose material with the queen.', 'Defend accurately and consolidate the win.'],
    endgameTransitions: ['Up an exchange and more, trades close it out.'],
    greenArrowIdx: [1, 5],
    annotations: [
      'Bb3 — White retreats the bishop.',
      '…Qxa1 — Black’s queen grabs the rook in the corner.',
      'Qc2 — White tries to trap the queen.',
      '…Bf5 — Black develops with tempo, defending.',
      'Qd2 — White regroups.',
      '…Bxb1 — Black snatches the knight too.',
      'Bxd5 — White grabs a pawn back.',
      '…Rad8 — Black brings the rook to the d-file, up huge material.',
    ],
    cues: ['Bb3 — retreat', 'Qxa1 — grab the rook', 'Qc2 — try to trap it', 'Bf5 — develop, defend', 'Qd2 — regroup', 'Bxb1 — grab the knight', 'Bxd5 — White grabs back', 'Rad8 — Black is up big'],
  },
  'mp-progothamchess-caro-fantasy-bd6': {
    title: 'Caro-Kann vs Fantasy: Strike the Centre',
    intro: 'A real GothamChess win vs hanqi. Black breaks in the centre and wins a pawn with active rooks.',
    overview: 'A real GothamChess win (vs hanqi): Black centralises the rook, breaks with …exd4, and the tactics on e4 net a pawn with the rook dominating the open e-file (~+2.6).',
    pieceManeuvers: [{ piece: 'Rook', route: '...Rf8-e8-e4 file', explanation: 'The rook seizes the e-file and lands on e4.' }],
    pawnBreaks: [{ move: '...exd4 central break', explanation: '…exd4 opens the centre for Black’s pieces.', fen: '' }],
    strategicThemes: ['Break the centre with …exd4.', 'Dominate the open e-file.'],
    endgameTransitions: ['The extra pawn tells into the endgame.'],
    greenArrowIdx: [3, 7],
    annotations: [
      'Nc4 — White reroutes the knight.',
      '…Rfe8 — Black centralises the rook.',
      'Bg5 — White pressures the kingside.',
      '…exd4 — Black breaks open the centre.',
      'cxd4 — White recaptures.',
      '…Nxe4 — Black snatches the centre pawn.',
      'Bxe4 — White recaptures.',
      '…Rxe4 — Black regains the piece, a pawn up with a dominant rook.',
    ],
    cues: ['Nc4 — reroute', 'Rfe8 — centralise', 'Bg5 — pressure', 'exd4 — break the centre', 'cxd4 — recapture', 'Nxe4 — snatch the pawn', 'Bxe4 — recapture', 'Rxe4 — Black wins a pawn'],
  },
  'mp-progothamchess-caro-two-knights': {
    title: 'Caro-Kann Two Knights: Win the Centre Pawn',
    intro: 'A real GothamChess win vs AradNazari. Black strikes the centre and the tactics win material.',
    overview: 'A real GothamChess win (vs AradNazari): …cxd4 strikes the centre, and the sequence of captures on e5 leaves Black’s knight forking its way to material (~+1.7).',
    pieceManeuvers: [{ piece: 'Knight', route: '...Ne5xd3 fork', explanation: 'The knight lands on e5 and grabs the bishop on d3.' }],
    pawnBreaks: [{ move: '...cxd4 central break', explanation: '…cxd4 opens the centre for the tactics.', fen: '' }],
    strategicThemes: ['Strike the centre with …cxd4.', 'Win material with the centralised knight.'],
    endgameTransitions: ['The extra material decides.'],
    greenArrowIdx: [1, 7],
    annotations: [
      'b4 — White grabs queenside space.',
      '…cxd4 — Black strikes the centre.',
      'cxd4 — White recaptures.',
      '…Ndxe5 — Black grabs the centre pawn with the knight.',
      'dxe5 — White recaptures.',
      '…Nxe5 — Black recaptures, centralising the knight and hitting d3.',
      'Qg3 — White tries to hold things together.',
      '…Nxd3 — Black snatches the bishop, winning material.',
    ],
    cues: ['b4 — grab space', 'cxd4 — strike the centre', 'cxd4 — recapture', 'Ndxe5 — grab the pawn', 'dxe5 — recapture', 'Nxe5 — hit d3', 'Qg3 — hold on', 'Nxd3 — win material'],
  },
  'mp-pro-gothamchess-carokann-c5': {
    title: 'Caro-Kann: Trade Down to Comfortable Equality',
    intro: 'A real GothamChess win. Black trades the knights and centralises into a solid, equal game.',
    overview: 'A real GothamChess win: Black accepts the knight trade, develops …Nf6 with tempo, and centralises the queen on d5 — reaching the comfortable equality the Caro-Kann is built for.',
    pieceManeuvers: [{ piece: 'Queen', route: '...Qd8-d5 centralise', explanation: 'The queen centralises on d5, the well-placed Caro-Kann queen.' }],
    pawnBreaks: [{ move: '...c5 freeing break', explanation: 'An eventual …c5 frees Black’s position.', fen: '' }],
    strategicThemes: ['Trade into a solid, equal structure.', 'Centralise the queen actively.'],
    endgameTransitions: ['The sound structure equalises into the endgame.'],
    greenArrowIdx: [5],
    annotations: [
      'Ne4 — White offers a knight trade.',
      '…Nxe4 — Black accepts.',
      'Qxe4 — White recaptures.',
      '…Nf6 — Black develops with tempo on the queen.',
      'Qe2 — White retreats.',
      '…Qd5 — Black centralises the queen.',
      'Kb1 — White tucks the king.',
      '…Qb5 — Black offers a queen trade into a comfortable game.',
    ],
    cues: ['Ne4 — offer a trade', 'Nxe4 — accept', 'Qxe4 — recapture', 'Nf6 — develop with tempo', 'Qe2 — retreat', 'Qd5 — centralise', 'Kb1 — tuck the king', 'Qb5 — comfortable equality'],
  },
  'mp-pro-gothamchess-carokann-solid': {
    title: 'Caro-Kann: Castle, Trade, Equalise',
    intro: 'A real GothamChess win. Black castles to safety, trades the knights, and reaches an equal game.',
    overview: 'A real GothamChess win: Black castles short, accepts the knight trade, and develops …Nf6 with tempo before centralising on d5 — a solid, equal Caro-Kann.',
    pieceManeuvers: [{ piece: 'Queen', route: '...Qd8-d5 centralise', explanation: 'The queen centralises on d5 after the trades.' }],
    pawnBreaks: [{ move: '...c5 freeing break', explanation: 'An eventual …c5 frees Black’s game.', fen: '' }],
    strategicThemes: ['Castle to safety first.', 'Trade into solid equality.'],
    endgameTransitions: ['The sound structure carries into the endgame.'],
    greenArrowIdx: [7],
    annotations: [
      'Kb1 — White tucks the king.',
      '…O-O — Black castles to safety.',
      'Ne4 — White offers a knight trade.',
      '…Nxe4 — Black accepts.',
      'Qxe4 — White recaptures.',
      '…Nf6 — Black develops with tempo on the queen.',
      'Qe2 — White retreats.',
      '…Qd5 — Black centralises into a solid, equal game.',
    ],
    cues: ['Kb1 — tuck the king', 'O-O — castle to safety', 'Ne4 — offer a trade', 'Nxe4 — accept', 'Qxe4 — recapture', 'Nf6 — develop with tempo', 'Qe2 — retreat', 'Qd5 — equalise'],
  },
  // ===== Scandinavian =====
  'mp-progothamchess-scand-bb5-ne5': {
    title: 'Scandinavian: Break with …c5',
    intro: 'A real GothamChess win vs fin. Black seizes the c-file and breaks with …c5 for active play.',
    overview: 'A real GothamChess win (vs fin): Black grabs the c-file, breaks with …c5, and after the trade the bishop is active and the pieces well-placed — clearly better (~+2.4).',
    pieceManeuvers: [{ piece: 'Rook', route: '...Ra8-c8 file', explanation: 'The rook takes the c-file ahead of the …c5 break.' }],
    pawnBreaks: [{ move: '...c5 break', explanation: '…c5 strikes the centre and frees Black’s game.', fen: '' }],
    strategicThemes: ['Seize the c-file.', 'Break with …c5 for activity.'],
    endgameTransitions: ['The active pieces carry the edge into the endgame.'],
    greenArrowIdx: [3],
    annotations: [
      'Re1 — White centralises the rook.',
      '…Rc8 — Black takes the c-file.',
      'Ne4 — White’s knight jumps in.',
      '…c5 — Black breaks in the centre.',
      'dxc5 — White grabs the pawn.',
      '…Bxc5 — Black recaptures, the bishop eyeing f2.',
      'Rd1 — White contests the d-file.',
      '…Be7 — Black repositions, comfortably better with active pieces.',
    ],
    cues: ['Re1 — centralise', 'Rc8 — take the c-file', 'Ne4 — White jumps in', 'c5 — break the centre', 'dxc5 — White grabs it', 'Bxc5 — active bishop', 'Rd1 — contest the d-file', 'Be7 — Black is better'],
  },
  'mp-progothamchess-scand-nf6bg4-oooattack': {
    title: 'Scandinavian: Open the Centre and Centralise',
    intro: 'A real GothamChess win vs JoachimMouhamad. Black opens the centre and the queen dominates d5.',
    overview: 'A real GothamChess win (vs JoachimMouhamad): …g4 grabs kingside space, …exd5 opens the centre, and after the trades the queen recaptures on d5, dominating the board (~+1.3).',
    pieceManeuvers: [{ piece: 'Queen', route: '...Qh5-d5 centralise', explanation: 'The queen recaptures on d5, dominating the centre.' }],
    pawnBreaks: [{ move: '...exd5 central break', explanation: '…exd5 opens the centre for Black’s pieces.', fen: '' }],
    strategicThemes: ['Grab kingside space with …g4.', 'Open the centre and centralise the queen.'],
    endgameTransitions: ['The dominant queen and centre tell into the endgame.'],
    greenArrowIdx: [1, 7],
    annotations: [
      'g3 — White blunts the long diagonal.',
      '…g4 — Black grabs kingside space, fixing g3.',
      'Nh4 — White’s knight sidesteps.',
      '…exd5 — Black opens the centre.',
      'Nxd5 — White recaptures.',
      '…Nxd5 — Black trades knights.',
      'cxd5 — White recaptures.',
      '…Qxd5 — Black grabs the pawn, centralising the queen with the better game.',
    ],
    cues: ['g3 — blunt the diagonal', 'g4 — grab space', 'Nh4 — sidestep', 'exd5 — open the centre', 'Nxd5 — recapture', 'Nxd5 — trade knights', 'cxd5 — recapture', 'Qxd5 — dominate the centre'],
  },
  'mp-progothamchess-scandi-portuguese': {
    title: 'Portuguese Scandinavian: Win the Queen',
    intro: 'A real GothamChess win. Black’s knights swarm the centre and net the queen.',
    overview: 'A real GothamChess win: …g4 grabs space, the knight grabs on d4, and after …Nb6 hits the queen the follow-up …Nxc4 wins it outright (~+6).',
    pieceManeuvers: [{ piece: 'Knight', route: '...Nxd4 and ...Nxc4', explanation: 'The knights grab the centre and then the queen on c4.' }],
    pawnBreaks: [{ move: '...g4 space grab', explanation: '…g4 grabs kingside space and cramps White.', fen: '' }],
    strategicThemes: ['Swarm the centre with the knights.', 'Win the queen with the …Nb6/…Nxc4 trick.'],
    endgameTransitions: ['A queen up, no endgame is needed.'],
    greenArrowIdx: [3, 7],
    annotations: [
      'Ne4 — White centralises a knight.',
      '…g4 — Black gains kingside space.',
      'Ne5 — White’s knight jumps to e5.',
      '…Nxd4 — Black grabs the centre pawn with the knight.',
      'Qc4 — White attacks.',
      '…Nb6 — Black defends and hits the queen.',
      'Nf6 — White lunges with the knight.',
      '…Nxc4 — Black grabs the queen, winning material.',
    ],
    cues: ['Ne4 — centralise', 'g4 — gain space', 'Ne5 — jump in', 'Nxd4 — grab the pawn', 'Qc4 — White attacks', 'Nb6 — hit the queen', 'Nf6 — White lunges', 'Nxc4 — win the queen'],
  },
  'mp-progothamchess-scand-nf6nc3-bg4pin': {
    title: 'Scandinavian: Trade and Equalise Soundly',
    intro: 'A real GothamChess win vs lukas_111111. Black trades a piece, solidifies, and castles to safety.',
    overview: 'A real GothamChess win (vs lukas_111111): Black trades on g5, plays …e6 to solidify the centre, castles, and gains queenside space — a sound, comfortable game (~equal).',
    pieceManeuvers: [{ piece: 'King', route: '...O-O safety', explanation: 'Black castles to tuck the king away before pressing.' }],
    pawnBreaks: [{ move: '...e6 solid centre', explanation: '…e6 solidifies Black’s centre, and …a5 gains queenside space.', fen: '' }],
    strategicThemes: ['Trade and solidify the centre.', 'Castle, then take queenside space.'],
    endgameTransitions: ['The solid structure equalises into the endgame.'],
    greenArrowIdx: [3],
    annotations: [
      'Qe3 — White repositions the queen.',
      '…Nxg5 — Black trades off a piece.',
      'Qxg5 — White recaptures.',
      '…e6 — Black solidifies the centre.',
      'Qf4 — White’s queen eyes the kingside.',
      '…O-O — Black castles to safety.',
      'Rad1 — White centralises.',
      '…a5 — Black gains queenside space; comfortable equality.',
    ],
    cues: ['Qe3 — reposition', 'Nxg5 — trade a piece', 'Qxg5 — recapture', 'e6 — solidify', 'Qf4 — eye the kingside', 'O-O — castle to safety', 'Rad1 — centralise', 'a5 — comfortable equality'],
  },
  'mp-progothamchess-scand-qa5-bxc3': {
    title: 'Scandinavian: Keep the Bishop, Hold the Balance',
    intro: 'A real GothamChess win vs Leebit02. Black shepherds the bishop and reaches a comfortable game.',
    overview: 'A real GothamChess win (vs Leebit02): Black keeps the light-squared bishop alive under the h3-g4 prods, centralises the rook, and after the trade on g6 opens the h-file with a comfortable game (~equal).',
    pieceManeuvers: [{ piece: 'Bishop', route: '...Bg4-h5-g6 shuffle', explanation: 'The bishop shuffles to safety while keeping its diagonal.' }],
    pawnBreaks: [{ move: '...h-file opening', explanation: '…hxg6 opens the h-file for Black’s rook.', fen: '' }],
    strategicThemes: ['Keep the good light-squared bishop.', 'Open the h-file for counterplay.'],
    endgameTransitions: ['The sound structure holds the balance into the endgame.'],
    greenArrowIdx: [3],
    annotations: [
      'h3 — White questions the bishop.',
      '…Bh5 — Black keeps the bishop on its diagonal.',
      'g4 — White grabs space, hitting the bishop.',
      '…Bg6 — Black retreats the bishop safely.',
      'Ne5 — White’s knight jumps to e5.',
      '…Rad8 — Black centralises the rook.',
      'Nxg6 — White trades on g6.',
      '…hxg6 — Black recaptures, opening the h-file; comfortable equality.',
    ],
    cues: ['h3 — question the bishop', 'Bh5 — keep the diagonal', 'g4 — White grabs space', 'Bg6 — retreat safely', 'Ne5 — jump in', 'Rad8 — centralise', 'Nxg6 — trade', 'hxg6 — open the h-file'],
  },
};

const r = apply(narr);
console.log('caro-scandi:', JSON.stringify(r));
