// GothamChess Closed Sicilian (5) + London (6) — real 8-ply lines from his wins.
const { apply } = require('../apply-plan-narration.cjs');

const narr = {
  // ===== Closed Sicilian =====
  'mp-progothamchess-closed-sicilian-bb5-trade': {
    title: 'Closed Sicilian: the d5 Outpost Grip',
    intro: 'A real GothamChess win vs donwhitenoise. The knight plants on d5 and grips the position.',
    overview: 'A real GothamChess win (vs donwhitenoise): the knight leaps to the d5 outpost — the heart of the Closed Sicilian — and even when Black trades it off the structural grip remains. Clearly better (~+2).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nc3-d5 outpost', explanation: 'The knight reaches the dominant d5 outpost.' }],
    pawnBreaks: [{ move: 'f4-f5 lever', explanation: 'The Closed-Sicilian f-pawn levers open the kingside.', fen: '' }],
    strategicThemes: ['Plant a knight on d5.', 'Keep the structural grip even after trades.'],
    endgameTransitions: ['The grip and space favour White into the endgame.'],
    greenArrowIdx: [0],
    annotations: [
      'Nd5 — the knight leaps to the d5 outpost, the heart of the Closed Sicilian.',
      '…Rc8 — Black contests the c-file.',
      'Kb1 — tucking the king after long castling.',
      '…Rg8 — Black readies a kingside push.',
      'g3 — solidifying the kingside.',
      '…Rc5 — the rook swings along the fifth rank.',
      'Nh4 — the knight reroutes toward f5.',
      '…Bxd5 — Black trades the strong knight, but White’s grip persists.',
    ],
    cues: ['Nd5 — seize the outpost', 'Rc8 — contest c-file', 'Kb1 — tuck the king', 'Rg8 — ready a push', 'g3 — solidify', 'Rc5 — swing the rook', 'Nh4 — reroute to f5', 'Bxd5 — grip persists'],
  },
  'mp-progothamchess-closedsic-bb5-bg5': {
    title: 'Closed Sicilian: Win the Castling Race',
    intro: 'A real GothamChess win vs donwhitenoise. Opposite-side castling — White’s kingside storm is faster.',
    overview: 'A real GothamChess win: with kings on opposite wings, h4 launches the storm and the queen swings to f4 while Black’s counterplay arrives a tempo too late. Clearly better (~+1.2).',
    pieceManeuvers: [{ piece: 'Rook', route: 'Rd1-d4 lift', explanation: 'The rook lifts to d4, ready to swing into the attack.' }],
    pawnBreaks: [{ move: 'h4-h5 storm', explanation: 'h4 then h5 storms the kingside in the castling race.', fen: '' }],
    strategicThemes: ['Win the opposite-side castling race.', 'Lift the rook to join the storm.'],
    endgameTransitions: ['The attack aims to land before any endgame.'],
    greenArrowIdx: [2],
    annotations: [
      'Kb1 — tucking the king for the opposite-side race.',
      '…O-O — Black castles short; the race is on.',
      'h4 — the kingside pawn storm begins.',
      '…h6 — Black braces.',
      'Qf4 — the queen swings toward the kingside.',
      '…Qb4 — Black counters on the queenside.',
      'Rd4 — the rook lifts, ready to swing across.',
      '…Qc5 — Black offers a trade, but White’s attack is faster.',
    ],
    cues: ['Kb1 — tuck for the race', 'O-O — race is on', 'h4 — start the storm', 'h6 — brace', 'Qf4 — swing the queen', 'Qb4 — Black counters', 'Rd4 — lift the rook', 'Qc5 — White is faster'],
  },
  'mp-progothamchess-closedsic-d6-oppositecastle': {
    title: 'Closed Sicilian: Recapture and Reoccupy d5',
    intro: 'A real GothamChess win vs Karatsev. Trades open the f-file; the knight returns to d5.',
    overview: 'A real GothamChess win (vs Karatsev): after the central trades open the f-file, White reroutes a knight back to the dominant d5 outpost and keeps the initiative. Clearly better (~+1.3).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nc3-d5 reoccupy', explanation: 'A knight returns to the d5 outpost after the trades.' }],
    pawnBreaks: [{ move: 'f4 lever', explanation: 'The f4 break opens the f-file for the rooks.', fen: '' }],
    strategicThemes: ['Open the f-file with f4.', 'Reoccupy d5 with a knight.'],
    endgameTransitions: ['The outpost and open file persist into the endgame.'],
    greenArrowIdx: [6],
    annotations: [
      'Ngxe2 — recapturing with the knight.',
      '…exf4 — Black opens the f-file.',
      'Nxf4 — recapturing; the knight eyes d5 and e6.',
      '…Rc8 — contesting the c-file.',
      'Qg2 — the queen eyes the long diagonal.',
      '…Ne5 — Black centralises a knight.',
      'Ncd5 — the knight reoccupies the dominant d5 outpost.',
      '…Nxd5 — Black trades it off, but White keeps the initiative.',
    ],
    cues: ['Ngxe2 — recapture', 'exf4 — open the f-file', 'Nxf4 — eye d5 and e6', 'Rc8 — contest c-file', 'Qg2 — long diagonal', 'Ne5 — centralise', 'Ncd5 — reoccupy d5', 'Nxd5 — White keeps it'],
  },
  'mp-progothamchess-closedsic-e6-oooattack': {
    title: 'Closed Sicilian: Storm the h-file',
    intro: 'A real GothamChess win. Opposite castling, and White’s h-pawn rips open the h-file.',
    overview: 'A real GothamChess win: h4 storms forward and the queen lifts to f3 to back the attack; when the h-file opens, White’s heavy pieces pour in. Completely winning (~+5.8).',
    pieceManeuvers: [{ piece: 'Queen', route: 'Qd1-f3 attack', explanation: 'The queen lifts to f3 to back the h-file storm.' }],
    pawnBreaks: [{ move: 'h4-h5 storm', explanation: 'h4 then the hxg5 break tears open the h-file.', fen: '' }],
    strategicThemes: ['Open the h-file against the castled king.', 'Back the storm with the queen.'],
    endgameTransitions: ['The attack decides before any endgame.'],
    greenArrowIdx: [2],
    annotations: [
      'Bg3 — repositioning the bishop onto a long diagonal.',
      '…a5 — Black starts a queenside push.',
      'h4 — White’s kingside storm begins.',
      '…Ba6 — Black develops the bishop.',
      'Qf3 — the queen joins the kingside build-up.',
      '…Kg7 — the king sidesteps.',
      'hxg5 — opening the h-file.',
      '…hxg5 — recapturing, but the open h-file is White’s highway to the king.',
    ],
    cues: ['Bg3 — long diagonal', 'a5 — Black pushes', 'h4 — start the storm', 'Ba6 — develop', 'Qf3 — back the storm', 'Kg7 — sidestep', 'hxg5 — open the h-file', 'hxg5 — White pours in'],
  },
  'mp-progothamchess-closedsic-g6-nd5': {
    title: 'Closed Sicilian: Smash the Fianchetto',
    intro: 'A real GothamChess win vs JackRodgers. White trades pieces to tear open the fianchettoed king.',
    overview: 'A real GothamChess win (vs JackRodgers): the knight crashes through on f5 and g7, stripping the fianchetto, and the queen swings to g5 to harry the exposed king. Clearly better (~+1.1).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nf5-g7 demolition', explanation: 'The knight smashes through f5 and g7 to strip the fianchetto.' }],
    pawnBreaks: [{ move: 'f4-f5 lever', explanation: 'The f-pawn levers the knight into f5 against the fianchetto.', fen: '' }],
    strategicThemes: ['Demolish the fianchetto with a knight sac on g7.', 'Bring the queen to g5 against the bare king.'],
    endgameTransitions: ['The exposed king is the story, not the endgame.'],
    greenArrowIdx: [0, 2],
    annotations: [
      'Nxf5 — the knight grabs the f5-bishop, crashing into the kingside.',
      '…hxg5 — Black grabs a bishop back.',
      'Nxg7 — taking on g7, stripping the king’s fianchetto defender.',
      '…Kxg7 — the king is dragged out.',
      'Qxg5 — the queen recovers material and eyes the exposed king.',
      '…Qb6 — Black counterattacks.',
      'Qd2 — the queen regroups, keeping the attack alive.',
      '…Rac8 — Black activates, but White’s attack on the bare king persists.',
    ],
    cues: ['Nxf5 — crash in', 'hxg5 — Black grabs back', 'Nxg7 — strip the fianchetto', 'Kxg7 — king dragged out', 'Qxg5 — eye the king', 'Qb6 — Black counters', 'Qd2 — keep the attack', 'Rac8 — White presses on'],
  },
  // ===== London =====
  'mp-progothamchess-london-c6-c4break': {
    title: 'London: the Greek Gift on h7',
    intro: 'A real GothamChess win vs sceleon. The classic Bxh7+ sacrifice rips open the king.',
    overview: 'A real GothamChess win (vs sceleon): the bishop sacrifices on h7, the knight checks from g5, and the king is dragged into the open — a discovered check from the queen seals a clear edge. Clearly better (~+1.5).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nf3-g5 + Ne4 discovery', explanation: 'After the Greek gift, the knight checks from g5 and later uncovers the queen’s check.' }],
    pawnBreaks: [{ move: 'c3-c4 break', explanation: 'The London c4 break frees the centre before the kingside sac.', fen: '' }],
    strategicThemes: ['Use the Bxh7+ Greek gift to open the king.', 'Bring the knight and queen into the hunt.'],
    endgameTransitions: ['The attack and safer king carry the edge into the endgame.'],
    greenArrowIdx: [0, 2],
    annotations: [
      'Bxh7+ — the Greek gift! the bishop sacrifices to rip open the king.',
      '…Kxh7 — the king must take.',
      'Ng5+ — check; the knight leaps into the attack.',
      '…Kg6 — the king is dragged forward.',
      'Qxg4 — the queen joins in, regaining material with a raging attack.',
      '…Nf6 — Black scrambles to defend.',
      'Ne4+ — a discovered check; the knight steps aside and the queen hits the king.',
      '…Nxg4 — Black returns material to survive, but White’s safer king keeps a clear edge.',
    ],
    cues: ['Bxh7+ — the Greek gift', 'Kxh7 — king must take', 'Ng5+ — knight leaps in', 'Kg6 — dragged forward', 'Qxg4 — queen joins', 'Nf6 — scramble to defend', 'Ne4+ — discovered check', 'Nxg4 — White stays on top'],
  },
  'mp-progothamchess-london-e6-classical': {
    title: 'London: Greek Gift, then the h-pawn',
    intro: 'A real GothamChess win vs MINDMlNES. Bxh7+ opens the king and the h-pawn joins the hunt.',
    overview: 'A real GothamChess win (vs MINDMlNES): the Greek gift on h7 and Ng5+ drag the king out, then the queen and the h-pawn pile in for a crushing attack (~+3).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nf3-g5 attack', explanation: 'The knight checks from g5 after the sacrifice, driving the king up the board.' }],
    pawnBreaks: [{ move: 'h2-h4-h5 hunt', explanation: 'The h-pawn marches up to h5 to harry the exposed king.', fen: '' }],
    strategicThemes: ['Open the king with Bxh7+.', 'Bring the h-pawn into the attack.'],
    endgameTransitions: ['The attack decides; no endgame needed.'],
    greenArrowIdx: [0, 2],
    annotations: [
      'Bxh7+ — the Greek gift sacrifice rips open the king.',
      '…Kxh7 — the king takes.',
      'Ng5+ — check; the knight leaps in.',
      '…Kh6 — the king is dragged forward.',
      'Qd2 — bringing the queen toward the king with threats.',
      '…Kg6 — the king flees.',
      'h4 — the h-pawn joins the hunt, threatening to march to h5.',
      '…Nf5 — Black scrambles to defend, but White’s attack is crushing.',
    ],
    cues: ['Bxh7+ — Greek gift', 'Kxh7 — king takes', 'Ng5+ — leap in', 'Kh6 — dragged up', 'Qd2 — queen joins', 'Kg6 — king flees', 'h4 — h-pawn hunts', 'Nf5 — attack crushes'],
  },
  'mp-progothamchess-london-jobava-nb5': {
    title: 'Jobava London: Swing the Queen Over',
    intro: 'A real GothamChess win vs ChesssKnock. The queen swings to the kingside while the bishop eyes h7.',
    overview: 'A real GothamChess win (vs ChesssKnock): the queen lifts to h4 and g5 and the bishop lines up on d3 toward h7, generating pressure on the king for a pleasant edge (~+0.4).',
    pieceManeuvers: [{ piece: 'Queen', route: 'Qd1-h4-g5 probe', explanation: 'The queen swings to h4 then probes g5 against the king.' }],
    pawnBreaks: [{ move: 'e3-e4 lever', explanation: 'An eventual e4 frees the centre to feed the kingside pressure.', fen: '' }],
    strategicThemes: ['Swing the queen toward the king.', 'Line the bishop up toward h7.'],
    endgameTransitions: ['If the attack is parried, the pressure still nags into the endgame.'],
    greenArrowIdx: [0, 4],
    annotations: [
      'Qh4 — the queen swings toward the kingside.',
      '…b6 — Black prepares a fianchetto.',
      'Bd3 — eyeing the b1-h7 diagonal toward the king.',
      '…Bb7 — completing the fianchetto.',
      'Qg5 — the queen probes g5, pressing the kingside.',
      '…Kf8 — the king sidesteps the pressure.',
      'O-O-O — castling long, bringing the rook into play.',
      '…h6 — Black challenges the queen; White holds a pleasant edge.',
    ],
    cues: ['Qh4 — swing over', 'b6 — prepare fianchetto', 'Bd3 — eye h7', 'Bb7 — fianchetto', 'Qg5 — probe the kingside', 'Kf8 — sidestep', 'O-O-O — bring the rook', 'h6 — White is better'],
  },
  'mp-progothamchess-london-kid-rooksac': {
    title: 'London vs KID: Grab the Pawns, Hold the Edge',
    intro: 'A real GothamChess win vs AlexOstrovskiy. White castles long and snaps off central pawns.',
    overview: 'A real GothamChess win (vs AlexOstrovskiy): after long castling White picks off the c7- and d5-pawns and tucks the knight to f4, emerging a clear pawn up. Clearly better (~+3).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nc3-d5 grab', explanation: 'The knight grabs the central d5-pawn before retreating to f4.' }],
    pawnBreaks: [{ move: 'c-file pressure', explanation: 'Long castling powers the c-file and the central grabs.', fen: '' }],
    strategicThemes: ['Castle long and seize the centre.', 'Bank the extra pawns and consolidate.'],
    endgameTransitions: ['A clear pawn up, trades favour White.'],
    greenArrowIdx: [4],
    annotations: [
      'O-O-O — White castles long, putting the rook on the d-file.',
      '…Ne4 — Black’s knight jumps in.',
      'Bxc7 — snatching the c7-pawn.',
      '…Qe8 — Black regroups.',
      'Nxd5 — taking the central pawn, a clear pawn up.',
      '…Be6 — developing, hitting d5.',
      'Nf4 — the knight retreats to f4, keeping the extra pawns.',
      '…Rc8 — Black activates, but White is up material.',
    ],
    cues: ['O-O-O — castle long', 'Ne4 — Black jumps in', 'Bxc7 — grab c7', 'Qe8 — regroup', 'Nxd5 — grab the centre', 'Be6 — hit d5', 'Nf4 — keep the pawns', 'Rc8 — White is up'],
  },
  'mp-progothamchess-london-classical-attack': {
    title: 'London: Pressure the Queenside Pawns',
    intro: 'A real GothamChess win vs Hope_6. White trades into a structure where Black’s queenside is loose.',
    overview: 'A real GothamChess win (vs Hope_6): White snatches the b6-pawn and trades pieces to reach a structure where the bishop reroutes to b4 with lasting pressure. A pleasant edge (~+0.3).',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bf1-b5-b4 pressure', explanation: 'The bishop works the b5 and b4 squares, pressing the queenside.' }],
    pawnBreaks: [{ move: 'c-file pressure', explanation: 'Trades on the queenside leave Black’s pawns to target.', fen: '' }],
    strategicThemes: ['Target Black’s loose queenside pawns.', 'Reroute the bishop to b4.'],
    endgameTransitions: ['The healthier pawns nag Black into the endgame.'],
    greenArrowIdx: [2],
    annotations: [
      'Bxb6 — snatching the b6-pawn.',
      '…Rfc8 — activating the rook.',
      'Bb5 — the bishop pressures the queenside.',
      '…Na5 — Black’s knight jumps to a5.',
      'Bxa5 — trading off the knight.',
      '…Bxb5 — recapturing.',
      'Bb4 — the bishop repositions with lasting pressure.',
      '…e6 — Black solidifies; White holds a small, pleasant edge.',
    ],
    cues: ['Bxb6 — grab the pawn', 'Rfc8 — activate', 'Bb5 — press the queenside', 'Na5 — knight jumps', 'Bxa5 — trade it', 'Bxb5 — recapture', 'Bb4 — reposition', 'e6 — White is better'],
  },
  'mp-progothamchess-london-standard-ne5': {
    title: 'London: Gain Space and Shove the Knight',
    intro: 'A real GothamChess win. The h-pawn gains space and shoves Black’s knight to the rim.',
    overview: 'A real GothamChess win: g3 and h4-h5 gain kingside space and chase Black’s knight to the edge, after which the bishop pressures from g5 for a comfortable edge (~+0.9).',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bf4-g5 pressure', explanation: 'The bishop swings to g5 to press the kingside once the space is grabbed.' }],
    pawnBreaks: [{ move: 'h4-h5 space', explanation: 'h4 then h5 gains space and shoves the knight to the rim.', fen: '' }],
    strategicThemes: ['Gain kingside space with h4-h5.', 'Push Black’s pieces to the edge.'],
    endgameTransitions: ['The space edge carries into the endgame.'],
    greenArrowIdx: [4, 6],
    annotations: [
      'g3 — solidifying the kingside.',
      '…Ng6 — Black redeploys the knight.',
      'h4 — gaining kingside space, eyeing h5.',
      '…f5 — Black grabs central space.',
      'h5 — the pawn jabs, kicking the knight back.',
      '…Nh8 — the knight is shoved to the rim.',
      'Bg5 — the bishop swings to g5 with pressure.',
      '…Be7 — Black challenges; White is comfortably better with more space.',
    ],
    cues: ['g3 — solidify', 'Ng6 — redeploy', 'h4 — gain space', 'f5 — Black grabs space', 'h5 — jab, kick the knight', 'Nh8 — shoved to the rim', 'Bg5 — press', 'Be7 — White is comfier'],
  },
};

const r = apply(narr);
console.log('closedsic-london:', JSON.stringify(r));
