// GothamChess English (7) + Trompowsky (7) — real 8-ply lines from his wins.
const { apply } = require('../apply-plan-narration.cjs');

const narr = {
  // ===== English =====
  'mp-progothamchess-eng-c5-maroczy': {
    title: 'English Maroczy: the d5 Outpost',
    intro: 'A real GothamChess win vs flamingo8118. White trades to clear d5 and dominates the hole.',
    overview: 'A real GothamChess win (vs flamingo8118): Bxf6 clears the way, the knight seizes d5, and Nxf6+ shatters Black’s kingside pawns. The structural damage gives a clear edge (~+1.4).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nc3-d5 outpost', explanation: 'The knight occupies the d5 hole, the Maroczy dream square.' }],
    pawnBreaks: [{ move: 'c4 Maroczy bind', explanation: 'The c4-pawn clamps d5 and b5, the Maroczy grip.', fen: '' }],
    strategicThemes: ['Trade to clear and occupy d5.', 'Damage Black’s kingside pawns.'],
    endgameTransitions: ['The structural damage favours White into the endgame.'],
    greenArrowIdx: [2],
    annotations: [
      'Bxf6 — trading to damage Black’s structure and clear the d5-square.',
      '…Bxf6 — recapturing.',
      'Nd5 — the knight seizes the d5 outpost, the Maroczy dream square.',
      '…Qd8 — the queen sidesteps.',
      'Nxf6+ — grabbing the bishop with check, shattering Black’s kingside.',
      '…exf6 — recapturing with broken pawns.',
      'Nf3 — developing, eyeing the weak squares.',
      '…Kg7 — Black tucks the king, but the damaged pawns favour White.',
    ],
    cues: ['Bxf6 — clear d5', 'Bxf6 — recapture', 'Nd5 — seize the outpost', 'Qd8 — sidestep', 'Nxf6+ — shatter the kingside', 'exf6 — broken pawns', 'Nf3 — develop', 'Kg7 — White is better'],
  },
  'mp-progothamchess-eng-c6-slav-g4': {
    title: 'English: Leap to f5',
    intro: 'A real GothamChess win vs rabbiteUK. White grabs the centre and lands a knight on f5.',
    overview: 'A real GothamChess win (vs rabbiteUK): Nxe4 grabs the centre, f4 clamps, and the knight leaps into f5 eyeing g7 and e7 — clearly better (~+2.4).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Ne4-f5 leap', explanation: 'The knight leaps to f5, eyeing g7 and e7.' }],
    pawnBreaks: [{ move: 'f4 clamp', explanation: 'f4 clamps e5 and gains kingside space.', fen: '' }],
    strategicThemes: ['Grab the centre and clamp with f4.', 'Land a knight on f5.'],
    endgameTransitions: ['The space and active knight carry into the endgame.'],
    greenArrowIdx: [4],
    annotations: [
      'Nxe4 — grabbing the centre pawn.',
      '…Bc7 — Black redeploys the bishop.',
      'f4 — gaining space and clamping e5.',
      '…Re8 — Black centralises a rook.',
      'Nf5 — the knight leaps to f5, eyeing g7 and e7.',
      '…Nb4 — Black’s knight jumps in.',
      'Qb1 — sidestepping, keeping the kingside diagonal.',
      '…g6 — Black challenges the knight, but White is clearly better.',
    ],
    cues: ['Nxe4 — grab the centre', 'Bc7 — redeploy', 'f4 — clamp e5', 'Re8 — centralise', 'Nf5 — leap to f5', 'Nb4 — Black jumps', 'Qb1 — keep the diagonal', 'g6 — White is better'],
  },
  'mp-progothamchess-eng-e5-reversedsicilian': {
    title: 'Reversed Sicilian: Open the e-file',
    intro: 'A real GothamChess win. White opens the centre and seizes the e-file.',
    overview: 'A real GothamChess win: dxe5 opens the centre, the rook grabs the e-file, and when Black overpushes with …e4 the pawn becomes a target. Clearly better (~+1.1).',
    pieceManeuvers: [{ piece: 'Rook', route: 'Rf1-e1 file', explanation: 'The rook takes the open e-file after the central trade.' }],
    pawnBreaks: [{ move: 'd4xe5 break', explanation: 'dxe5 opens the centre and the e-file.', fen: '' }],
    strategicThemes: ['Open the centre and grab the e-file.', 'Target Black’s overextended e-pawn.'],
    endgameTransitions: ['The weak e-pawn is a target into the endgame.'],
    greenArrowIdx: [2],
    annotations: [
      'dxe5 — opening the centre.',
      '…dxe5 — recapturing.',
      'Rfe1 — the rook takes the open e-file.',
      '…Bxf3 — Black trades a piece.',
      'Bxf3 — recapturing; the bishop eyes the long diagonal.',
      '…e4 — Black pushes the pawn forward.',
      'Be2 — retreating; the advanced pawn becomes a target.',
      '…Nb4 — Black seeks activity, but White is better.',
    ],
    cues: ['dxe5 — open the centre', 'dxe5 — recapture', 'Rfe1 — take the e-file', 'Bxf3 — Black trades', 'Bxf3 — long diagonal', 'e4 — overpush', 'Be2 — target the pawn', 'Nb4 — White is better'],
  },
  'mp-progothamchess-eng-e6-doublefianchetto': {
    title: 'English Double Fianchetto: Solid and Sound',
    intro: 'A real GothamChess win vs subham777. White’s solid setup weathers a kingside sac.',
    overview: 'A real GothamChess win (vs subham777): White completes the double-fianchetto setup, and when Black throws in …Bxh3 the king holds — accurate defence keeps the balance (~equal, slight White edge).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Ng1-e2 defence', explanation: 'The knight reroutes to e2 to shore up the kingside.' }],
    pawnBreaks: [{ move: 'd4 central anchor', explanation: 'The d4-pawn anchors the centre behind the fianchettoes.', fen: '' }],
    strategicThemes: ['Complete the solid double-fianchetto setup.', 'Defend the king accurately against the …Bxh3 try.'],
    endgameTransitions: ['The sound structure equalises and presses lightly into the endgame.'],
    greenArrowIdx: [4],
    annotations: [
      'O-O — completing the double-fianchetto setup.',
      '…Be6 — Black develops the bishop.',
      'Bd3 — repositioning the bishop to defend the kingside.',
      '…Qd7 — Black eyes the kingside.',
      'Ne2 — rerouting the knight to bolster the king.',
      '…Bxh3 — Black sacrifices a bishop to open the king.',
      'gxh3 — accepting; White must defend precisely.',
      '…Qxh3 — Black regains a pawn, but White’s setup holds the balance.',
    ],
    cues: ['O-O — complete the setup', 'Be6 — develop', 'Bd3 — defend the kingside', 'Qd7 — eye the king', 'Ne2 — bolster the king', 'Bxh3 — Black sacs', 'gxh3 — defend precisely', 'Qxh3 — White holds'],
  },
  'mp-progothamchess-eng-g6-botvinnik-storm': {
    title: 'English: the d6 Wedge',
    intro: 'A real GothamChess win. White rams a pawn to d6, splitting Black’s position.',
    overview: 'A real GothamChess win: d6 wedges deep into Black’s camp, and after the trades on e3 the cramping pawn gives White a clear edge (~+1).',
    pieceManeuvers: [{ piece: 'Queen', route: 'Qd1-d2 support', explanation: 'The queen supports the d6-wedge and the dark squares.' }],
    pawnBreaks: [{ move: 'd5-d6 wedge', explanation: 'The d-pawn rams to d6 and cramps Black.', fen: '' }],
    strategicThemes: ['Wedge a pawn into d6.', 'Use the cramp to press.'],
    endgameTransitions: ['The advanced pawn is an asset into the endgame.'],
    greenArrowIdx: [2],
    annotations: [
      'Be3 — developing toward the kingside.',
      '…Ncd7 — Black redeploys a knight.',
      'd6 — the pawn wedges deep, splitting Black’s camp.',
      '…Ng4 — Black’s knight hits the bishop.',
      'Qd2 — defending and connecting.',
      '…Nxe3 — Black trades.',
      'Qxe3 — recapturing; the d6-wedge cramps Black.',
      '…Nb6 — Black regroups, but the wedge gives White the edge.',
    ],
    cues: ['Be3 — develop', 'Ncd7 — redeploy', 'd6 — wedge in deep', 'Ng4 — hit the bishop', 'Qd2 — defend', 'Nxe3 — trade', 'Qxe3 — cramp Black', 'Nb6 — White is better'],
  },
  'mp-progothamchess-english-botvinnik-main': {
    title: 'English Botvinnik: Open the h-file',
    intro: 'A real GothamChess win. White prises open the h-file and trades the fianchetto bishop.',
    overview: 'A real GothamChess win: h5 jabs at g6, the h-file opens, and Bh6 trades off the fianchetto bishop — roughly balanced, but White has the easier play (~equal).',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bc1-h6 trade', explanation: 'The bishop targets and trades the fianchettoed g7-bishop.' }],
    pawnBreaks: [{ move: 'h4-h5 lever', explanation: 'h5 then hxg6 prises open the h-file.', fen: '' }],
    strategicThemes: ['Open the h-file against the fianchetto.', 'Trade the g7-bishop with Bh6.'],
    endgameTransitions: ['The open file gives easier play into the endgame.'],
    greenArrowIdx: [0],
    annotations: [
      'h5 — gaining kingside space, jabbing at g6.',
      '…f4 — Black counters in the centre.',
      'hxg6 — opening the h-file.',
      '…hxg6 — recapturing.',
      'Bh6 — the bishop targets the fianchetto.',
      '…Rf7 — defending g7.',
      'Bxg7 — trading off the fianchetto bishop.',
      '…Rxg7 — recapturing; roughly balanced, but White has the easier play.',
    ],
    cues: ['h5 — jab at g6', 'f4 — Black counters', 'hxg6 — open the h-file', 'hxg6 — recapture', 'Bh6 — target the fianchetto', 'Rf7 — defend g7', 'Bxg7 — trade it off', 'Rxg7 — White plays easier'],
  },
  'mp-progothamchess-english-flank-attack': {
    title: 'English: Cramp with h6 and Reroute',
    intro: 'A real GothamChess win. The h6-wedge cramps the kingside while White reroutes a knight.',
    overview: 'A real GothamChess win: the h6-pawn wedges into Black’s kingside, and White calmly reroutes the knight (Nf3-h2-f1) toward a strong square. Clearly better (~+2.2).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nf3-h2-f1 reroute', explanation: 'The knight reroutes via h2 and f1 toward g3 or e3.' }],
    pawnBreaks: [{ move: 'h5-h6 wedge', explanation: 'The h-pawn wedges to h6 and cramps the kingside.', fen: '' }],
    strategicThemes: ['Cramp the kingside with the h6-wedge.', 'Reroute the knight to a strong post.'],
    endgameTransitions: ['The space edge carries into the endgame.'],
    greenArrowIdx: [4, 6],
    annotations: [
      'h6 — a space-gaining wedge that cramps Black’s kingside.',
      '…Be7 — the bishop retreats.',
      'Nf3 — developing the knight.',
      '…f6 — Black braces the centre.',
      'Nh2 — rerouting the knight toward g4 and f1.',
      '…Kh8 — Black tucks the king.',
      'Nf1 — the knight reroutes toward e3 or g3.',
      '…Rg8 — Black regroups, but White is clearly better with more space.',
    ],
    cues: ['h6 — cramping wedge', 'Be7 — retreat', 'Nf3 — develop', 'f6 — brace', 'Nh2 — reroute', 'Kh8 — tuck the king', 'Nf1 — reroute on', 'Rg8 — White is better'],
  },
  // ===== Trompowsky =====
  'mp-progothamchess-tromp-c5-gambit': {
    title: 'Trompowsky: f5 Demolition',
    intro: 'A real GothamChess win vs gmgamil. The f-pawn storms in and the kingside collapses.',
    overview: 'A real GothamChess win (vs gmgamil): f5 storms forward, fxg6 smashes the king’s cover, and the queen and knight pour in for a winning attack (~+10).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nf3-g5 attack', explanation: 'The knight leaps to g5 to finish the kingside attack.' }],
    pawnBreaks: [{ move: 'f4-f5 storm', explanation: 'f5 then fxg6 tears open the king.', fen: '' }],
    strategicThemes: ['Storm the kingside with f5.', 'Pour the pieces into the open king.'],
    endgameTransitions: ['The attack decides; no endgame needed.'],
    greenArrowIdx: [0, 6],
    annotations: [
      'f5 — the pawn storms forward, ripping open the kingside.',
      '…Nc7 — Black retreats the knight.',
      'fxg6 — smashing open the king’s cover.',
      '…hxg6 — recapturing with a wrecked kingside.',
      'Qe1 — swinging the queen toward the kingside.',
      '…Ne5 — Black tries to block.',
      'Ng5 — the knight leaps in; the attack is overwhelming.',
      '…a6 — Black is lost; White is completely winning.',
    ],
    cues: ['f5 — storm in', 'Nc7 — retreat', 'fxg6 — smash the cover', 'hxg6 — wrecked kingside', 'Qe1 — swing the queen', 'Ne5 — try to block', 'Ng5 — leap in', 'a6 — White is winning'],
  },
  'mp-progothamchess-tromp-d5-squeeze': {
    title: 'Trompowsky: Reroute and Squeeze',
    intro: 'A real GothamChess win vs Algeriano22. White regains the pawn and manoeuvres for the squeeze.',
    overview: 'A real GothamChess win (vs Algeriano22): Nxc4 regains the pawn, the knight reroutes to e3 eyeing d5 and f5, and White castles long for a balanced, manoeuvring game (~equal, small edge).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nxc4-e3 reroute', explanation: 'The knight reroutes via c4 to e3, eyeing d5 and f5.' }],
    pawnBreaks: [{ move: 'f4 clamp', explanation: 'f4 clamps the centre in the manoeuvring squeeze.', fen: '' }],
    strategicThemes: ['Regain the pawn and reroute the knight.', 'Squeeze in a manoeuvring middlegame.'],
    endgameTransitions: ['The squeeze can persist into the endgame.'],
    greenArrowIdx: [2],
    annotations: [
      'Nxc4 — regaining the pawn.',
      '…Qb5 — Black eyes the queenside.',
      'Ne3 — the knight reroutes, eyeing d5 and f5.',
      '…Rg8 — Black readies a kingside push.',
      'O-O-O — castling long.',
      '…f5 — Black grabs space.',
      'f4 — clamping and gaining space.',
      '…Rc8 — Black contests the c-file; roughly balanced.',
    ],
    cues: ['Nxc4 — regain the pawn', 'Qb5 — eye queenside', 'Ne3 — reroute', 'Rg8 — ready a push', 'O-O-O — castle long', 'f5 — grab space', 'f4 — clamp', 'Rc8 — balanced'],
  },
  'mp-progothamchess-trompowsky-knight-flank': {
    title: 'Trompowsky: Active King, Space on the Wings',
    intro: 'A real GothamChess win vs Vitaly_Sivuk. Queens come off and White grabs space on both wings.',
    overview: 'A real GothamChess win (vs Vitaly_Sivuk): the queens trade off, White’s king sits actively in the centre, and g4-h4 grab kingside space in the queenless middlegame (~equal, small edge).',
    pieceManeuvers: [{ piece: 'King', route: 'Ke1-e2 centralise', explanation: 'The king steps up, active in the queenless middlegame.' }],
    pawnBreaks: [{ move: 'g4-h4 space', explanation: 'g4 and h4 grab kingside space once the queens are off.', fen: '' }],
    strategicThemes: ['Trade queens and centralise the king.', 'Grab space on both wings.'],
    endgameTransitions: ['The queenless middlegame flows straight into a pleasant endgame.'],
    greenArrowIdx: [2],
    annotations: [
      'Ke2 — the king steps toward the centre.',
      '…c5 — Black strikes on the queenside.',
      'g4 — gaining kingside space.',
      '…Qxd3+ — Black trades queens with check.',
      'Kxd3 — the king recaptures, active in the centre.',
      '…Nc6 — Black develops.',
      'h4 — gaining more kingside space.',
      '…Be7 — Black develops; roughly balanced, with White’s space.',
    ],
    cues: ['Ke2 — step up', 'c5 — Black strikes', 'g4 — grab space', 'Qxd3+ — trade queens', 'Kxd3 — active king', 'Nc6 — develop', 'h4 — more space', 'Be7 — balanced edge'],
  },
  'mp-progothamchess-trompowsky-main-system': {
    title: 'Trompowsky Main: Queens Off, Clear Edge',
    intro: 'A real GothamChess win vs Vitaly_Sivuk. The queens trade and White’s pieces dominate.',
    overview: 'A real GothamChess win (vs Vitaly_Sivuk): dxe5 opens the centre, the queens come off, and White castles long with tempo on the d-file — clearly better in the queenless middlegame (~+3.3).',
    pieceManeuvers: [{ piece: 'Bishop', route: 'recapture on d3', explanation: 'The bishop recaptures on d3 as the queens trade, eyeing the kingside.' }],
    pawnBreaks: [{ move: 'g4 space', explanation: 'g4 grabs kingside space in the queenless middlegame.', fen: '' }],
    strategicThemes: ['Trade queens into a better middlegame.', 'Castle long with tempo on the d-file.'],
    endgameTransitions: ['White’s activity carries the edge into the endgame.'],
    greenArrowIdx: [4],
    annotations: [
      'dxe5 — opening the centre.',
      '…Qxd3 — Black trades queens.',
      'Bxd3 — recapturing; the queens are off and White is better.',
      '…Kd8 — Black’s king stays central.',
      'O-O-O — castling long with tempo on the d-file.',
      '…Ke7 — the king shuffles.',
      'g4 — gaining kingside space.',
      '…Rad8 — Black contests the d-file, but White is clearly better.',
    ],
    cues: ['dxe5 — open the centre', 'Qxd3 — trade queens', 'Bxd3 — White is better', 'Kd8 — king stays central', 'O-O-O — castle with tempo', 'Ke7 — shuffle', 'g4 — grab space', 'Rad8 — White is better'],
  },
  'mp-progothamchess-tromp-e6-bishoppair': {
    title: 'Trompowsky: Roll the Kingside Pawns',
    intro: 'A real GothamChess win. White storms g4-g5 and keeps the king safe enough to press.',
    overview: 'A real GothamChess win: g4 storms forward, the king sidesteps a check, and g5 prises open lines — a balanced, double-edged game with White’s space (~equal, small edge).',
    pieceManeuvers: [{ piece: 'Rook', route: 'Rh1-g1 support', explanation: 'The rook backs the g-pawn storm from g1.' }],
    pawnBreaks: [{ move: 'g4-g5 storm', explanation: 'g4 then g5 storms the kingside and opens lines.', fen: '' }],
    strategicThemes: ['Roll the kingside pawns g4-g5.', 'Back the storm with the rook.'],
    endgameTransitions: ['The space can tell into the endgame.'],
    greenArrowIdx: [0, 6],
    annotations: [
      'g4 — the pawn storms forward, gaining kingside space.',
      '…Bh4+ — Black checks to disrupt.',
      'Ke2 — the king steps aside, keeping the pawns rolling.',
      '…Be7 — the bishop retreats.',
      'Rhg1 — the rook backs the g-pawn.',
      '…f6 — Black braces.',
      'g5 — the pawn jabs, prising open lines.',
      '…hxg5 — Black opens the h-file; roughly balanced, with White’s space.',
    ],
    cues: ['g4 — storm forward', 'Bh4+ — disruptive check', 'Ke2 — step aside', 'Be7 — retreat', 'Rhg1 — back the pawn', 'f6 — brace', 'g5 — prise it open', 'hxg5 — balanced edge'],
  },
  'mp-progothamchess-tromp-g6-doubled': {
    title: 'Trompowsky: Queenside Space Clamp',
    intro: 'A real GothamChess win. White centralises the queen and rolls the queenside pawns.',
    overview: 'A real GothamChess win: the queen centralises on d3, then c5 and b5 clamp the queenside while the knight jumps to f4. Clearly better (~+1.3).',
    pieceManeuvers: [{ piece: 'Knight', route: 'to f4 outpost', explanation: 'The knight jumps to f4, eyeing d5 and e6.' }],
    pawnBreaks: [{ move: 'c5 and b5 clamp', explanation: 'c5 then b5 clamp the queenside and gain space.', fen: '' }],
    strategicThemes: ['Clamp the queenside with c5 and b5.', 'Post the knight on f4.'],
    endgameTransitions: ['The queenside space squeezes into the endgame.'],
    greenArrowIdx: [6],
    annotations: [
      'Qd3 — centralising the queen.',
      '…d5 — Black strikes the centre.',
      'c5 — clamping and gaining queenside space.',
      '…Kh8 — Black tucks the king.',
      'b5 — expanding further on the queenside.',
      '…Ng8 — Black’s knight retreats.',
      'Nf4 — the knight jumps to f4, eyeing d5 and e6.',
      '…Nf6 — Black redevelops, but White’s space gives the edge.',
    ],
    cues: ['Qd3 — centralise', 'd5 — Black strikes', 'c5 — clamp', 'Kh8 — tuck the king', 'b5 — expand', 'Ng8 — retreat', 'Nf4 — jump to f4', 'Nf6 — White is better'],
  },
  'mp-progothamchess-tromp-vaganian-gambit': {
    title: 'Trompowsky Vaganian Gambit: King Hunt',
    intro: 'A real GothamChess win vs swimmerchess. A knight grab and checks drive the king into the open.',
    overview: 'A real GothamChess win (vs swimmerchess): the knight grabs on g5, Qh5+ and Nf7+ check the king out into the open, and the attack is decisive (~+6).',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nxg5 then Nf7+', explanation: 'The knight grabs g5 and forks from f7 to drive the king out.' }],
    pawnBreaks: [{ move: 'e-file opening', explanation: 'Open lines feed the queen and knight into the king.', fen: '' }],
    strategicThemes: ['Sacrifice to open the king.', 'Drive the king out with checks.'],
    endgameTransitions: ['The king hunt decides before any endgame.'],
    greenArrowIdx: [0, 4],
    annotations: [
      'Nfxg5 — the knight grabs g5, smashing into the kingside.',
      '…h6 — Black tries to trap the knight.',
      'Qh5+ — check; the queen joins the attack.',
      '…Kd8 — the king is forced to move.',
      'Nf7+ — a fork; the knight checks and hits the rook.',
      '…Kc7 — the king flees.',
      'Nc3 — developing into the attack.',
      '…g6 — Black is lost; White is winning material and the attack.',
    ],
    cues: ['Nxg5 — smash in', 'h6 — try to trap it', 'Qh5+ — queen joins', 'Kd8 — king moves', 'Nf7+ — fork the king', 'Kc7 — king flees', 'Nc3 — pile in', 'g6 — White is winning'],
  },
};

const r = apply(narr);
console.log('english-tromp:', JSON.stringify(r));
