// Final batch — the last groundable plans, re-derived from canonical variation
// entry positions + walk-back, all real winning-game lines. 27 plans.
// Deferred (5, not sound): caro-panov, pirc-150-b5, qgd-tartakower-b6,
// KID-makogonov-kingside, Naj-classical-development.
const { apply } = require('../apply-plan-narration.cjs');

const W = (id, title, intro, overview, pm, pb, themes, endg, arrows, ann, cues) => ({
  [id]: { title, intro, overview, pieceManeuvers: pm, pawnBreaks: pb, strategicThemes: themes, endgameTransitions: endg, greenArrowIdx: arrows, annotations: ann, cues },
});

const narr = Object.assign({},
  W('mp-progothamchess-antisic-e6-open', 'Anti-Sicilian vs …e6: the e5 Wedge',
    'A real GothamChess win. The e5-pawn cramps Black and the knight dominates e5.',
    'A real GothamChess win: e5 grabs central space, and after …f6 White recaptures with the knight, planting it on the strong e5 outpost — clearly better (~+1.2).',
    [{ piece: 'Knight', route: 'to the e5 outpost', explanation: 'The knight recaptures on e5, dominating the centre.' }],
    [{ move: 'e4-e5 wedge', explanation: 'e5 cramps Black and supports the knight outpost.', fen: '' }],
    ['Cramp with the e5-wedge.', 'Plant the knight on e5.'], ['The strong knight tells into the endgame.'], [0, 6],
    ['e5 — the pawn jabs forward, gaining central space.', '…Be7 — Black retreats the bishop.', 'Nf1 — the knight reroutes toward e3 and g3.', '…f6 — Black strikes at the e5-wedge.', 'Bf4 — White develops, defending e5.', '…fxe5 — Black opens the f-file.', 'Nxe5 — White recaptures; the knight dominates e5.', '…Bf6 — Black challenges, but White’s strong knight gives a clear edge.'],
    ['e5 — jab, gain space', 'Be7 — retreat', 'Nf1 — reroute', 'f6 — strike the wedge', 'Bf4 — defend e5', 'fxe5 — open the f-file', 'Nxe5 — dominate e5', 'Bf6 — White is better']),

  W('mp-progothamchess-french-rubinstein-qxd4', 'French Rubinstein: Trade Down to Equality',
    'A real GothamChess win. The position simplifies to a balanced game where White holds steady.',
    'A real GothamChess win: deep in the middlegame the pieces trade off and the centre clarifies — a balanced, equal position (~level).',
    [{ piece: 'Queen', route: '...Qe6 centralise', explanation: 'The queen centralises on e6, offering a trade.' }],
    [{ move: '...f-file pressure', explanation: '…fxe3 opens the f-file for Black.', fen: '' }],
    ['Simplify into equality.', 'Centralise the queen.'], ['The balanced structure holds into the endgame.'], [3],
    ['c5 — White grabs space.', '…fxe3 — Black captures, opening the f-file.', 'Qxe3 — White recaptures.', '…Qe6 — Black centralises the queen, offering a trade.', 'Qe4 — White declines and centralises.', '…Qc8 — Black repositions.', 'cxd6 — White captures.', '…cxd6 — Black recaptures; a balanced, equal game.'],
    ['c5 — White grabs space', 'fxe3 — open the f-file', 'Qxe3 — recapture', 'Qe6 — centralise', 'Qe4 — decline', 'Qc8 — reposition', 'cxd6 — capture', 'cxd6 — equal']),

  // ===== Alekhine (black) =====
  W('mp-pronaroAlek-modernquiet-conversion', 'Alekhine Modern: Active Defence',
    'A real Naroditsky win. Black tucks the king and meets White’s probes with active pieces.',
    'A real Naroditsky win: Black tucks the king, redevelops the knight, activates the rook and checks with …Qa5+ for a balanced, active game (~level).',
    [{ piece: 'Knight', route: '...Nd5-f6 redeploy', explanation: 'The knight redeploys to f6, eyeing the centre.' }],
    [{ move: '...c5 freeing break', explanation: 'An eventual …c5 frees Black’s game.', fen: '' }],
    ['Tuck the king and defend actively.', 'Gain tempo with …Qa5+.'], ['The active pieces hold the balance.'], [4],
    ['Ng5 — White’s knight probes g5.', '…Kc8 — Black tucks the king.', 'c4 — White grabs space.', '…Nf6 — Black redevelops the knight.', 'Nf7 — the knight raids f7.', '…Rh4 — Black activates the rook.', 'Be3 — White develops.', '…Qa5+ — Black checks, gaining a tempo; a balanced game.'],
    ['Ng5 — probe', 'Kc8 — tuck the king', 'c4 — grab space', 'Nf6 — redeploy', 'Nf7 — raid f7', 'Rh4 — activate', 'Be3 — develop', 'Qa5+ — gain a tempo']),
  W('mp-pronaroAlek-modern-nb4', 'Alekhine Modern: Pin and Trade',
    'A real Naroditsky win vs the centre. Black pins with …Bc5 and trades into a better game.',
    'A real Naroditsky win: …Bc5 develops with a pin, Black castles, and the dark bishops and queens trade off leaving Black clearly better (~+1.7).',
    [{ piece: 'Bishop', route: '...Bf8-c5 pin', explanation: 'The bishop develops to c5 with a pin on the e3-bishop.' }],
    [{ move: '...c5 break', explanation: 'The …c5 break frees Black’s position.', fen: '' }],
    ['Pin with …Bc5.', 'Trade the dark bishops and queens.'], ['The better game persists into the endgame.'], [1],
    ['Be3 — White develops.', '…Bc5 — Black develops with tempo, pinning.', 'Rad1 — White centralises.', '…O-O — Black castles.', 'Nc3 — White develops.', '…Bxe3 — Black trades the bishops.', 'Qxe3 — White recaptures.', '…Qxe3 — Black trades queens, with the better game.'],
    ['Be3 — develop', 'Bc5 — pin', 'Rad1 — centralise', 'O-O — castle', 'Nc3 — develop', 'Bxe3 — trade bishops', 'Qxe3 — recapture', 'Qxe3 — Black is better']),
  W('mp-pronaroAlek-quiet-d5break', 'Alekhine Quiet: Queenside Counterplay',
    'A real Naroditsky win. Black trades the fianchetto and storms the queenside.',
    'A real Naroditsky win: the dark bishops come off, Black takes the c-file, and …c5-c4 storms the queenside for a clear edge (~+3.6).',
    [{ piece: 'Rook', route: '...Ra8-c8 file', explanation: 'The rook takes the c-file ahead of the queenside push.' }],
    [{ move: '...c5-c4 queenside', explanation: '…c5 then …c4 storm the queenside.', fen: '' }],
    ['Trade the fianchetto bishops.', 'Storm the queenside with …c5-c4.'], ['The queenside pawns tell into the endgame.'], [5],
    ['Bh6 — White offers a trade of dark bishops.', '…Rc8 — Black takes the c-file.', 'Bxg7 — White trades.', '…Kxg7 — Black recaptures.', 'Rad1 — White centralises.', '…c5 — Black strikes on the queenside.', 'Na4 — White’s knight probes.', '…c4 — Black gains queenside space, clearly better.'],
    ['Bh6 — offer a trade', 'Rc8 — take the c-file', 'Bxg7 — trade', 'Kxg7 — recapture', 'Rad1 — centralise', 'c5 — strike', 'Na4 — probe', 'c4 — Black is better']),
  W('mp-pronaroAlek-twoknights-equality', 'Alekhine Two Knights: Fianchetto and Equalise',
    'A real Naroditsky win. Black fianchettoes, castles, and meets White’s f4 with active play.',
    'A real Naroditsky win: Black reroutes the knight, fianchettoes, castles, and when White strikes f4 opens the f-file — comfortably better (~+1.2).',
    [{ piece: 'Bishop', route: '...Bg7 fianchetto', explanation: 'The bishop fianchettoes to g7 on the long diagonal.' }],
    [{ move: '...exf4 file-opening', explanation: '…exf4 opens the f-file for Black.', fen: '' }],
    ['Fianchetto and castle.', 'Meet f4 with …exf4.'], ['The active pieces hold the edge.'], [3],
    ['Qh3 — White’s queen eyes the kingside.', '…Nd8 — Black reroutes the knight.', 'Ne4 — White centralises.', '…Bg7 — Black fianchettoes.', 'Bh6 — White targets the fianchetto.', '…O-O — Black castles.', 'f4 — White strikes.', '…exf4 — Black opens the f-file, comfortably better.'],
    ['Qh3 — eye the kingside', 'Nd8 — reroute', 'Ne4 — centralise', 'Bg7 — fianchetto', 'Bh6 — target it', 'O-O — castle', 'f4 — strike', 'exf4 — Black is better']),
  W('mp-pronaroAlek-twoknights-trade', 'Alekhine Two Knights: Trade into Activity',
    'A real Naroditsky win. The same fianchetto setup, reaching an active, better game.',
    'A real Naroditsky win: Black reroutes, fianchettoes and castles; when White lunges f4, …exf4 opens the f-file and Black is comfortably better (~+1.2).',
    [{ piece: 'Bishop', route: '...Bg7 fianchetto', explanation: 'The bishop fianchettoes to g7.' }],
    [{ move: '...exf4 file-opening', explanation: '…exf4 opens the f-file.', fen: '' }],
    ['Fianchetto and castle.', 'Open the f-file with …exf4.'], ['The active pieces hold the edge.'], [3],
    ['Qh3 — White’s queen eyes the kingside.', '…Nd8 — Black reroutes the knight.', 'Ne4 — White centralises.', '…Bg7 — Black fianchettoes.', 'Bh6 — White targets the fianchetto.', '…O-O — Black castles.', 'f4 — White strikes.', '…exf4 — Black opens the f-file, comfortably better.'],
    ['Qh3 — eye the kingside', 'Nd8 — reroute', 'Ne4 — centralise', 'Bg7 — fianchetto', 'Bh6 — target it', 'O-O — castle', 'f4 — strike', 'exf4 — Black is better']),

  // ===== Fantasy Caro (white) =====
  W('mp-pronaroFantasy-kingside-attack', 'Fantasy Caro: Damage the Kingside',
    'A real Naroditsky win. White trades off the bishop to wreck the kingside, then clamps the centre.',
    'A real Naroditsky win: Nxg6 damages Black’s kingside pawns, and d5/c4 clamp the centre while Black’s king sits exposed — clearly better (~+2).',
    [{ piece: 'Pawn', route: 'd4-d5 clamp', explanation: 'The d-pawn clamps the centre after the kingside damage.' }],
    [{ move: 'd4-d5 clamp', explanation: 'd5 clamps the centre while the king is exposed.', fen: '' }],
    ['Damage the kingside with Nxg6.', 'Clamp the centre with d5.'], ['The damaged kingside tells into the endgame.'], [0, 4],
    ['Nxg6 — White grabs the bishop, damaging the kingside.', '…hxg6 — Black recaptures, opening the h-file.', 'Nf3 — White develops.', '…O-O-O — Black castles long.', 'd5 — White clamps the centre.', '…c5 — Black strikes back.', 'c4 — White supports d5.', '…a6 — Black regroups, but the damaged kingside leaves White clearly better.'],
    ['Nxg6 — wreck the kingside', 'hxg6 — open the h-file', 'Nf3 — develop', 'O-O-O — castle long', 'd5 — clamp', 'c5 — strike back', 'c4 — support d5', 'a6 — White is better']),

  // ===== Jobava London (white) =====
  W('mp-pronaroJobava-central-queen-attack', 'Jobava London: Win the Exchange in the Melee',
    'A real Naroditsky win. White grabs the exchange on d8 and the central tactics favour him.',
    'A real Naroditsky win: Bxd8 wins the exchange, and after the central e4/exf5 tactics White emerges up material — clearly better (~+2.3).',
    [{ piece: 'Bishop', route: 'Bxd8 exchange', explanation: 'The bishop grabs the rook on d8, winning the exchange.' }],
    [{ move: 'e3-e4 break', explanation: 'e4 opens the centre in the tactical melee.', fen: '' }],
    ['Win the exchange on d8.', 'Open the centre with e4.'], ['Up material, trades close it out.'], [2],
    ['Bxd8 — White grabs the exchange on d8.', '…Rxd8 — Black recaptures.', 'e4 — White strikes the centre.', '…Nxb2 — Black grabs a pawn.', 'exf5 — White takes the bishop, opening lines.', '…Nxd1 — Black grabs the rook.', 'Nxd1 — White recaptures.', '…gxf5 — Black recaptures; White is up material and clearly better.'],
    ['Bxd8 — win the exchange', 'Rxd8 — recapture', 'e4 — strike the centre', 'Nxb2 — grab a pawn', 'exf5 — open lines', 'Nxd1 — grab the rook', 'Nxd1 — recapture', 'gxf5 — White is up']),
  W('mp-pronaroJob-french-attack', 'Jobava London vs …e6: Grab the Centre',
    'A real Naroditsky win. White snaps the d5-pawn, trades with check, and rolls e5.',
    'A real Naroditsky win: Nxd5 grabs the central pawn, Nxe7+ trades with check, and e5 gains space — White is a clean pawn up (~+1.6).',
    [{ piece: 'Knight', route: 'Nxd5 then Nxe7+', explanation: 'The knight grabs d5 and trades on e7 with check.' }],
    [{ move: 'e4-e5 space', explanation: 'e5 gains central space, a pawn up.', fen: '' }],
    ['Grab the central pawn.', 'Roll e5 for space.'], ['A pawn up, trades favour White.'], [0, 6],
    ['Nxd5 — White grabs the central pawn.', '…Nb4 — Black’s knight jumps in.', 'Nxe7+ — White grabs the bishop with check.', '…Qxe7 — Black recaptures.', 'a3 — White kicks the b4-knight.', '…Nc6 — the knight retreats.', 'e5 — White gains central space.', '…Ng4 — Black seeks counterplay, but White is a clean pawn up.'],
    ['Nxd5 — grab the pawn', 'Nb4 — jump in', 'Nxe7+ — trade with check', 'Qxe7 — recapture', 'a3 — kick the knight', 'Nc6 — retreat', 'e5 — gain space', 'Ng4 — White is up']),
  W('mp-pronaroJob-slav-trade', 'Jobava London vs …c6: Kingside Strike',
    'A real Naroditsky win. White aims the bishop at h7 and strikes f5.',
    'A real Naroditsky win: the bishop lines up toward h7, White castles and centralises, and f5 cracks the kingside — clearly better (~+2.3).',
    [{ piece: 'Bishop', route: 'Bf1-d3 to h7', explanation: 'The bishop lines up on d3 toward h7.' }],
    [{ move: 'f4-f5 strike', explanation: 'f5 cracks open the kingside.', fen: '' }],
    ['Aim the bishop at h7.', 'Strike the kingside with f5.'], ['The kingside initiative tells into the endgame.'], [6],
    ['Bd3 — White lines the bishop up toward h7.', '…Bd7 — Black develops.', 'O-O — White castles.', '…Bc6 — Black redeploys the bishop.', 'Rae1 — White centralises.', '…Qe7 — Black connects.', 'f5 — White strikes on the kingside.', '…Nxd3 — Black trades, but White’s kingside initiative gives the edge.'],
    ['Bd3 — aim at h7', 'Bd7 — develop', 'O-O — castle', 'Bc6 — redeploy', 'Rae1 — centralise', 'Qe7 — connect', 'f5 — strike', 'Nxd3 — White presses']),
  W('mp-pronaroJob-slav-rad1', 'Jobava London vs …c6: the Ng6 Raid',
    'A real Naroditsky win. The knight raids g6 and the rook crashes into h7.',
    'A real Naroditsky win: the knight raids g6, the rook grabs h7, and White emerges a pawn up with the safer king (~+1.9).',
    [{ piece: 'Knight', route: 'to g6 raid', explanation: 'The knight raids g6 to open the h-file.' }],
    [{ move: 'h-file grab', explanation: 'Rxh7 grabs a pawn and the open file.', fen: '' }],
    ['Raid g6 with the knight.', 'Grab h7 and the open file.'], ['A pawn up with the safer king.'], [2],
    ['Qd3 — White centralises the queen.', '…Bd6 — Black develops.', 'Ng6 — White’s knight raids g6.', '…Rg8 — Black defends.', 'Rxh7 — White grabs a pawn, the rook crashing in.', '…Nf8 — Black defends.', 'Nxf8 — White trades.', '…Kxf8 — Black recaptures; White is a pawn up with the safer king.'],
    ['Qd3 — centralise', 'Bd6 — develop', 'Ng6 — raid g6', 'Rg8 — defend', 'Rxh7 — grab the pawn', 'Nf8 — defend', 'Nxf8 — trade', 'Kxf8 — White is up']),

  // ===== KIA (white) =====
  W('mp-pronaroKIA-symmetric-attack', 'KIA Symmetric: Long-Diagonal Bishop',
    'A real Naroditsky win. White recaptures on the long diagonal and presses a small edge.',
    'A real Naroditsky win: the bishop recaptures on f3 raking the long diagonal, the centre opens, and White presses a small, pleasant pull (~+0.6).',
    [{ piece: 'Bishop', route: 'recapture on f3', explanation: 'The bishop recaptures on f3, raking the long diagonal.' }],
    [{ move: 'e4xd5 break', explanation: 'exd5 opens the centre.', fen: '' }],
    ['Hold the long diagonal.', 'Press the small edge.'], ['The pull persists into the endgame.'], [0],
    ['Bxf3 — White recaptures, the bishop on the long diagonal.', '…cxd5 — Black opens the centre.', 'exd5 — White recaptures.', '…Nac4 — Black’s knight jumps to c4.', 'Rd1 — White centralises.', '…Nd6 — the knight reroutes.', 'h4 — White gains kingside space.', '…Nbc4 — Black regroups; White holds a small edge.'],
    ['Bxf3 — long diagonal', 'cxd5 — open the centre', 'exd5 — recapture', 'Nac4 — jump in', 'Rd1 — centralise', 'Nd6 — reroute', 'h4 — gain space', 'Nbc4 — White is better']),
  W('mp-pronaroKIA-symmetric-e5push', 'KIA Symmetric: the e4 Break',
    'A real Naroditsky win. White trades the dark bishops and strikes e4.',
    'A real Naroditsky win: White pins with Bg5, trades the dark bishops, and the e3-e4 break opens the centre — clearly better (~+1.8).',
    [{ piece: 'Pawn', route: 'e3-e4 break', explanation: 'The e-pawn breaks to e4, opening the centre.' }],
    [{ move: 'e3-e4 break', explanation: 'e4 strikes the centre after the trades.', fen: '' }],
    ['Trade the dark bishops.', 'Strike with e4.'], ['The central break tells into the endgame.'], [6],
    ['Bg5 — White develops, pinning.', '…f5 — Black grabs kingside space.', 'e3 — White prepares e4.', '…Bf6 — Black challenges the bishop.', 'Bxf6 — White trades.', '…Rxf6 — Black recaptures.', 'e4 — White strikes the centre.', '…Qf8 — Black regroups; White is clearly better with the break.'],
    ['Bg5 — pin', 'f5 — grab space', 'e3 — prepare e4', 'Bf6 — challenge', 'Bxf6 — trade', 'Rxf6 — recapture', 'e4 — strike', 'Qf8 — White is better']),
  W('mp-pronaroKIA-reti-attack', 'KIA / Réti: Win a Piece in the Centre',
    'A real Naroditsky win. White’s knights snap off material in the centre.',
    'A real Naroditsky win: Nxc6 and Nxb4 grab a piece, and Qa4 hits the loose pawns — White is winning material (~+9).',
    [{ piece: 'Knight', route: 'Nxc6 then Nxb4', explanation: 'The knights grab on c6 and b4, winning a piece.' }],
    [{ move: 'central grabs', explanation: 'The knights snap off c6 and b4 in the centre.', fen: '' }],
    ['Snap off the central material.', 'Hit the loose pawns with Qa4.'], ['A piece up, the win is routine.'], [2],
    ['Nxc6 — White grabs the knight.', '…bxc6 — Black recaptures, damaging the queenside.', 'Nxb4 — White grabs the bishop, winning a piece.', '…Rad8 — Black activates.', 'Qa4 — White hits the loose c6-pawn.', '…Rd2 — Black’s rook infiltrates.', 'Nxc6 — White grabs another pawn.', '…Rxe2 — Black grabs a pawn back, but White is winning a piece.'],
    ['Nxc6 — grab the knight', 'bxc6 — recapture', 'Nxb4 — win a piece', 'Rad8 — activate', 'Qa4 — hit c6', 'Rd2 — infiltrate', 'Nxc6 — grab a pawn', 'Rxe2 — White is winning']),
  W('mp-pronaroKIA-reti-nc4', 'KIA / Réti: Central Knights Win Material',
    'A real Naroditsky win. The same central knight grabs net a piece.',
    'A real Naroditsky win: Nxc6 and Nxb4 win a piece, and Qa4 mops up the loose pawns — winning material (~+9).',
    [{ piece: 'Knight', route: 'Nxc6 then Nxb4', explanation: 'The knights grab on c6 and b4, netting a piece.' }],
    [{ move: 'central grabs', explanation: 'The knights snap off c6 and b4.', fen: '' }],
    ['Win the central material.', 'Mop up with the queen.'], ['A piece up, the win is routine.'], [2],
    ['Nxc6 — White grabs the knight.', '…bxc6 — Black recaptures, damaging the queenside.', 'Nxb4 — White grabs the bishop, winning a piece.', '…Rad8 — Black activates.', 'Qa4 — White hits the loose c6-pawn.', '…Rd2 — Black’s rook infiltrates.', 'Nxc6 — White grabs another pawn.', '…Rxe2 — Black grabs one back, but White is winning a piece.'],
    ['Nxc6 — grab the knight', 'bxc6 — recapture', 'Nxb4 — win a piece', 'Rad8 — activate', 'Qa4 — hit c6', 'Rd2 — infiltrate', 'Nxc6 — grab a pawn', 'Rxe2 — White is winning']),

  // ===== Najdorf (black) =====
  W('mp-pronaroNaj-english-race', 'Najdorf English Attack: …d5 Counter-Strike',
    'A real Naroditsky win. Black grabs queenside space and strikes …d5 for active play.',
    'A real Naroditsky win: Black expands with …c5, centralises the rook, and breaks …d5 to free the position — clearly better (~+1.2).',
    [{ piece: 'Rook', route: '...Rf8-d8 file', explanation: 'The rook comes to d8 to back the …d5 break.' }],
    [{ move: '...d5 central break', explanation: '…d5 strikes the centre and frees Black’s game.', fen: '' }],
    ['Expand with …c5.', 'Break the centre with …d5.'], ['The active pieces tell into the endgame.'], [5],
    ['f4 — White expands on the kingside.', '…c5 — Black grabs queenside space.', 'Bf3 — White repositions.', '…Rfd8 — Black centralises the rook.', 'Qf2 — White regroups.', '…d5 — Black strikes the centre.', 'exd5 — White captures.', '…exd5 — Black recaptures with active play, clearly better.'],
    ['f4 — White expands', 'c5 — grab space', 'Bf3 — reposition', 'Rfd8 — centralise', 'Qf2 — regroup', 'd5 — strike', 'exd5 — capture', 'exd5 — Black is better']),
  W('mp-pronaroNaj-adams-defense', 'Najdorf: Castle and Equalise',
    'A real Naroditsky win. Black gains queenside space and castles to a balanced game.',
    'A real Naroditsky win: Black grabs space with …a4, opens the f-file with …exf4, castles to safety and redeploys — a balanced Najdorf (~level).',
    [{ piece: 'Knight', route: '...Nd7 redeploy', explanation: 'The knight redeploys to d7 to support …b5 and …e5.' }],
    [{ move: '...exf4 file-opening', explanation: '…exf4 opens the f-file.', fen: '' }],
    ['Gain queenside space with …a4.', 'Castle to safety and redeploy.'], ['The balanced structure holds into the endgame.'], [5],
    ['f4 — White strikes.', '…a4 — Black gains queenside space.', 'Nd2 — White reroutes.', '…exf4 — Black opens the f-file.', 'Ne4 — White centralises.', '…O-O — Black castles to safety.', 'Bxf4 — White recaptures.', '…Nd7 — Black redeploys; a balanced Najdorf.'],
    ['f4 — White strikes', 'a4 — grab space', 'Nd2 — reroute', 'exf4 — open the f-file', 'Ne4 — centralise', 'O-O — castle', 'Bxf4 — recapture', 'Nd7 — balanced']),

  // ===== Rossolimo (white) =====
  W('mp-pronaroRoss-bd7-conversion', 'Rossolimo: Fianchetto and Press',
    'A real Naroditsky win. White fianchettoes the bishop and presses a small edge.',
    'A real Naroditsky win: the bishop takes the long diagonal from b2, White centralises the rooks and reroutes the light bishop — a pleasant pull (~+0.9).',
    [{ piece: 'Bishop', route: 'Bc1-b2 long diagonal', explanation: 'The bishop fianchettoes to b2 on the long diagonal.' }],
    [{ move: 'e-file pressure', explanation: 'White works the centre behind the fianchetto.', fen: '' }],
    ['Fianchetto on b2.', 'Press the small edge.'], ['The pull persists into the endgame.'], [2],
    ['b3 — White prepares to fianchetto.', '…Bd7 — Black develops.', 'Bb2 — White takes the long diagonal.', '…Rc8 — Black takes the c-file.', 'Rfe1 — White centralises.', '…Re8 — Black contests.', 'Bf1 — White reroutes the bishop.', '…Qa5 — Black eyes the queenside; White holds a small edge.'],
    ['b3 — prep fianchetto', 'Bd7 — develop', 'Bb2 — long diagonal', 'Rc8 — take the c-file', 'Rfe1 — centralise', 'Re8 — contest', 'Bf1 — reroute', 'Qa5 — White is better']),
  W('mp-pronaroRoss-bd7-attack', 'Rossolimo: Punish the …b5 Push',
    'A real Naroditsky win. Black’s …b5 is met head-on and White wins a pawn.',
    'A real Naroditsky win: when Black pushes …b5, White captures and the bishop grabs the pawn, emerging a clean pawn up (~+0.8).',
    [{ piece: 'Knight', route: 'Nf3-d2 reroute', explanation: 'The knight reroutes via d2 to support the centre.' }],
    [{ move: 'c4xb5 grab', explanation: 'cxb5 and Bxb5 win the queenside pawn.', fen: '' }],
    ['Meet …b5 head-on.', 'Win the queenside pawn.'], ['A pawn up, trades favour White.'], [4],
    ['Nd2 — White reroutes the knight.', '…b5 — Black strikes on the queenside.', 'cxb5 — White captures.', '…axb5 — Black recaptures, opening the a-file.', 'Bxb5 — White grabs the pawn.', '…d5 — Black strikes the centre.', 'exd5 — White captures.', '…Nxd5 — Black recaptures; White is a pawn up.'],
    ['Nd2 — reroute', 'b5 — Black strikes', 'cxb5 — capture', 'axb5 — recapture', 'Bxb5 — win the pawn', 'd5 — strike', 'exd5 — capture', 'Nxd5 — White is up']),
  W('mp-pronaroRoss-nc6-maroczy', 'Rossolimo …Nc6: Trade Queens, Keep the Pull',
    'A real Naroditsky win. White trades queens via b3 and presses the better structure.',
    'A real Naroditsky win: the queen swings to b3 and trades on b6, and White presses the healthier structure with the rook on e1 — clearly better (~+3.5).',
    [{ piece: 'Queen', route: 'Qd1-b3 then trade', explanation: 'The queen swings to b3 and trades on b6.' }],
    [{ move: 'b2-b3 solid', explanation: 'b3 solidifies as White presses the better structure.', fen: '' }],
    ['Trade queens via b3.', 'Press the healthier structure.'], ['The better structure tells into the endgame.'], [0],
    ['Qb3 — White’s queen eyes b6 and f7.', '…Rb8 — Black defends.', 'Qxb6 — White trades queens.', '…Rxb6 — Black recaptures.', 'b3 — White solidifies.', '…Bf5 — Black develops.', 'Rfe1 — White centralises.', '…O-O — Black castles; White is clearly better.'],
    ['Qb3 — eye b6/f7', 'Rb8 — defend', 'Qxb6 — trade queens', 'Rxb6 — recapture', 'b3 — solidify', 'Bf5 — develop', 'Rfe1 — centralise', 'O-O — White is better']),
  W('mp-pronaroRoss-nc6-b4push', 'Rossolimo …Nc6: Simplify into the Edge',
    'A real Naroditsky win. The same queen trade leaves White pressing the better structure.',
    'A real Naroditsky win: Qb3 trades on b6 and White presses the healthier structure, rooks centralised — clearly better (~+3.5).',
    [{ piece: 'Queen', route: 'Qd1-b3 then trade', explanation: 'The queen swings to b3 and trades on b6.' }],
    [{ move: 'b2-b3 solid', explanation: 'b3 solidifies the structural edge.', fen: '' }],
    ['Trade queens via b3.', 'Press the healthier structure.'], ['The better structure tells into the endgame.'], [0],
    ['Qb3 — White’s queen eyes b6 and f7.', '…Rb8 — Black defends.', 'Qxb6 — White trades queens.', '…Rxb6 — Black recaptures.', 'b3 — White solidifies.', '…Bf5 — Black develops.', 'Rfe1 — White centralises.', '…O-O — Black castles; White is clearly better.'],
    ['Qb3 — eye b6/f7', 'Rb8 — defend', 'Qxb6 — trade queens', 'Rxb6 — recapture', 'b3 — solidify', 'Bf5 — develop', 'Rfe1 — centralise', 'O-O — White is better']),
  W('mp-pronaroRoss-g6-maroczy', 'Rossolimo …g6: Dominate the Centre',
    'A real Naroditsky win. The bishop dominates d5 and White keeps a small edge.',
    'A real Naroditsky win: the bishop sits on d5, the knight probes g5, and after the central trades White presses a small pull (~+1).',
    [{ piece: 'Bishop', route: 'to d5 dominate', explanation: 'The bishop dominates the central d5 square.' }],
    [{ move: 'e5xd6 break', explanation: 'exd6 opens the centre in White’s favour.', fen: '' }],
    ['Dominate d5 with the bishop.', 'Press the small edge.'], ['The central edge persists into the endgame.'], [0],
    ['Bd5 — White’s bishop dominates the centre.', '…Bb7 — Black challenges it.', 'Ng5 — White’s knight probes g5.', '…e6 — Black kicks the bishop.', 'Bf3 — White retreats.', '…d5 — Black strikes the centre.', 'exd6 — White captures en passant.', '…Qd8 — Black regroups; White holds a small edge.'],
    ['Bd5 — dominate d5', 'Bb7 — challenge', 'Ng5 — probe', 'e6 — kick the bishop', 'Bf3 — retreat', 'd5 — strike', 'exd6 — en passant', 'Qd8 — White is better']),
  W('mp-pronaroRoss-e6-taimanov', 'Rossolimo …e6: the d6 Knight Raid',
    'A real Naroditsky win. The knight raids d6 and White trades into a balanced edge.',
    'A real Naroditsky win: Nd6 raids the outpost, and after the queen trade White opens the a-file with a small pull (~+0.5).',
    [{ piece: 'Knight', route: 'to d6 raid', explanation: 'The knight raids the d6 outpost.' }],
    [{ move: 'a-file opening', explanation: 'axb3 opens the a-file after the queen trade.', fen: '' }],
    ['Raid d6 with the knight.', 'Open the a-file.'], ['The small edge holds into the endgame.'], [2],
    ['Bf4 — White develops.', '…Bf5 — Black develops.', 'Nd6 — White’s knight raids d6.', '…Qb6 — Black counterattacks.', 'Qb3 — White offers a queen trade.', '…Qxb3 — Black trades.', 'axb3 — White recaptures, opening the a-file.', '…Bc2 — Black harasses; a balanced game.'],
    ['Bf4 — develop', 'Bf5 — develop', 'Nd6 — raid d6', 'Qb6 — counter', 'Qb3 — offer the trade', 'Qxb3 — trade', 'axb3 — open the a-file', 'Bc2 — balanced']),
  W('mp-pronaroRoss-e6-ne5', 'Rossolimo …e6: Fianchetto and Take the d-file',
    'A real Naroditsky win. White fianchettoes and grabs the d-file for a small pull.',
    'A real Naroditsky win: White prepares the fianchetto, the centre opens, and the rook takes the d-file — a pleasant edge (~+1.1).',
    [{ piece: 'Rook', route: 'Rf1-d1 file', explanation: 'The rook takes the open d-file.' }],
    [{ move: 'd4xc4 trade', explanation: 'dxc4 resolves the centre on White’s terms.', fen: '' }],
    ['Fianchetto and open the centre.', 'Take the d-file.'], ['The d-file pressure tells into the endgame.'], [6],
    ['b3 — White prepares to fianchetto.', '…c4 — Black strikes on the queenside.', 'dxc4 — White captures.', '…dxc4 — Black recaptures.', 'Be3 — White develops.', '…Ba6 — Black develops, eyeing c4.', 'Rfd1 — White takes the d-file.', '…Rd8 — Black contests; White holds a small edge.'],
    ['b3 — prep fianchetto', 'c4 — strike', 'dxc4 — capture', 'dxc4 — recapture', 'Be3 — develop', 'Ba6 — eye c4', 'Rfd1 — take the d-file', 'Rd8 — White is better']),

  // ===== Ruy Lopez (white) =====
  W('mp-pronaroRuy-d3-positional', 'Ruy Lopez d3: Reroute and Trade Down',
    'A real Naroditsky win. White reroutes the knight to g3 and simplifies into a pull.',
    'A real Naroditsky win: the knight reroutes to g3, a4 strikes the queenside, and the centre trades into a small, pleasant edge (~+0.6).',
    [{ piece: 'Knight', route: 'to g3 reroute', explanation: 'The knight reroutes to g3, eyeing f5 and h5.' }],
    [{ move: 'a2-a4 strike', explanation: 'a4 strikes Black’s queenside.', fen: '' }],
    ['Reroute the knight to g3.', 'Strike the queenside with a4.'], ['The small edge holds into the endgame.'], [1],
    ['…Ncd7 — Black reroutes a knight.', 'Ng3 — White’s knight reroutes to g3.', '…Bb7 — Black fianchettoes.', 'a4 — White strikes the queenside.', '…Nf8 — Black reroutes for defence.', 'dxe5 — White opens the centre.', '…dxe5 — Black recaptures.', 'Qxd8 — White trades queens; a small edge.'],
    ['Ncd7 — reroute', 'Ng3 — to g3', 'Bb7 — fianchetto', 'a4 — strike', 'Nf8 — reroute', 'dxe5 — open the centre', 'dxe5 — recapture', 'Qxd8 — White is better']),
  W('mp-pronaroRuy-d3-flank', 'Ruy Lopez d3: the f4 Flank Strike',
    'A real Naroditsky win. White reroutes the knight and strikes f4 on the kingside.',
    'A real Naroditsky win: h3 and Nh2 prepare the kingside, and f4 strikes against Black’s setup — a small, pleasant edge (~+0.9).',
    [{ piece: 'Knight', route: 'Nf3-h2 reroute', explanation: 'The knight reroutes via h2 toward g4 and f1.' }],
    [{ move: 'f2-f4 strike', explanation: 'f4 strikes the kingside.', fen: '' }],
    ['Reroute the knight via h2.', 'Strike the kingside with f4.'], ['The small edge holds into the endgame.'], [5],
    ['…Bf8 — Black reroutes the bishop.', 'h3 — White prepares the kingside expansion.', '…g6 — Black fianchettoes.', 'Nh2 — White’s knight reroutes toward g4 and f1.', '…Bg7 — Black completes the fianchetto.', 'f4 — White strikes on the kingside.', '…d5 — Black counters in the centre.', 'fxe5 — White opens lines; White holds a small edge.'],
    ['Bf8 — reroute', 'h3 — prepare', 'g6 — fianchetto', 'Nh2 — reroute', 'Bg7 — fianchetto', 'f4 — strike', 'd5 — counter', 'fxe5 — White is better']),
);

const r = apply(narr);
console.log('final-batch:', JSON.stringify(r));
