// Naroditsky Caro-Kann (Black) — 5 plans, real 8-ply lines from his wins.
const { apply } = require('../apply-plan-narration.cjs');

const narr = {
  'mp-pronarocaro-classical-kingside-storm': {
    title: 'Caro-Kann Classical: Trade and Equalise',
    intro: 'A real Naroditsky win. Black keeps the good bishop, trades cleanly, and centralises.',
    overview: 'A real Naroditsky win: Black keeps the bishop on its diagonal, trades a piece, develops …Nd7, and centralises the rook — the comfortable equality the Classical Caro promises.',
    pieceManeuvers: [{ piece: 'Rook', route: '...Ra8-d8 centralise', explanation: 'The rook centralises on d8 after the trades.' }],
    pawnBreaks: [{ move: '...c5 freeing break', explanation: 'An eventual …c5 frees Black’s position.', fen: '' }],
    strategicThemes: ['Keep the good light-squared bishop.', 'Trade into solid equality.'],
    endgameTransitions: ['The sound structure equalises into the endgame.'],
    greenArrowIdx: [7],
    annotations: [
      'h3 — White questions the bishop.',
      '…Bh5 — Black keeps the bishop on its diagonal.',
      'Qd2 — White connects.',
      '…Bxe2 — Black trades off a piece.',
      'Bxe2 — White recaptures.',
      '…Nd7 — Black develops the knight.',
      'Bf3 — White repositions.',
      '…Rad8 — Black centralises the rook; comfortable equality.',
    ],
    cues: ['h3 — question the bishop', 'Bh5 — keep the diagonal', 'Qd2 — connect', 'Bxe2 — trade a piece', 'Bxe2 — recapture', 'Nd7 — develop', 'Bf3 — reposition', 'Rad8 — equalise'],
  },
  'mp-pronarocaro-advance-knight-reroute': {
    title: 'Caro-Kann Advance: Strike the e5-Wedge',
    intro: 'A real Naroditsky win vs spicycaterpillar. Black castles long and breaks at the centre with …f6.',
    overview: 'A real Naroditsky win (vs spicycaterpillar): Black castles long, strikes the e5-wedge with …f6, and after the trades the queen is active and lines open in Black’s favour (~+0.7).',
    pieceManeuvers: [{ piece: 'Queen', route: '...Qc7-b6 active', explanation: 'The queen recaptures on b6, active against White’s queenside.' }],
    pawnBreaks: [{ move: '...f6 central break', explanation: '…f6 strikes the e5-wedge and opens lines.', fen: '' }],
    strategicThemes: ['Castle long for activity.', 'Break the e5-wedge with …f6.'],
    endgameTransitions: ['The open lines favour the active side into the endgame.'],
    greenArrowIdx: [3],
    annotations: [
      'h4 — White gains kingside space.',
      '…O-O-O — Black castles long.',
      'Be3 — White develops.',
      '…f6 — Black strikes at the e5-wedge.',
      'Bxb6 — White trades.',
      '…Qxb6 — Black recaptures, the queen active.',
      'exf6 — White captures.',
      '…gxf6 — Black recaptures, opening lines with the better game.',
    ],
    cues: ['h4 — White grabs space', 'O-O-O — castle long', 'Be3 — develop', 'f6 — strike the wedge', 'Bxb6 — White trades', 'Qxb6 — active queen', 'exf6 — capture', 'gxf6 — Black is better'],
  },
  'mp-pronarocaro-exchange-bg4-pin': {
    title: 'Caro-Kann Exchange: Free the Game with …e5',
    intro: 'A real Naroditsky win vs Parhamov. Black develops smoothly and strikes …e5 to equalise.',
    overview: 'A real Naroditsky win (vs Parhamov): Black makes luft, gains queenside space, centralises the rook, and breaks with …e5 to free the position — comfortable equality.',
    pieceManeuvers: [{ piece: 'Rook', route: '...Rf8-e8 file', explanation: 'The rook comes to e8 to back the …e5 break.' }],
    pawnBreaks: [{ move: '...e5 freeing break', explanation: '…e5 strikes the centre and frees Black’s game.', fen: '' }],
    strategicThemes: ['Develop smoothly and gain space.', 'Free the position with …e5.'],
    endgameTransitions: ['The freed position equalises into the endgame.'],
    greenArrowIdx: [5],
    annotations: [
      'Bd3 — White develops.',
      '…h6 — Black makes luft.',
      'Re1 — White takes the e-file.',
      '…a6 — Black gains queenside space.',
      'a4 — White restrains.',
      '…Rfe8 — Black centralises the rook behind the e-pawn.',
      'Qd1 — White repositions.',
      '…e5 — Black strikes the centre, freeing the position; equal.',
    ],
    cues: ['Bd3 — develop', 'h6 — luft', 'Re1 — take the e-file', 'a6 — gain space', 'a4 — restrain', 'Rfe8 — back the e-pawn', 'Qd1 — reposition', 'e5 — free the game'],
  },
  'mp-pronarocaro-kia-b5-expansion': {
    title: 'Caro-Kann vs KIA: Queenside Expansion',
    intro: 'A real Naroditsky win vs BrandonJacobson. Black rolls the queenside pawns to cramp White.',
    overview: 'A real Naroditsky win (vs BrandonJacobson): Black castles, sends the knight to a5, and pushes the queenside pawns all the way to …b3 — cramping White for a clear edge (~+1.7).',
    pieceManeuvers: [{ piece: 'Knight', route: '...Nc6-a5 to c4/b3', explanation: 'The knight reroutes to a5 to support the queenside push.' }],
    pawnBreaks: [{ move: '...b5-b4-b3 expansion', explanation: 'The b-pawn rolls to b3, cramping White’s queenside.', fen: '' }],
    strategicThemes: ['Expand on the queenside.', 'Cramp White with …b3.'],
    endgameTransitions: ['The queenside clamp persists into the endgame.'],
    greenArrowIdx: [3, 7],
    annotations: [
      'h3 — White makes luft.',
      '…O-O — Black castles to safety.',
      'c3 — White solidifies.',
      '…Na5 — Black’s knight heads for c4.',
      'Ba2 — White retreats the bishop.',
      '…Rd8 — Black centralises a rook.',
      'Qe2 — White connects.',
      '…b3 — Black’s pawn jabs the queenside, cramping White; clearly better.',
    ],
    cues: ['h3 — luft', 'O-O — castle to safety', 'c3 — solidify', 'Na5 — head for c4', 'Ba2 — retreat', 'Rd8 — centralise', 'Qe2 — connect', 'b3 — cramp the queenside'],
  },
  'mp-pronarocaro-modern-trade-and-develop': {
    title: 'Caro-Kann Modern: Reroute the Knight Actively',
    intro: 'A real Naroditsky win vs BrandonJacobson. Black trades in the centre and activates the knight.',
    overview: 'A real Naroditsky win (vs BrandonJacobson): Black captures on d5, redeploys the bishop, and reroutes the knight via e6 to g5 for active counterplay — slightly better (~+0.5).',
    pieceManeuvers: [{ piece: 'Knight', route: '...Nc7-e6-g5 reroute', explanation: 'The knight reroutes via e6 to the active g5 square.' }],
    pawnBreaks: [{ move: '...cxd5 central trade', explanation: '…cxd5 resolves the centre on Black’s terms.', fen: '' }],
    strategicThemes: ['Resolve the centre with …cxd5.', 'Reroute the knight to an active post.'],
    endgameTransitions: ['The active knight holds the edge into the endgame.'],
    greenArrowIdx: [5, 7],
    annotations: [
      'd5 — White clamps the centre.',
      '…cxd5 — Black captures.',
      'c5 — White grabs queenside space.',
      '…Bd7 — Black redeploys the bishop.',
      'Nd4 — White centralises.',
      '…Ne6 — Black’s knight challenges d4 and c5.',
      'Rac1 — White takes the c-file.',
      '…Ng5 — Black’s knight reroutes actively; slightly better.',
    ],
    cues: ['d5 — White clamps', 'cxd5 — capture', 'c5 — White grabs space', 'Bd7 — redeploy', 'Nd4 — centralise', 'Ne6 — challenge d4/c5', 'Rac1 — take the c-file', 'Ng5 — active knight'],
  },
};

const r = apply(narr);
console.log('naro-caro:', JSON.stringify(r));
