// Naroditsky Alapin (8, White) + Jobava-bd3 (1, White) + Alekhine (1, Black).
const { apply } = require('../apply-plan-narration.cjs');

const narr = {
  'mp-pronaroAlapin-d5open-mg': {
    title: 'Alapin: Trade Queens, Keep the Centre',
    intro: 'A real Naroditsky win vs Shankland. White castles, simplifies, and keeps the broad pawn centre.',
    overview: 'A real Naroditsky win (vs Shankland): White ignores the knight prods, castles, and after the queens come off keeps a healthy big-pawn centre — a comfortable, balanced game.',
    pieceManeuvers: [{ piece: 'Queen', route: 'Qd1-d4 trade', explanation: 'The queen centralises on d4 to offer the trade and keep the centre.' }],
    pawnBreaks: [{ move: 'c3-d4 centre', explanation: 'The c3/d4 pawns hold the broad Alapin centre.', fen: '' }],
    strategicThemes: ['Castle and ignore the prods.', 'Trade queens but keep the centre.'],
    endgameTransitions: ['The strong centre tells in the endgame.'],
    greenArrowIdx: [5],
    annotations: [
      '…Ng4 — Black’s knight lunges at e3.',
      'O-O — White calmly castles.',
      '…Nxe3 — Black trades on e3.',
      'fxe3 — White recaptures, opening the f-file.',
      '…g6 — Black fianchettoes.',
      'Qd4 — White centralises, offering a queen trade.',
      '…Qxd4 — Black trades queens.',
      'cxd4 — White recaptures, with a strong centre; balanced.',
    ],
    cues: ['Ng4 — Black lunges', 'O-O — castle calmly', 'Nxe3 — trade on e3', 'fxe3 — open the f-file', 'g6 — fianchetto', 'Qd4 — offer the trade', 'Qxd4 — queens off', 'cxd4 — strong centre'],
  },
  'mp-pronaroAlapin-d6main-mg': {
    title: 'Alapin: the b4-b5-b6 Queenside Storm',
    intro: 'A real Naroditsky win vs Nicki2013. A pawn race — White’s queenside rush is faster.',
    overview: 'A real Naroditsky win (vs Nicki2013): White storms b4-b5-b6 while Black races on the kingside, but the queenside pawn jabs deeper and faster — clearly better (~+1.1).',
    pawnBreaks: [{ move: 'b4-b5-b6 storm', explanation: 'The b-pawn storms to b6, splitting Black’s queenside.', fen: '' }],
    pieceManeuvers: [{ piece: 'Bishop', route: 'Be3-d2 sidestep', explanation: 'The bishop sidesteps to d2, out of the f-pawn’s way.' }],
    strategicThemes: ['Win the opposite-wing pawn race.', 'Jab deep with b6.'],
    endgameTransitions: ['The advanced b-pawn is a long-term asset.'],
    greenArrowIdx: [0, 4],
    annotations: [
      'b4 — White storms the queenside.',
      '…f6 — Black answers with the kingside pawns.',
      'b5 — White pushes on.',
      '…f5 — Black races too.',
      'b6 — White’s pawn jabs deep, splitting the queenside.',
      '…f4 — Black’s pawn storms forward.',
      'Bd2 — White sidesteps the bishop, out of the f-pawn’s way.',
      '…Nxb6 — Black grabs the advanced pawn, but White is clearly better.',
    ],
    cues: ['b4 — storm the queenside', 'f6 — Black answers', 'b5 — push on', 'f5 — Black races', 'b6 — jab deep', 'f4 — Black storms', 'Bd2 — sidestep', 'Nxb6 — White is better'],
  },
  'mp-pronaroAlapin-e6french-mg': {
    title: 'Alapin vs …e6: Open the King with Bxh6',
    intro: 'A real Naroditsky win vs NikoTheodorou. White sacrifices on h6 to expose the king.',
    overview: 'A real Naroditsky win (vs NikoTheodorou): Bxh6 rips open the kingside and the queen infiltrates to h6 and f6, generating a lasting attack as Black scrambles to safety (~equal, attack).',
    pieceManeuvers: [{ piece: 'Queen', route: 'Qh5-h6-f6 infiltration', explanation: 'The queen pours into h6 and f6 after the bishop opens the king.' }],
    pawnBreaks: [{ move: 'b-file opening', explanation: 'Rab1 prepares b4-b5 to open lines at the queenside king.', fen: '' }],
    strategicThemes: ['Open the king with Bxh6.', 'Infiltrate with the queen.'],
    endgameTransitions: ['The attack is the point, not an endgame.'],
    greenArrowIdx: [2, 4],
    annotations: [
      'Bxh6 — White sacrifices the bishop to rip open the king.',
      '…gxh6 — Black recaptures, shattering the kingside.',
      'Qxh6 — White grabs the pawn, the queen by the king.',
      '…O-O-O — Black castles long, away from the damage.',
      'Qf6 — White’s queen infiltrates.',
      '…Kb8 — Black tucks the king.',
      'Rab1 — White prepares a queenside pawn storm.',
      '…Rc8 — Black contests; roughly balanced with White attacking.',
    ],
    cues: ['Bxh6 — open the king', 'gxh6 — shatter the kingside', 'Qxh6 — queen by the king', 'O-O-O — flee long', 'Qf6 — infiltrate', 'Kb8 — tuck the king', 'Rab1 — ready b4-b5', 'Rc8 — White attacks'],
  },
  'mp-pronaroAlapin-g6dragon-mg': {
    title: 'Alapin vs …g6: Consolidate the Big Edge',
    intro: 'A real Naroditsky win vs AlexandraBotez. White trades down and converts a dominant position.',
    overview: 'A real Naroditsky win (vs AlexandraBotez): White repositions, castles, and trades the knights, taking the open e-file from a dominant position — clearly winning (~+5).',
    pieceManeuvers: [{ piece: 'Rook', route: 'Rf1-e1 file', explanation: 'The rook takes the open e-file in the dominant position.' }],
    pawnBreaks: [{ move: 'c4-d4 centre', explanation: 'The broad centre underpins White’s dominance.', fen: '' }],
    strategicThemes: ['Trade down from strength.', 'Seize the open e-file.'],
    endgameTransitions: ['The dominant position converts cleanly.'],
    greenArrowIdx: [6],
    annotations: [
      'Bc1 — White repositions the bishop.',
      '…Nd5 — Black centralises a knight.',
      'O-O — White castles.',
      '…b6 — Black fianchettoes.',
      'Nxd5 — White trades the knights.',
      '…Qxd5 — Black recaptures.',
      'Re1 — White takes the open e-file.',
      '…Re8 — Black contests, but White is clearly on top.',
    ],
    cues: ['Bc1 — reposition', 'Nd5 — centralise', 'O-O — castle', 'b6 — fianchetto', 'Nxd5 — trade knights', 'Qxd5 — recapture', 'Re1 — take the e-file', 'Re8 — White dominates'],
  },
  'mp-pronaroAlapin-nc6-mg': {
    title: 'Alapin vs …Nc6: Target the Fianchetto',
    intro: 'A real Naroditsky win vs Zanyglobal. The bishop swings to h6 to press the fianchetto.',
    overview: 'A real Naroditsky win (vs Zanyglobal): the bishop targets the fianchetto from h6, White makes luft and seizes the e-file — a small, pleasant pull (~+0.7).',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bc1-g5-h6 pressure', explanation: 'The bishop reroutes via g5 to h6 to press the fianchetto.' }],
    pawnBreaks: [{ move: 'c4-d4 centre', explanation: 'The broad centre supports the pressure.', fen: '' }],
    strategicThemes: ['Target the g7-fianchetto with Bh6.', 'Seize the e-file.'],
    endgameTransitions: ['The pull persists into the endgame.'],
    greenArrowIdx: [0, 2],
    annotations: [
      'Bg5 — White develops the bishop with pressure.',
      '…g6 — Black fianchettoes.',
      'Bh6 — the bishop targets the fianchetto.',
      '…Re8 — Black centralises a rook.',
      'h3 — White makes luft.',
      '…Nd5 — Black centralises a knight.',
      'Rfe1 — White seizes the e-file.',
      '…Bf8 — Black challenges the h6-bishop; White holds a small edge.',
    ],
    cues: ['Bg5 — develop with pressure', 'g6 — fianchetto', 'Bh6 — target it', 'Re8 — centralise', 'h3 — luft', 'Nd5 — centralise', 'Rfe1 — seize the e-file', 'Bf8 — White is better'],
  },
  'mp-pronaroAlapin-spined6-mg': {
    title: 'Alapin: Sac into the Kingside, Win the Pawn',
    intro: 'A real Naroditsky win vs Salem-AR. A knight sac on g5 nets pawns and a strong centre.',
    overview: 'A real Naroditsky win (vs Salem-AR): when Black overpushes …e4, Nxg5 and Bxg5 recover the material with interest, and cxd5 leaves White a clear pawn up (~+1.1).',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bc1-g5 recapture', explanation: 'The bishop recaptures on g5, active and pressing.' }],
    pawnBreaks: [{ move: 'c4xd5 break', explanation: 'cxd5 grabs the centre pawn after the kingside sac.', fen: '' }],
    strategicThemes: ['Punish the …e4 overpush.', 'Bank the extra pawn.'],
    endgameTransitions: ['A pawn up, trades favour White.'],
    greenArrowIdx: [3],
    annotations: [
      '…e4 — Black pushes a pawn, hitting the knight.',
      'Nxg5 — White grabs a pawn, sacrificing into the kingside.',
      '…hxg5 — Black recaptures the knight.',
      'Bxg5 — White recovers a pawn, the bishop active.',
      '…Qd7 — Black connects.',
      'cxd5 — White grabs a central pawn.',
      '…Bg4 — Black develops with tempo.',
      'Nc3 — White develops; clearly better, a pawn up.',
    ],
    cues: ['e4 — Black overpushes', 'Nxg5 — sac in', 'hxg5 — recapture', 'Bxg5 — recover the pawn', 'Qd7 — connect', 'cxd5 — grab the centre', 'Bg4 — develop', 'Nc3 — a pawn up'],
  },
  'mp-pronaroAlapin-spinee6-mg': {
    title: 'Alapin vs …e6: Open Lines, Harmonious Development',
    intro: 'A real Naroditsky win vs chessawp. White opens the position and develops smoothly.',
    overview: 'A real Naroditsky win (vs chessawp): exd6 opens the position, the bishops take their best diagonals (d3 and b2), and White develops harmoniously — a balanced, pleasant game (~equal).',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bc4-d3 diagonal', explanation: 'The bishop drops to d3, eyeing the b1-h7 diagonal.' }],
    pawnBreaks: [{ move: 'e5xd6 break', explanation: 'exd6 opens the position for the pieces.', fen: '' }],
    strategicThemes: ['Open the position with exd6.', 'Place the bishops on their best diagonals.'],
    endgameTransitions: ['The harmonious pieces hold into the endgame.'],
    greenArrowIdx: [2],
    annotations: [
      'exd6 — White opens the position with the trade.',
      '…Bxd6 — Black recaptures.',
      'Bd3 — White eyes the b1-h7 diagonal.',
      '…Qc7 — Black lines up on the b8-h2 diagonal.',
      'h3 — White makes luft.',
      '…Bf4 — Black’s bishop probes.',
      'Bb2 — White’s bishop takes the long diagonal.',
      '…Bh6 — Black repositions; roughly balanced.',
    ],
    cues: ['exd6 — open the position', 'Bxd6 — recapture', 'Bd3 — eye h7', 'Qc7 — eye h2', 'h3 — luft', 'Bf4 — probe', 'Bb2 — long diagonal', 'Bh6 — balanced'],
  },
  'mp-pronaroAlapin-nf6main-mg': {
    title: 'Alapin Main: Pile on the d-file',
    intro: 'A real Naroditsky win vs VeryOldMuchSlow. White takes the d-file and probes the kingside.',
    overview: 'A real Naroditsky win (vs VeryOldMuchSlow): the rook takes the d-file, the knight reroutes via a3, and Bh6 plus the centralised queen keep up a small, pleasant pull (~+0.5).',
    pieceManeuvers: [{ piece: 'Queen', route: 'Qg4-e4 centralise', explanation: 'The queen centralises on e4, dominating key diagonals.' }],
    pawnBreaks: [{ move: 'c4-d4 centre', explanation: 'The broad centre supports the pressure.', fen: '' }],
    strategicThemes: ['Seize the d-file.', 'Centralise the queen on e4.'],
    endgameTransitions: ['The pull carries into the endgame.'],
    greenArrowIdx: [6],
    annotations: [
      'Rd1 — White takes the d-file.',
      '…Qc7 — Black repositions the queen.',
      'Na3 — White develops the knight, heading for c4 or b5.',
      '…O-O — Black castles.',
      'Bh6 — White’s bishop probes the kingside.',
      '…Rfd8 — Black contests the d-file.',
      'Qe4 — White centralises the queen.',
      '…Qc6 — Black offers a trade; White holds a small edge.',
    ],
    cues: ['Rd1 — take the d-file', 'Qc7 — reposition', 'Na3 — reroute the knight', 'O-O — castle', 'Bh6 — probe', 'Rfd8 — contest', 'Qe4 — centralise', 'Qc6 — White is better'],
  },
  // ===== Jobava London =====
  'mp-pronaroJob-a6c5-bd3': {
    title: 'Jobava London: Harmonious Development',
    intro: 'A real Naroditsky win. White lines the bishop toward h7 and develops every piece smoothly.',
    overview: 'A real Naroditsky win: the queen and bishop aim at the kingside, the rooks come to the central files, and White reaches a harmonious, balanced middlegame (~equal).',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Be4-d3 diagonal', explanation: 'The bishop drops to d3, eyeing the b1-h7 diagonal toward the king.' }],
    pawnBreaks: [{ move: 'e3-e4 lever', explanation: 'An eventual e4 frees the centre to feed the kingside.', fen: '' }],
    strategicThemes: ['Aim the bishop and queen at the kingside.', 'Centralise the rooks.'],
    endgameTransitions: ['The harmonious setup holds into the endgame.'],
    greenArrowIdx: [2],
    annotations: [
      'Qc2 — White centralises the queen toward the kingside.',
      '…Nf6 — Black develops.',
      'Bd3 — White lines the bishop up toward h7.',
      '…b5 — Black expands on the queenside.',
      'Rad1 — White centralises a rook.',
      '…Bb7 — Black fianchettoes.',
      'Rfe1 — White completes development.',
      '…Bxf3 — Black trades off a piece; roughly balanced.',
    ],
    cues: ['Qc2 — eye the kingside', 'Nf6 — develop', 'Bd3 — aim at h7', 'b5 — expand', 'Rad1 — centralise', 'Bb7 — fianchetto', 'Rfe1 — complete development', 'Bxf3 — balanced'],
  },
  // ===== Alekhine =====
  'mp-pronaroAlek-modern-development': {
    title: 'Alekhine Modern: Trade into Easy Equality',
    intro: 'A real Naroditsky win. Black trades queens and activates the pieces to regain the pawn.',
    overview: 'A real Naroditsky win: Black redeploys the knights to e5, trades queens onto the open d-file, and the active bishop is poised to regain the pawn — comfortable equality.',
    pieceManeuvers: [{ piece: 'Knight', route: '...Nd7-e5 + ...Rd8', explanation: 'The knight centralises on e5 and the rook takes the open d-file.' }],
    pawnBreaks: [{ move: '...c5 freeing break', explanation: 'The …c5 break frees Black’s Alekhine.', fen: '' }],
    strategicThemes: ['Centralise the knights on e5.', 'Trade queens and regain the pawn.'],
    endgameTransitions: ['The active pieces equalise into the endgame.'],
    greenArrowIdx: [3],
    annotations: [
      'dxc5 — White grabs a pawn.',
      '…Nd7 — Black redeploys, eyeing e5 and c5.',
      'Be4 — White centralises the bishop.',
      '…Nde5 — Black centralises the knight.',
      'Qxd8 — White trades queens.',
      '…Raxd8 — Black recaptures, the rook on the open d-file.',
      'Nxe5 — White trades.',
      '…Bxe5 — Black recaptures; the active bishop and loose White pawn leave an equal game.',
    ],
    cues: ['dxc5 — White grabs a pawn', 'Nd7 — redeploy', 'Be4 — centralise', 'Nde5 — centralise', 'Qxd8 — trade queens', 'Raxd8 — open d-file', 'Nxe5 — trade', 'Bxe5 — regain the pawn'],
  },
};

const r = apply(narr);
console.log('naro-alapin:', JSON.stringify(r));
