// Naroditsky KID (Black) — 10 clean plans. Deferred (flagged, walk-back pass):
// classical-kingside, classical-c5, makogonov-kingside, fianchetto-simplify.
const { apply } = require('../apply-plan-narration.cjs');

const narr = {
  'mp-pronaroKID-antikidnf3-rooklift': {
    title: 'KID: …Bxh3 Sacrifice Wins the Exchange',
    intro: 'A real Naroditsky win vs Salem-AR. A bishop sac on h3 leads to a knight fork that nets the rook.',
    overview: 'A real Naroditsky win (vs Salem-AR): …Bxh3 rips open the kingside, and the …Nf3+/…Nxe1+ fork collects the rook before …Nxe4 grabs a pawn too — up the exchange (~+1.1).',
    pieceManeuvers: [{ piece: 'Knight', route: '...Ne5-f3-e1 fork', explanation: 'The knight forks from f3 and grabs the rook on e1.' }],
    pawnBreaks: [{ move: '...Bxh3 open the king', explanation: '…Bxh3 sacrifices to open White’s king for the knight fork.', fen: '' }],
    strategicThemes: ['Open the king with …Bxh3.', 'Win the exchange with the …Nf3 fork.'],
    endgameTransitions: ['Up the exchange, trades close it out.'],
    greenArrowIdx: [1, 3],
    annotations: [
      'b3 — White prepares to fianchetto.',
      '…Bxh3 — Black sacrifices the bishop to rip open the kingside.',
      'Bxh3 — White recaptures.',
      '…Nf3+ — Black’s knight forks with check.',
      'Kg2 — the king sidesteps.',
      '…Nxe1+ — Black grabs the rook with check.',
      'Qxe1 — White recaptures.',
      '…Nxe4 — Black snatches a central pawn, up the exchange.',
    ],
    cues: ['b3 — prep fianchetto', 'Bxh3 — sac, open the king', 'Bxh3 — recapture', 'Nf3+ — fork with check', 'Kg2 — sidestep', 'Nxe1+ — grab the rook', 'Qxe1 — recapture', 'Nxe4 — up the exchange'],
  },
  'mp-pronaroKID-antikidnf3-yugoslav': {
    title: 'KID: …Qxe1 and the …Nf3+ Fork',
    intro: 'A real Naroditsky win vs Firouzja2003. Black grabs the rook and forks his way to a winning game.',
    overview: 'A real Naroditsky win (vs Firouzja2003!): Black grabs the e4-pawn, the queen snatches the rook on e1, and …Nf3+ forks to keep the extra material — clearly winning (~+3.5).',
    pieceManeuvers: [{ piece: 'Knight', route: '...Ne5-f3+ fork', explanation: 'The knight forks from f3 to cement the material edge.' }],
    pawnBreaks: [{ move: '...Nxe4 central grab', explanation: '…Nxe4 grabs the centre pawn before the tactics.', fen: '' }],
    strategicThemes: ['Grab the centre, then the rook.', 'Cement the win with the …Nf3+ fork.'],
    endgameTransitions: ['The extra material decides.'],
    greenArrowIdx: [5, 7],
    annotations: [
      'Ne3 — White repositions the knight.',
      '…Be6 — Black develops.',
      'Bf1 — White retreats.',
      '…Nxe4 — Black grabs the centre pawn.',
      'Nxe4 — White recaptures.',
      '…Qxe1 — Black’s queen grabs the rook.',
      'Qxe1 — White recaptures.',
      '…Nf3+ — Black forks with the knight, winning material.',
    ],
    cues: ['Ne3 — reposition', 'Be6 — develop', 'Bf1 — retreat', 'Nxe4 — grab the centre', 'Nxe4 — recapture', 'Qxe1 — grab the rook', 'Qxe1 — recapture', 'Nf3+ — fork, win material'],
  },
  'mp-pronaroKID-fianchetto-queenside': {
    title: 'KID Fianchetto: Equalise on the d-file',
    intro: 'A real Naroditsky win vs alexrustemov. Black meets the c5 break and takes the open file.',
    overview: 'A real Naroditsky win (vs alexrustemov): when White breaks with c5, Black captures, takes the open d-file with the rook, and develops smoothly — comfortable equality.',
    pieceManeuvers: [{ piece: 'Rook', route: '...Re8-d8 file', explanation: 'The rook takes the open d-file after the c5 trade.' }],
    pawnBreaks: [{ move: '...dxc5 trade', explanation: '…dxc5 meets White’s break and opens the d-file.', fen: '' }],
    strategicThemes: ['Meet c5 with …dxc5.', 'Take the open d-file.'],
    endgameTransitions: ['The open file gives easy equality into the endgame.'],
    greenArrowIdx: [5],
    annotations: [
      'Nb3 — White repositions the knight.',
      '…Qc7 — Black repositions the queen.',
      'c5 — White strikes on the queenside.',
      '…dxc5 — Black captures.',
      'Bxc5 — White recaptures.',
      '…Rd8 — Black takes the open d-file.',
      'Qe2 — White connects.',
      '…Be6 — Black develops; comfortable equality.',
    ],
    cues: ['Nb3 — reposition', 'Qc7 — reposition', 'c5 — White strikes', 'dxc5 — capture', 'Bxc5 — recapture', 'Rd8 — take the d-file', 'Qe2 — connect', 'Be6 — equalise'],
  },
  'mp-pronaroKID-fourpawns-reroute': {
    title: 'KID Four Pawns: Clamp with …f4',
    intro: 'A real Naroditsky win vs Indianlad. Black clamps the kingside and reroutes for the attack.',
    overview: 'A real Naroditsky win (vs Indianlad): Black plays the thematic …f4 clamp and reroutes the bishop toward the kingside, setting up the classic KID attack — a balanced, double-edged game.',
    pieceManeuvers: [{ piece: 'Bishop', route: '...Bg7-f6-e7 reroute', explanation: 'The bishop reroutes via f6 to e7, heading for the kingside attack.' }],
    pawnBreaks: [{ move: '...f4 kingside clamp', explanation: '…f4 clamps the kingside, the thematic KID lever.', fen: '' }],
    strategicThemes: ['Clamp the kingside with …f4.', 'Reroute pieces for the attack.'],
    endgameTransitions: ['The kingside play is the point, not an endgame.'],
    greenArrowIdx: [3],
    annotations: [
      'b4 — White expands on the queenside.',
      '…b6 — Black braces.',
      'Nd2 — White reroutes a knight.',
      '…f4 — Black clamps the kingside, the thematic KID lever.',
      'Bf2 — White retreats the bishop.',
      '…Bf6 — Black reroutes the bishop toward the kingside.',
      'Kh1 — White tucks the king.',
      '…Be7 — Black regroups for the kingside attack; balanced.',
    ],
    cues: ['b4 — White expands', 'b6 — brace', 'Nd2 — reroute', 'f4 — clamp the kingside', 'Bf2 — retreat', 'Bf6 — reroute the bishop', 'Kh1 — tuck the king', 'Be7 — ready the attack'],
  },
  'mp-pronaroKID-fourpawns-counter': {
    title: 'KID Four Pawns: the …f5-f4-g5 Race',
    intro: 'A real Naroditsky win vs Antony-soprano01. Black storms the kingside in the classic KID race.',
    overview: 'A real Naroditsky win (vs Antony-soprano01): Black strikes …f5, clamps with …f4, and rolls …g5 — the textbook KID kingside storm against White’s queenside play — a sharp, balanced race.',
    pawnBreaks: [{ move: '...f5-f4 and ...g5 storm', explanation: '…f5-f4 clamps and …g5 storms the kingside.', fen: '' }],
    pieceManeuvers: [{ piece: 'Queen', route: '...Qd8-e7 support', explanation: 'The queen comes to e7 to back the kingside pawns.' }],
    strategicThemes: ['Race on the kingside with …f5-f4-g5.', 'Out-storm White’s queenside play.'],
    endgameTransitions: ['The mutual storms decide before any endgame.'],
    greenArrowIdx: [3, 7],
    annotations: [
      'Rae1 — White centralises a rook.',
      '…Qe7 — Black connects, backing the kingside.',
      'a3 — White prepares b4.',
      '…f5 — Black strikes on the kingside.',
      'b4 — White expands on the queenside.',
      '…f4 — Black clamps with the f-pawn.',
      'Bf2 — White retreats the bishop.',
      '…g5 — Black storms the kingside; the typical KID race.',
    ],
    cues: ['Rae1 — centralise', 'Qe7 — back the pawns', 'a3 — prep b4', 'f5 — strike', 'b4 — White expands', 'f4 — clamp', 'Bf2 — retreat', 'g5 — storm the kingside'],
  },
  'mp-pronaroKID-makogonov-nc5': {
    title: 'KID Makogonov: …f5 Counterplay',
    intro: 'A real Naroditsky win vs Tobias_Koelle. Black strikes …f5 and reroutes for active play.',
    overview: 'A real Naroditsky win (vs Tobias_Koelle): …f5 opens the kingside, and after the trade Black reroutes the knight to c7 for active KID counterplay — a balanced, double-edged game.',
    pieceManeuvers: [{ piece: 'Knight', route: '...Na6-c7 reroute', explanation: 'The knight reroutes to c7, supporting …b5 and …e6.' }],
    pawnBreaks: [{ move: '...f5 break', explanation: '…f5 opens the kingside for Black’s counterplay.', fen: '' }],
    strategicThemes: ['Open the kingside with …f5.', 'Reroute the knight for counterplay.'],
    endgameTransitions: ['The active counterplay holds the balance.'],
    greenArrowIdx: [1],
    annotations: [
      'Qd2 — White connects.',
      '…f5 — Black strikes on the kingside.',
      'exf5 — White captures.',
      '…gxf5 — Black recaptures, opening the g-file.',
      'Bg5 — White’s bishop probes.',
      '…Qd7 — Black connects.',
      'Rae1 — White centralises.',
      '…Nc7 — Black reroutes the knight; a balanced KID with kingside play.',
    ],
    cues: ['Qd2 — connect', 'f5 — strike the kingside', 'exf5 — capture', 'gxf5 — open the g-file', 'Bg5 — probe', 'Qd7 — connect', 'Rae1 — centralise', 'Nc7 — reroute, counterplay'],
  },
  'mp-pronaroKID-petrosian-central': {
    title: 'KID Petrosian: Strike with …d5 and …f6',
    intro: 'A real Naroditsky win vs penguingm1. Black breaks the centre and opens lines for the pieces.',
    overview: 'A real Naroditsky win (vs penguingm1): Black trades on f4, strikes …d5, and challenges the e5-wedge with …f6 — opening the f-file with the better structure (~+0.6).',
    pawnBreaks: [{ move: '...d5 and ...f6 break', explanation: '…d5 and …f6 strike the centre and open lines.', fen: '' }],
    pieceManeuvers: [{ piece: 'Pawn', route: '...fxe5 file-opening', explanation: '…fxe5 opens the f-file for Black’s rook.' }],
    strategicThemes: ['Break the centre with …d5 and …f6.', 'Open the f-file for active play.'],
    endgameTransitions: ['The better structure tells into the endgame.'],
    greenArrowIdx: [2],
    annotations: [
      '…Nxf4 — Black trades off a piece.',
      'Bxf4 — White recaptures.',
      '…d5 — Black strikes the centre.',
      'e5 — White pushes past.',
      '…f6 — Black challenges the e5-wedge.',
      'O-O — White castles.',
      '…fxe5 — Black opens the f-file.',
      'dxe5 — White recaptures; Black has the better structure and open lines.',
    ],
    cues: ['Nxf4 — trade a piece', 'Bxf4 — recapture', 'd5 — strike the centre', 'e5 — White pushes', 'f6 — challenge the wedge', 'O-O — castle', 'fxe5 — open the f-file', 'dxe5 — Black is better'],
  },
  'mp-pronaroKID-petrosian-re8': {
    title: 'KID Petrosian: Open the Centre with …d5',
    intro: 'A real Naroditsky win vs penguingm1. The same central break, reaching an active, balanced game.',
    overview: 'A real Naroditsky win (vs penguingm1): Black trades on f4 and strikes …d5/…f6, opening the f-file for active counterplay — a balanced, dynamic game.',
    pawnBreaks: [{ move: '...d5 central break', explanation: '…d5 strikes the centre and opens lines.', fen: '' }],
    pieceManeuvers: [{ piece: 'Pawn', route: '...f6-...fxe5 file', explanation: '…f6 and …fxe5 open the f-file for Black.' }],
    strategicThemes: ['Strike the centre with …d5.', 'Open the f-file for counterplay.'],
    endgameTransitions: ['The active pieces hold the balance.'],
    greenArrowIdx: [3],
    annotations: [
      'Bd2 — White repositions the bishop.',
      '…Nxf4 — Black trades a piece.',
      'Bxf4 — White recaptures.',
      '…d5 — Black strikes the centre.',
      'e5 — White pushes past.',
      '…f6 — Black challenges the wedge.',
      'O-O — White castles.',
      '…fxe5 — Black opens the f-file with active play; balanced.',
    ],
    cues: ['Bd2 — reposition', 'Nxf4 — trade a piece', 'Bxf4 — recapture', 'd5 — strike the centre', 'e5 — White pushes', 'f6 — challenge it', 'O-O — castle', 'fxe5 — open the f-file'],
  },
  'mp-pronaroKID-saemisch-central': {
    title: 'KID Sämisch: Reroute and Brace',
    intro: 'A real Naroditsky win vs igrok6996. Black trades the dark bishops and sets up counterplay.',
    overview: 'A real Naroditsky win (vs igrok6996): Black eyes the queenside with …Qa5, reroutes the knight to d7, and after the dark bishops come off braces with …f6 for a balanced Sämisch.',
    pieceManeuvers: [{ piece: 'Knight', route: '...Nf6-d7 reroute', explanation: 'The knight reroutes to d7 to support …c5 and …e5.' }],
    pawnBreaks: [{ move: '...c5 / ...b5 counter', explanation: 'Black aims for the queenside …c5/…b5 counter in the Sämisch.', fen: '' }],
    strategicThemes: ['Trade the dark bishops.', 'Reroute the knight for counterplay.'],
    endgameTransitions: ['The balanced structure holds into the endgame.'],
    greenArrowIdx: [3],
    annotations: [
      'Be2 — White develops.',
      '…Qa5 — Black eyes the queenside.',
      'O-O — White castles.',
      '…Nd7 — Black reroutes the knight.',
      'Bxg7 — White trades the dark-squared bishops.',
      '…Kxg7 — Black recaptures.',
      'f4 — White expands in the centre.',
      '…f6 — Black braces; a balanced Sämisch.',
    ],
    cues: ['Be2 — develop', 'Qa5 — eye the queenside', 'O-O — castle', 'Nd7 — reroute', 'Bxg7 — trade bishops', 'Kxg7 — recapture', 'f4 — White expands', 'f6 — brace, balanced'],
  },
  'mp-pronaroKID-saemisch-queenside': {
    title: 'KID Sämisch: the …b5 Queenside Counter',
    intro: 'A real Naroditsky win vs igrok6996. Black strikes …b5 and gets full queenside counterplay.',
    overview: 'A real Naroditsky win (vs igrok6996): Black strikes …b5 on the queenside while White pushes the kingside, and after the trades Black’s counterplay is in full swing (~+0.7).',
    pawnBreaks: [{ move: '...b5 queenside counter', explanation: '…b5 strikes on the queenside, the thematic Sämisch counter.', fen: '' }],
    pieceManeuvers: [{ piece: 'Bishop', route: '...Be6-f7 reroute', explanation: 'The bishop drops to f7 to support the queenside play.' }],
    strategicThemes: ['Counter on the queenside with …b5.', 'Keep the king safe while pushing.'],
    endgameTransitions: ['The queenside play carries into the endgame.'],
    greenArrowIdx: [3],
    annotations: [
      'f4 — White expands in the centre.',
      '…f6 — Black braces the centre.',
      'Kh1 — White tucks the king.',
      '…b5 — Black strikes on the queenside, the thematic Sämisch counter.',
      'f5 — White pushes on.',
      '…Bf7 — Black repositions the bishop.',
      'fxg6 — White opens the f-file.',
      '…hxg6 — Black recaptures; the queenside counterplay is in full swing.',
    ],
    cues: ['f4 — White expands', 'f6 — brace', 'Kh1 — tuck the king', 'b5 — queenside counter', 'f5 — White pushes', 'Bf7 — reposition', 'fxg6 — open the f-file', 'hxg6 — counterplay rolls'],
  },
};

const r = apply(narr);
console.log('naro-kid:', JSON.stringify(r));
