// GothamChess Vienna (7) + Fantasy-Caro (5) — real 8-ply lines from his wins.
const { apply } = require('../apply-plan-narration.cjs');

const narr = {
  // ===== Vienna =====
  'mp-progothamchess-vie-accepted-space': {
    title: 'Vienna: Pile Onto the Weakened Kingside',
    intro: 'A real GothamChess win vs kikoveiga. White’s pieces all swing toward the loosened king.',
    overview: 'A real GothamChess win (vs kikoveiga): the rook lifts to g1, the bishop swings to h3 hitting e6, and the queen centralises on c4 eyeing f7 — every piece pointed at Black’s king.',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bf1-h3 pressure', explanation: 'The bishop reroutes to h3 to rake the c8-h3 diagonal and hit e6.' }],
    pawnBreaks: [{ move: 'f4 kingside lever', explanation: 'The Vienna f-pawn loosens Black’s kingside for the pieces.', fen: '' }],
    strategicThemes: ['Aim every piece at the loosened king.', 'Use the f4 break to open lines.'],
    endgameTransitions: ['The space edge lingers into the endgame.'],
    greenArrowIdx: [0, 2],
    annotations: [
      'Rg1 — the rook lifts to g1, backing a kingside advance.',
      '…Ne6 — the knight reroutes to e6.',
      'Bh3 — the bishop swings to h3, hitting e6 and eyeing the king.',
      '…g6 — shoring up the light squares.',
      'Qc4 — the queen centralises, pressuring f7 and the centre.',
      '…c6 — challenging the queen.',
      'Nc3 — developing the last piece.',
      '…h5 — Black grabs kingside space, but White’s pieces are aimed at the king.',
    ],
    cues: ['Rg1 — back the advance', 'Ne6 — reroute', 'Bh3 — hit e6, eye the king', 'g6 — shore up light squares', 'Qc4 — pressure f7', 'c6 — challenge', 'Nc3 — develop', 'h5 — White aims at the king'],
  },
  'mp-progothamchess-vienna-gambit-main': {
    title: 'Vienna Gambit: Clamp and Dominate',
    intro: 'A real GothamChess win vs Arystanner. White clamps the centre with c4 and lets piece activity decide.',
    overview: 'A real GothamChess win (vs Arystanner): c4 clamps the centre, and after the trade on c4 the d-file opens for the rook while Black’s loose pawns become targets.',
    pieceManeuvers: [{ piece: 'Rook', route: 'Rf1-d1 d-file', explanation: 'The rook takes the d-file after the c4 trade.' }],
    pawnBreaks: [{ move: 'c4 clamp', explanation: 'c4 clamps the centre and opens lines after the exchange.', fen: '' }],
    strategicThemes: ['Clamp the centre with c4.', 'Open the d-file for the rooks.'],
    endgameTransitions: ['The active pieces are worth more than the pawn into the endgame.'],
    greenArrowIdx: [2, 6],
    annotations: [
      'Bg5 — developing the bishop to an aggressive post.',
      '…Rde8 — centralising the rook.',
      'c4 — clamping the centre and gaining space.',
      '…Bxc4 — Black grabs the pawn.',
      'dxc4 — recapturing and opening the d-file.',
      '…d3 — Black pushes a wedge.',
      'Rd1 — the rook lines up on the d-file behind the pawn.',
      '…Nxe5 — Black grabs a pawn, but White’s piece activity dominates.',
    ],
    cues: ['Bg5 — aggressive post', 'Rde8 — centralise', 'c4 — clamp the centre', 'Bxc4 — Black grabs it', 'dxc4 — open the d-file', 'd3 — a wedge', 'Rd1 — work the d-file', 'Nxe5 — White dominates'],
  },
  'mp-progothamchess-vie-f5-buildup': {
    title: 'Vienna: Castle, Centralise, Press',
    intro: 'A real GothamChess win vs Arystanner. A patient build-up — space on the kingside, rooks centralised.',
    overview: 'A real GothamChess win: h4 grabs kingside space, the knight reroutes via h3, both sides castle, and White finishes development with the rook on e1, comfortably better.',
    pieceManeuvers: [{ piece: 'Knight', route: 'Ng1-h3-f4 reroute', explanation: 'The knight reroutes through h3 toward f4 and the kingside.' }],
    pawnBreaks: [{ move: 'h4 kingside space', explanation: 'h4 claims kingside space ahead of the build-up.', fen: '' }],
    strategicThemes: ['Grab kingside space, then complete development.', 'Centralise the rooks before striking.'],
    endgameTransitions: ['The space advantage carries into the endgame.'],
    greenArrowIdx: [0, 2],
    annotations: [
      'h4 — gaining kingside space.',
      '…O-O-O — Black castles long.',
      'Nh3 — the knight reroutes toward f4.',
      '…Rhe8 — centralising the rook.',
      'O-O — White tucks the king away.',
      '…Bf7 — repositioning the bishop.',
      'Rfe1 — the rook takes the e-file.',
      '…h6 — Black makes luft, but White is comfortably better.',
    ],
    cues: ['h4 — grab kingside space', 'O-O-O — Black castles long', 'Nh3 — reroute toward f4', 'Rhe8 — centralise', 'O-O — tuck the king', 'Bf7 — reposition', 'Rfe1 — take the e-file', 'h6 — White is better'],
  },
  'mp-progothamchess-vienna-paulsen-attack': {
    title: 'Vienna Paulsen: Damage the Structure, then Press',
    intro: 'A real GothamChess win vs mirciulica14. White trades to wreck Black’s pawns and posts a strong knight.',
    overview: 'A real GothamChess win (vs mirciulica14): Bxc6 damages Black’s structure, the bishops come off, and the knight lands on g5 eyeing the kingside while a4 grabs queenside space.',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nf3-g5 outpost', explanation: 'The knight recaptures on g5, eyeing f7, e6 and h7.' }],
    pawnBreaks: [{ move: 'a4 queenside space', explanation: 'a4 expands on the queenside once the centre is settled.', fen: '' }],
    strategicThemes: ['Trade to damage Black’s pawn structure.', 'Post the knight aggressively, then expand.'],
    endgameTransitions: ['The damaged pawns favour White into the endgame.'],
    greenArrowIdx: [4],
    annotations: [
      'Bxc6 — trading off to damage Black’s structure.',
      '…Qxc6 — recapturing with the queen.',
      'Bg5 — the bishop offers a trade.',
      '…Bxg5 — Black takes.',
      'Nxg5 — recapturing; the knight eyes f7, e6 and h7.',
      '…Qd7 — defending the kingside.',
      'a4 — gaining queenside space.',
      '…Bf5 — developing, but White’s knight and space hold the edge.',
    ],
    cues: ['Bxc6 — damage the pawns', 'Qxc6 — recapture', 'Bg5 — offer the trade', 'Bxg5 — Black takes', 'Nxg5 — knight eyes f7', 'Qd7 — defend', 'a4 — expand queenside', 'Bf5 — White is better'],
  },
  'mp-progothamchess-vie-gambit-main-attack': {
    title: 'Vienna Gambit: Hold the Centre vs the Pawn Storm',
    intro: 'A real GothamChess win. Black storms the kingside; White’s centralised knight and queen hold firm.',
    overview: 'A real GothamChess win: Black throws the kingside pawns forward, but White develops with Be3, grabs on c5, plants the knight on d4 and tucks the queen on f2 — the centre holds and the storm runs out.',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nf3-d4 centralise', explanation: 'The knight centralises on d4, dominating while Black storms the wing.' }],
    pawnBreaks: [{ move: 'd4xc5 break', explanation: 'dxc5 opens lines and grabs material as Black overextends.', fen: '' }],
    strategicThemes: ['Meet a wing storm with a strong centre.', 'Centralise the knight on d4.'],
    endgameTransitions: ['Once the storm fizzles, White’s pieces dominate the endgame.'],
    greenArrowIdx: [4],
    annotations: [
      'Be3 — developing the bishop.',
      '…g5 — Black lunges on the kingside.',
      'dxc5 — grabbing a pawn and opening lines.',
      '…h5 — Black pushes the storm on.',
      'Nd4 — centralising the knight in the middle of the board.',
      '…h4 — the pawn storm rolls forward.',
      'Qf2 — the queen tucks onto f2, holding the kingside.',
      '…Bxc5 — Black regains the pawn, but White’s centre knight dominates.',
    ],
    cues: ['Be3 — develop', 'g5 — Black lunges', 'dxc5 — grab, open lines', 'h5 — storm on', 'Nd4 — centralise', 'h4 — storm rolls', 'Qf2 — hold the kingside', 'Bxc5 — White dominates'],
  },
  'mp-progothamchess-vie-nc6-forcing': {
    title: 'Vienna: Win the Queen, then Hunt the King',
    intro: 'A real GothamChess win vs ChessicallyInclined. A tactic nets the queen; the rest is a king hunt.',
    overview: 'A real GothamChess win: the knight snaps off the queen on f3, and with a decisive material edge White checks the king out into the open with Re1+ and Ne5+.',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nf3 then Ne5+ hunt', explanation: 'The knight wins the queen and later checks from e5 to drive the king out.' }],
    pawnBreaks: [{ move: 'e4-e5 wedge', explanation: 'The e-pawn supports the knight outpost that hunts the king.', fen: '' }],
    strategicThemes: ['Cash the winning tactic.', 'Hunt the exposed king with checks.'],
    endgameTransitions: ['A queen up, no endgame is needed.'],
    greenArrowIdx: [0, 6],
    annotations: [
      'Nxf3 — the knight snaps off the queen; White is winning huge material.',
      '…Bd6 — Black develops in vain.',
      'Bf4 — developing with tempo, offering a trade.',
      '…Nf6 — developing.',
      'Re1+ — check; the rook drives the king out.',
      '…Kd7 — the king is forced to run.',
      'Ne5+ — check; the knight joins the hunt.',
      '…Kc8 — the king flees, and White is completely winning.',
    ],
    cues: ['Nxf3 — win the queen', 'Bd6 — too late', 'Bf4 — develop with tempo', 'Nf6 — develop', 'Re1+ — drive the king', 'Kd7 — king runs', 'Ne5+ — join the hunt', 'Kc8 — White is winning'],
  },
  'mp-progothamchess-vie-quiet-bc4-na4': {
    title: 'Vienna Quiet: Outpost and Shatter the Kingside',
    intro: 'A real GothamChess win vs CoachJKane. White grabs the e5 outpost and breaks up Black’s kingside.',
    overview: 'A real GothamChess win (vs CoachJKane): the bishop seizes the e5 outpost, and Bxf6 shatters Black’s kingside pawns, leaving White with the better structure and the safer king.',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bc1-e5 outpost', explanation: 'The dark-squared bishop seizes the powerful e5 outpost.' }],
    pawnBreaks: [{ move: 'a-file opening', explanation: 'axb3 opens the a-file for the rook after the knight trade.', fen: '' }],
    strategicThemes: ['Seize the e5 outpost.', 'Shatter Black’s kingside with Bxf6.'],
    endgameTransitions: ['The healthier pawns win the endgame.'],
    greenArrowIdx: [2, 6],
    annotations: [
      'Bb3 — retreating the bishop, keeping the strong diagonal.',
      '…c4 — Black hits the bishop.',
      'Be5 — the dark-squared bishop seizes the e5 outpost.',
      '…Nxb3 — Black trades off the light bishop.',
      'axb3 — recapturing and opening the a-file.',
      '…cxd3 — Black grabs a pawn.',
      'Bxf6 — taking the knight and shattering Black’s kingside.',
      '…gxf6 — recapturing with wrecked pawns; White’s structure is far healthier.',
    ],
    cues: ['Bb3 — keep the diagonal', 'c4 — Black hits it', 'Be5 — seize the outpost', 'Nxb3 — trade the bishop', 'axb3 — open the a-file', 'cxd3 — Black grabs a pawn', 'Bxf6 — shatter the kingside', 'gxf6 — White is healthier'],
  },
  // ===== Fantasy-Caro =====
  'mp-progothamchess-fantasy-dxe4-center': {
    title: 'Fantasy Caro: Pry Open the Queenside',
    intro: 'A real GothamChess win vs Styloow. White strikes the queenside with a4 and b4 to open lines.',
    overview: 'A real GothamChess win (vs Styloow): the bishop develops to d3, then a4 and b4 pry at Black’s queenside pawns, opening files while White’s lead in development tells.',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bf1-d3 develop', explanation: 'The bishop develops to d3 before the queenside expansion.' }],
    pawnBreaks: [{ move: 'a4 and b4 queenside', explanation: 'a4 and b4 pry open Black’s queenside pawn chain.', fen: '' }],
    strategicThemes: ['Open the queenside with a4 and b4.', 'Use the development lead.'],
    endgameTransitions: ['Open files favour the better-developed side into the endgame.'],
    greenArrowIdx: [2, 6],
    annotations: [
      'Bd3 — developing the bishop toward the kingside.',
      '…Bg6 — Black offers a trade of light bishops.',
      'a4 — striking at Black’s queenside pawns.',
      '…Rb8 — propping up b5.',
      'axb5 — opening the a-file.',
      '…cxb5 — recapturing.',
      'b4 — clamping and prying open the queenside.',
      '…Qxc3 — Black grabs a pawn, but White’s development lead tells.',
    ],
    cues: ['Bd3 — develop', 'Bg6 — offer a trade', 'a4 — strike the queenside', 'Rb8 — prop up b5', 'axb5 — open the a-file', 'cxb5 — recapture', 'b4 — pry it open', 'Qxc3 — White leads'],
  },
  'mp-progothamchess-fantasy-bxc3-pair': {
    title: 'Fantasy Caro: Win the Exchange on f8',
    intro: 'A real GothamChess win vs MightyGMpretender. The knight jumps to g5 and the bishop snatches the rook.',
    overview: 'A real GothamChess win (vs MightyGMpretender): Ng5 hits f7, and Bxf8 snatches the rook — White wins the exchange and castles to safety with a clear material edge.',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nf3-g5 to f7/f8', explanation: 'The knight jumps to g5, setting up the Bxf8 fork that wins the exchange.' }],
    pawnBreaks: [{ move: 'e4-e5 anchor', explanation: 'The e5-pawn anchors the centre for the kingside raid.', fen: '' }],
    strategicThemes: ['Use Ng5 to hit the kingside.', 'Cash the exchange and consolidate.'],
    endgameTransitions: ['Up the exchange, trades bring the win closer.'],
    greenArrowIdx: [0, 2],
    annotations: [
      'Ng5 — the knight jumps to g5, eyeing f7.',
      '…Nc6 — Black develops.',
      'Bxf8 — snatching the rook; White wins the exchange.',
      '…Qxf8 — recapturing.',
      'O-O — White castles, safe with the extra material.',
      '…Nd8 — Black regroups.',
      'Rf2 — lifting the rook into play.',
      '…Bd7 — developing, but White is up the exchange.',
    ],
    cues: ['Ng5 — eye f7', 'Nc6 — develop', 'Bxf8 — win the exchange', 'Qxf8 — recapture', 'O-O — castle to safety', 'Nd8 — regroup', 'Rf2 — lift the rook', 'Bd7 — White is up material'],
  },
  'mp-progothamchess-fantasy-e6-qg4attack': {
    title: 'Fantasy Caro: Punish the Greedy Rook',
    intro: 'A real GothamChess win. Black grabs g2 with the rook; Nf4 traps it on the offensive.',
    overview: 'A real GothamChess win: when Black’s rook gorges on g2, Nf4 jumps in to hit it and White’s initiative rolls while the rook scrambles back.',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nh3-f4 attack', explanation: 'The knight leaps to f4 to attack the offside g2-rook.' }],
    pawnBreaks: [{ move: 'c4 central space', explanation: 'c4 grabs central space while Black’s rook is offside.', fen: '' }],
    strategicThemes: ['Punish the greedy rook with Nf4.', 'Keep the initiative rolling.'],
    endgameTransitions: ['The initiative converts before any endgame.'],
    greenArrowIdx: [2],
    annotations: [
      'Bd2 — developing the bishop.',
      '…Rxg2 — Black’s rook gorges on the g2-pawn.',
      'Nf4 — the knight leaps in, attacking the stranded rook.',
      '…Rg8 — the rook scrambles back.',
      'Rf1 — activating the rook.',
      '…b6 — Black develops.',
      'c4 — grabbing central space.',
      '…Qa4 — Black seeks counterplay, but White’s initiative dominates.',
    ],
    cues: ['Bd2 — develop', 'Rxg2 — Black grabs g2', 'Nf4 — attack the rook', 'Rg8 — rook retreats', 'Rf1 — activate', 'b6 — develop', 'c4 — central space', 'Qa4 — White presses'],
  },
  'mp-progothamchess-fantasy-g6-poisonpawn': {
    title: 'Fantasy Caro: Crack the Kingside with f5',
    intro: 'A real GothamChess win vs imsuyogwaghYT. f5 rips the kingside open and the pieces swarm.',
    overview: 'A real GothamChess win (vs imsuyogwaghYT): f5 cracks Black’s kingside, the bishop eyes f7 from c4, and the knight grabs the centre on d4 as White’s pieces swarm the king.',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bf1-c4 to f7', explanation: 'The bishop targets f7 from c4 as the kingside opens.' }],
    pawnBreaks: [{ move: 'f4-f5 break', explanation: 'f5 cracks open Black’s kingside pawn cover.', fen: '' }],
    strategicThemes: ['Open the kingside with f5.', 'Swarm the king with the pieces.'],
    endgameTransitions: ['The attack decides before an endgame.'],
    greenArrowIdx: [0, 4],
    annotations: [
      'f5 — the pawn storms forward, cracking open the kingside.',
      '…Qd6 — Black repositions the queen.',
      'O-O — White castles.',
      '…d4 — Black hits the centre.',
      'Bc4 — the bishop eyes f7.',
      '…gxf5 — Black grabs the pawn, opening the g-file.',
      'Nxd4 — the knight grabs the centre, hitting e6 and f5.',
      '…Be5 — Black centralises, but White’s pieces swarm the king.',
    ],
    cues: ['f5 — crack the kingside', 'Qd6 — reposition', 'O-O — castle', 'd4 — hit the centre', 'Bc4 — eye f7', 'gxf5 — open the g-file', 'Nxd4 — grab the centre', 'Be5 — White swarms'],
  },
  'mp-progothamchess-fantasy-qb6-na4': {
    title: 'Fantasy Caro: Swing the Queen to the Kingside',
    intro: 'A real GothamChess win vs jerry_77. Trade the dark bishops, then reroute the queen to h4.',
    overview: 'A real GothamChess win (vs jerry_77): the dark-squared bishops come off, then the queen reroutes via e1 to h4, swinging into the kingside attack.',
    pieceManeuvers: [{ piece: 'Queen', route: 'Qd1-e1-h4 swing', explanation: 'The queen reroutes through e1 to h4 to attack the kingside.' }],
    pawnBreaks: [{ move: 'e4-e5 anchor', explanation: 'The e5-pawn anchors the centre while the queen swings over.', fen: '' }],
    strategicThemes: ['Trade the dark bishops, then attack the kingside.', 'Reroute the queen to h4.'],
    endgameTransitions: ['If the attack is held, the centre still favours White.'],
    greenArrowIdx: [4, 6],
    annotations: [
      'Bf4 — developing and offering a trade.',
      '…Bd6 — Black challenges the bishop.',
      'Bxd6 — trading the dark-squared bishops.',
      '…Qxd6 — recapturing.',
      'Qe1 — rerouting the queen toward the kingside.',
      '…Ng4 — Black’s knight lunges.',
      'Qh4 — the queen swings to h4, joining the attack.',
      '…Ne5 — the knight retreats to the centre, but White’s queen is active.',
    ],
    cues: ['Bf4 — offer a trade', 'Bd6 — challenge', 'Bxd6 — trade bishops', 'Qxd6 — recapture', 'Qe1 — reroute the queen', 'Ng4 — Black lunges', 'Qh4 — swing into the attack', 'Ne5 — White is active'],
  },
};

const r = apply(narr);
console.log('vienna-fantasy:', JSON.stringify(r));
