// Small GothamChess white openings: Ponziani (4), Anti-Sicilian (1), Stafford (1),
// KIA (1), Milner-Barry (2). Real 8-ply lines from his wins, narrated.
const { apply } = require('../apply-plan-narration.cjs');

const narr = {
  // ---- Ponziani ----
  'mp-progothamchess-ponziani-d5-qa4': {
    title: 'Ponziani: the d5-d6 Space Wedge',
    intro: 'A real GothamChess win vs penguingm1. The Ponziani’s early d4-d5 grabs the centre, then d6 wedges deep and cramps Black.',
    overview: 'The Ponziani aims for a quick d4 and a big pawn centre. A real GothamChess win (vs penguingm1): d5 seizes space and shoves the knight back, then d6 wedges into Black’s camp. The cramping pawn leaves Black tied up.',
    pawnBreaks: [{ move: 'd5-d6 wedge', explanation: 'The d-pawn marches to d5 and on to d6, wedging into Black’s position and cramping him.', fen: '' }],
    pieceManeuvers: [{ piece: 'Knight', route: 'Nb1-c3 develop', explanation: 'The last minor piece comes to c3 to support the centre.' }],
    strategicThemes: ['Use the d4-d5-d6 pawn to gain space and cramp Black.', 'Develop quickly behind the advanced centre.'],
    endgameTransitions: ['The space edge persists into the endgame.'],
    greenArrowIdx: [0, 2],
    annotations: [
      'd5 — the centre pawn jabs forward, seizing space and shoving the knight back.',
      '…Nb4 — the knight hops to b4 looking for activity.',
      'd6 — pressing on; the advanced pawn wedges deep into Black’s camp.',
      '…cxd6 — Black challenges the intruder.',
      'cxd6 — recapturing toward the centre; the d6-pawn cramps Black badly.',
      '…Bd8 — the bishop tucks back to untangle.',
      'Nc3 — bringing the last minor piece into play.',
      '…O-O — Black finally castles, but the d6-wedge leaves him passive.',
    ],
    cues: ['d5 — jab, gain space', 'Nb4 — seek activity', 'd6 — wedge in deep', 'cxd6 — challenge it', 'cxd6 — cramp Black', 'Bd8 — untangle', 'Nc3 — develop', 'O-O — Black stays cramped'],
  },
  'mp-progothamchess-ponziani-main-qb3': {
    title: 'Ponziani: Trade the Active Knight on c4',
    intro: 'A real GothamChess win vs Train_Your_Dragon. White restrains, then swaps off Black’s active knight to keep a clean structural edge.',
    overview: 'A real GothamChess win (vs Train_Your_Dragon): a3 restrains Black, the queen steps to c2, and White trades off the knight that reaches c4 — keeping the better structure and the central pawns.',
    pieceManeuvers: [{ piece: 'Knight', route: 'Nxc4 trade', explanation: 'White swaps off Black’s active knight on c4 to keep the cleaner structure.' }],
    pawnBreaks: [{ move: 'a3 restraint', explanation: 'a3 takes the b4-square away before White expands.', fen: '' }],
    strategicThemes: ['Restrain Black’s knight with a3 before expanding.', 'Trade off the active piece to keep the structural edge.'],
    endgameTransitions: ['The healthier pawns favour White in the endgame.'],
    greenArrowIdx: [4],
    annotations: [
      'a3 — a restraining move, taking b4 away from Black’s knight.',
      '…Na5 — the knight reroutes toward the c4 outpost.',
      'Qc2 — the queen steps off the d-file, connecting and eyeing the kingside.',
      '…Nac4 — the knight reaches the c4 square.',
      'Nxc4 — trading off the active knight at once.',
      '…Nxc4 — recapturing, keeping a piece on the outpost.',
      'Bc1 — rerouting the bishop to a better diagonal.',
      '…O-O-O — Black castles long into a passive position.',
    ],
    cues: ['a3 — take b4 away', 'Na5 — reroute', 'Qc2 — connect, eye kingside', 'Nac4 — reach c4', 'Nxc4 — trade it off', 'Nxc4 — recapture', 'Bc1 — reroute the bishop', 'O-O-O — Black is passive'],
  },
  'mp-progothamchess-ponziani-d4-thrust': {
    title: 'Ponziani: the Bd3 + Qc2 Kingside Battery',
    intro: 'A real GothamChess win vs Train_Your_Dragon. White lines the bishop and queen up on the b1-h7 diagonal, aiming at the king.',
    overview: 'A real GothamChess win: the bishop comes to d3 and the queen to c2, forming a battery on the b1-h7 diagonal pointed straight at Black’s king while the dark-squared bishop joins from g5.',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bf1-d3 battery', explanation: 'The bishop lands on d3 to form a battery with the c2-queen aimed at h7.' }],
    pawnBreaks: [{ move: 'e4-e5 central space', explanation: 'The e-pawn anchors the centre so the kingside battery can operate.', fen: '' }],
    strategicThemes: ['Build the Bd3 + Qc2 battery toward h7.', 'Bring every piece to bear on the king.'],
    endgameTransitions: ['If the attack is parried, the central pawns still tell.'],
    greenArrowIdx: [4, 6],
    annotations: [
      'Bf4 — developing the bishop to an active diagonal.',
      '…a4 — Black grabs queenside space.',
      'Qc2 — the queen eyes the b1-h7 diagonal toward Black’s king.',
      '…Ne7 — the knight reroutes to defend.',
      'Bd3 — lining the bishop up with the queen, a battery aimed at h7.',
      '…Ng6 — covering the kingside light squares.',
      'Bg5 — the dark-squared bishop swings to g5 to join in.',
      '…Qd7 — Black untangles, but every White piece points at the king.',
    ],
    cues: ['Bf4 — active bishop', 'a4 — Black takes space', 'Qc2 — eye the diagonal', 'Ne7 — reroute to defend', 'Bd3 — battery toward h7', 'Ng6 — cover the kingside', 'Bg5 — bishop joins in', 'Qd7 — White’s aim holds'],
  },
  'mp-progothamchess-ponziani-nxe4-gambit': {
    title: 'Ponziani Gambit: the Dominant Central Queen',
    intro: 'A real GothamChess win vs ZackyyD. The gambit pawn buys time; the queen seizes the centre and burrows into Black’s camp.',
    overview: 'A real GothamChess win (vs ZackyyD): for the gambit pawn White plants the queen on d5 and then d6, dominating the centre and cramping Black while development flows.',
    pieceManeuvers: [{ piece: 'Queen', route: 'Qd5-d6 domination', explanation: 'The queen seizes d5 and burrows into d6, cramping Black’s position.' }],
    pawnBreaks: [{ move: 'e4 central anchor', explanation: 'The e-pawn anchors the centre so the queen can dominate.', fen: '' }],
    strategicThemes: ['Use the lead in development the gambit buys.', 'Dominate the central squares with the queen.'],
    endgameTransitions: ['The activity is worth more than the pawn well into the late middlegame.'],
    greenArrowIdx: [2, 6],
    annotations: [
      'h3 — a quiet move, denying g4 and making luft.',
      '…Ne5 — the knight centralises.',
      'Qd5 — the queen seizes the centre, eyeing f7 and the knight.',
      '…Re8 — defending and developing the rook.',
      'Be3 — completing development.',
      '…c6 — challenging the centralised queen.',
      'Qd6 — the queen burrows into d6, cramping Black.',
      '…Nc4 — Black hits back, but the lead in development is worth the pawn.',
    ],
    cues: ['h3 — luft, deny g4', 'Ne5 — centralise', 'Qd5 — seize the centre', 'Re8 — defend', 'Be3 — develop', 'c6 — challenge the queen', 'Qd6 — burrow in, cramp', 'Nc4 — White has full value'],
  },
  // ---- Anti-Sicilian ----
  'mp-progothamchess-antisic-g6-d4break': {
    title: 'Anti-Sicilian: Trade Down to a Better Game',
    intro: 'A real GothamChess win. White trades the heavy pieces in the centre and steers into a pleasant, simpler position.',
    overview: 'A real GothamChess win: the pieces come off on d4, queens included, and White emerges with the more comfortable position and the easier pieces to play.',
    pieceManeuvers: [{ piece: 'Rook', route: 'Ra1-c1 c-file', explanation: 'The rook swings to c1 to work the c-file in the simplified position.' }],
    pawnBreaks: [{ move: 'd4 central break', explanation: 'The d4 break invites the mass trade that simplifies into White’s edge.', fen: '' }],
    strategicThemes: ['Simplify into a comfortable middlegame.', 'Use the c-file once the heavy trades are done.'],
    endgameTransitions: ['The simpler position carries a small but real edge into the endgame.'],
    greenArrowIdx: [4],
    annotations: [
      'Nxd4 — recapturing and inviting the trades in the centre.',
      '…Qxd4 — Black takes the knight.',
      'Qxd4 — offering the queen trade.',
      '…Bxd4 — recapturing; the queens are off the board.',
      'Rac1 — activating the rook toward the c-file.',
      '…Bf5 — developing the bishop.',
      'Nc3 — developing, gripping the centre.',
      '…e5 — Black claims space, but White’s position is the easier to handle.',
    ],
    cues: ['Nxd4 — invite trades', 'Qxd4 — Black takes', 'Qxd4 — offer the swap', 'Bxd4 — queens off', 'Rac1 — work the c-file', 'Bf5 — develop', 'Nc3 — grip the centre', 'e5 — White is comfier'],
  },
  // ---- Stafford refute ----
  'mp-progothamchess-stafford-consolidate': {
    title: 'Stafford Gambit: Consolidate the Extra Piece',
    intro: 'A real GothamChess win. White refuses the complications, tucks the king safely, and the extra material decides.',
    overview: 'A real GothamChess win: against the Stafford’s tricks White just develops, routes the knight to a fine square, tucks the king to g2 and consolidates the extra piece.',
    pieceManeuvers: [{ piece: 'Knight', route: 'Na3-c4-e5 reroute', explanation: 'The knight reroutes via c4 to the dominant e5 square as White consolidates.' }],
    pawnBreaks: [{ move: 'e4-e5 anchor', explanation: 'The e5-pawn anchors the centre while White untangles.', fen: '' }],
    strategicThemes: ['Develop and tuck the king before cashing in.', 'Keep the extra piece; refuse needless complications.'],
    endgameTransitions: ['A piece up, any trade brings the win closer.'],
    greenArrowIdx: [0, 2],
    annotations: [
      'Na3 — developing the knight, heading for c4.',
      '…O-O-O — Black castles long, hunting activity for the pawn.',
      'Nc4 — the knight reaches the fine c4 square.',
      '…f6 — Black strikes at the centre.',
      'Kg2 — calmly tucking the king and connecting the rooks.',
      '…fxe5 — opening the f-file.',
      'Nxe5 — recapturing; the knight dominates e5.',
      '…c5 — Black seeks counterplay, but White is a piece up and consolidated.',
    ],
    cues: ['Na3 — head for c4', 'O-O-O — Black seeks play', 'Nc4 — fine square', 'f6 — strike the centre', 'Kg2 — tuck the king', 'fxe5 — open the f-file', 'Nxe5 — dominate e5', 'c5 — White is winning'],
  },
  // ---- KIA ----
  'mp-progothamchess-kia-system-attack': {
    title: 'King’s Indian Attack: Simplify and Press',
    intro: 'A real GothamChess win. The KIA setup invites central trades; White comes out with the more pleasant pieces.',
    overview: 'A real GothamChess win: the central tension resolves into a mass trade, queens included, and White is left pressing a small, comfortable edge with the more active pieces.',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bc1-f4 develop', explanation: 'The bishop swings to f4 with tempo as the position simplifies.' }],
    pawnBreaks: [{ move: 'd4 central break', explanation: 'The d4 break resolves the centre into White’s favour.', fen: '' }],
    strategicThemes: ['Let the centre trade off into a comfortable game.', 'Activate the bishops in the simplified position.'],
    endgameTransitions: ['The pleasanter pieces carry a nagging edge into the endgame.'],
    greenArrowIdx: [6],
    annotations: [
      'Nxe4 — snapping off the centre pawn.',
      '…exd4 — Black strikes back in the centre.',
      'exd4 — recapturing to keep the centre.',
      '…Qxd4 — grabbing the pawn.',
      'Qxd4 — offering the queen trade.',
      '…Bxd4 — the queens come off.',
      'Bf4 — developing the bishop with tempo.',
      '…Bxg4 — Black grabs a pawn, but White’s pieces are the more active.',
    ],
    cues: ['Nxe4 — take the pawn', 'exd4 — strike back', 'exd4 — recapture', 'Qxd4 — grab it', 'Qxd4 — offer the swap', 'Bxd4 — queens off', 'Bf4 — develop with tempo', 'Bxg4 — White presses'],
  },
  // ---- Milner-Barry ----
  'mp-progothamchess-french-rubinstein': {
    title: 'Milner-Barry: Queenside Expansion for the Pawn',
    intro: 'A real GothamChess win vs spajsije. White centralises the rooks and rolls the queenside pawns as gambit compensation.',
    overview: 'A real GothamChess win (vs spajsije): the bishops and rooks come to their best squares and then b4 expands on the queenside, the long-term compensation for the Milner-Barry pawn.',
    pieceManeuvers: [{ piece: 'Rook', route: 'Ra1-d1 central file', explanation: 'The rook takes the central d-file as White builds before expanding.' }],
    pawnBreaks: [{ move: 'b4 queenside expansion', explanation: 'b4 gains queenside space, the lasting compensation for the gambit pawn.', fen: '' }],
    strategicThemes: ['Develop fully, then expand with b4 on the queenside.', 'Trust the activity as compensation for the pawn.'],
    endgameTransitions: ['The space and activity offset the pawn deep into the game.'],
    greenArrowIdx: [2, 6],
    annotations: [
      'Be3 — developing the bishop, eyeing the queenside.',
      '…Qd7 — Black connects his pieces.',
      'Rad1 — the rook takes the central d-file.',
      '…Bd6 — developing toward the kingside.',
      'Bg2 — repositioning the bishop onto the long diagonal.',
      '…Kb8 — tucking the king away.',
      'b4 — gaining queenside space; the gambit compensation rolls.',
      '…Ne7 — developing, but White’s pressure is full value for the pawn.',
    ],
    cues: ['Be3 — develop, eye queenside', 'Qd7 — connect', 'Rad1 — take the d-file', 'Bd6 — develop', 'Bg2 — long diagonal', 'Kb8 — tuck the king', 'b4 — expand queenside', 'Ne7 — full compensation'],
  },
  'mp-progothamchess-mb-main-fstorm': {
    title: 'Milner-Barry: the f4-f5 Pawn Storm',
    intro: 'A real GothamChess win. The f-pawn storms forward, the signature Milner-Barry kingside plan.',
    overview: 'A real GothamChess win: f4 launches the kingside storm, and when Black counters with …g5 White recaptures and the dark-squared bishop joins the attack on the king.',
    pieceManeuvers: [{ piece: 'Bishop', route: 'Bc1-d2-f4 support', explanation: 'The bishop reroutes via d2 to recapture on f4 and support the storm.' }],
    pawnBreaks: [{ move: 'f4-f5 storm', explanation: 'The f-pawn storms to f4 and on toward f5 to crack the kingside.', fen: '' }],
    strategicThemes: ['Storm the kingside with the f-pawn.', 'Reroute the bishop to support the advance.'],
    endgameTransitions: ['The attack aims to decide before any endgame.'],
    greenArrowIdx: [0],
    annotations: [
      'f4 — the f-pawn storms forward, the Milner-Barry attacking plan.',
      '…Bc5 — developing with tempo.',
      'a3 — a useful restraining move on the queenside.',
      '…g5 — Black counters on the kingside.',
      'Bd2 — rerouting the bishop to support f4.',
      '…gxf4 — opening the g-file.',
      'Bxf4 — recapturing; the bishop now eyes the kingside.',
      '…O-O-O — Black castles long, but White’s storm is rolling.',
    ],
    cues: ['f4 — storm forward', 'Bc5 — develop', 'a3 — restrain', 'g5 — Black counters', 'Bd2 — support f4', 'gxf4 — open the g-file', 'Bxf4 — bishop eyes the king', 'O-O-O — storm rolls on'],
  },
};

const r = apply(narr);
console.log('white-small:', JSON.stringify(r));
