import { useEffect, useState } from 'react';
import type { LessonBeat } from '../types';
import { useAppStore } from '../stores/appStore';

/**
 * Lesson-narration localization (pilot).
 *
 * The hand-authored English narration (LessonBeat.say / sayShort) is the
 * board-verified source of truth. Per-language translations live in lazy JSON
 * packs at src/data/lessons/i18n/<openingId>.<lang>.json (generated by
 * scripts/i18n/translate-lesson.ts, chess-tokens preserved + verified). We swap
 * the beat prose at playback time by the user's `narrationLanguage` preference,
 * falling back to English for any beat/opening/language without a pack. The
 * spoken VOICE follows automatically — the /api/tts layer detects the text's
 * language and picks a native Polly voice.
 */
interface PackEntry { say: string; sayShort?: string }
type PackBeats = Record<string, PackEntry>;

// Vite auto-discovers every pack under i18n/ — adding a new
// <openingId>.<lang>.json file makes it available with zero wiring.
const PACK_LOADERS = import.meta.glob<{ beats: PackBeats }>('../data/lessons/i18n/*.json');

const cache = new Map<string, PackBeats | null>();

/** Load (and cache) the narration pack for an opening + language, or null if
 *  none exists (→ caller keeps English). */
export async function loadNarrationPack(openingId: string, lang: string): Promise<PackBeats | null> {
  const key = `${openingId}.${lang}`;
  if (cache.has(key)) return cache.get(key) ?? null;
  const loader = PACK_LOADERS[`../data/lessons/i18n/${openingId}.${lang}.json`];
  if (!loader) { cache.set(key, null); return null; }
  try {
    const mod = await loader();
    const beats = (mod as { beats?: PackBeats }).beats ?? null;
    cache.set(key, beats);
    return beats;
  } catch {
    cache.set(key, null);
    return null;
  }
}

/** Return beats with localized say/sayShort where the pack has a translation;
 *  every un-translated beat keeps its English prose. Pure. */
export function localizeBeats(beats: LessonBeat[], pack: PackBeats | null): LessonBeat[] {
  if (!pack) return beats;
  return beats.map((b) => {
    const t = pack[b.id];
    if (!t || !t.say) return b;
    return { ...b, say: t.say, sayShort: t.sayShort ?? b.sayShort };
  });
}

/**
 * Hook: localized copy of `beats` for the active profile's narration language.
 * Returns English immediately (and while the pack loads), then swaps to the
 * localized beats once the lazy pack resolves. English preference = no-op.
 */
export function useLocalizedBeats(openingId: string, beats: LessonBeat[]): LessonBeat[] {
  const lang = useAppStore((s) => s.activeProfile?.preferences?.narrationLanguage) ?? 'en';
  const [localized, setLocalized] = useState<LessonBeat[]>(beats);

  useEffect(() => {
    if (!lang || lang === 'en') { setLocalized(beats); return; }
    let cancelled = false;
    void loadNarrationPack(openingId, lang).then((pack) => {
      if (!cancelled) setLocalized(localizeBeats(beats, pack));
    });
    return () => { cancelled = true; };
  }, [openingId, lang, beats]);

  return localized;
}
