#!/bin/bash
# NEXT ROUND — 30 Naroditsky videos, picked by which TAUGHT opening still has no
# track. Generated by: node scripts/video-align/next-round.mjs --count 30 --write
#
# Run this on YOUR machine, David. One at a time with jittered gaps — four at a
# time got the IP bot-checked after ~40 videos last time, and the cookies were
# never the problem, the request RATE was.
#
#   1. export fresh YouTube cookies to /tmp/yt-cookies.txt (do NOT sign out of
#      that browser window afterwards — signing out rotates them dead)
#   2. bash next-round-dl.sh
#
# Subtitles first (tiny, ~500KB each, and they expire with the same cookies).
# Video is 480p-capped video-only DASH: ~40-60MB each, ~1.5GB for all 30.
set -u
OUT=${OUT:-$HOME/chess-videos}
COOKIES=${COOKIES:-/tmp/yt-cookies.txt}
GAP=${GAP:-45}
mkdir -p "$OUT/subs" "$OUT/video"

IDS="Nd2NeAbF3k8 iLiE-uWRfBc kYbh2NTFsS8 iZyf2oBcR9Q l65FZlRkWcM WmCImz1fv5s CXvo1dMF1Qs uJCgrG90u8A
0npOMfkAlVU mCB8n7v0MEA MWMloBpKuVg EN72rn5tVYI TNaKFN65B5o Ybg_2qbKXdA _j8aiuqS4_0 IMBSR0A9nJs
D7sbbap9lIc WQFcuBCL1F4 l6IwRWbovRU 1671V8LrEwk Twv9FExvwSw vMY6Wr3niUg bRMHNmDMLqw Gk7MNomOOSA
Zko_JUK06vM 1rcEbI44WqE qhHtJcXkkfg k7R9Omne_1Y QxHsw4ZS2Ts fhDxUI-t2v4"

for id in $IDS; do
  [ -s "$OUT/video/$id.mp4" ] && { echo "SKIP $id"; continue; }
  yt-dlp --cookies "$COOKIES" --remote-components ejs:npm \
    --write-auto-sub --skip-download --sub-format vtt --sub-langs en \
    -o "$OUT/subs/%(id)s.%(ext)s" "https://www.youtube.com/watch?v=$id" >/dev/null 2>&1
  # 135 is 480p and is missing on some uploads; the chain falls back rather than
  # dropping the video. Video-only DASH sidesteps the SABR wall that 403s every
  # progressive format.
  if yt-dlp --cookies "$COOKIES" --remote-components ejs:npm \
       -f "135/396/bestvideo[height<=480]/bestvideo" \
       -o "$OUT/video/%(id)s.%(ext)s" "https://www.youtube.com/watch?v=$id" \
       > "$OUT/video/$id.log" 2>&1; then
    echo "OK   $id"
  else
    echo "FAIL $id :: $(grep -oiE 'ERROR.*' "$OUT/video/$id.log" | head -1 | cut -c1-70)"
    grep -qE 'HTTP Error (429|403)' "$OUT/video/$id.log" && { echo "  rate-limited — sleeping 300s"; sleep 300; }
  fi
  sleep $((GAP + RANDOM % 30))
done
echo "=== done — videos in $OUT/video, subtitles in $OUT/subs ==="
