#!/bin/sh

# Xcode Cloud post-clone hook.
#
# LOCATION MATTERS: this MUST live at ios/App/ci_scripts/ — adjacent to
# App.xcodeproj — because Xcode Cloud looks for the ci_scripts folder in the
# same directory as the Xcode project, NOT at the repository root. A repo-root
# ci_scripts/ is silently ignored when the project sits in a subdirectory, so
# the hook never runs and the Archive step fails with "Project App.xcodeproj
# does not exist at ios/App/App.xcodeproj".
#
# The Capacitor ios/ tree is gitignored and regenerated by `cap`, so we
# generate it (web bundle + native project) here before Xcode Cloud archives.
# Only this ci_scripts/ folder is committed under ios/; everything else is
# produced below.
#
# The entire body is wrapped in a `{ ... }` group on purpose: the shell reads
# the whole compound command off disk BEFORE executing any of it, so the
# `rm -rf ios` that deletes this very file can't truncate the running script.
{
set -e

# Repo root (Xcode Cloud exports this).
cd "$CI_PRIMARY_REPOSITORY_PATH"

# Node isn't preinstalled on the Xcode Cloud image — install via Homebrew.
brew install node
node -v
npm -v

# Drop the sparse committed ios/ (this ci_scripts folder is the only tracked
# part) so `cap add ios` starts clean instead of erroring "already exists".
rm -rf ios

# Web bundle + native iOS project (mirrors `npm run setup:ios`).
npm ci
npm run build

# OTA (David 2026-07-03): stamp the SHIPPED bundle's version = short git SHA so
# it matches the OTA bundle published for this same commit
# (scripts/ci/publish-ota-bundle.mjs) — a fresh install won't redundantly
# re-download the bundle it already ships with. Read by capacitor.config.ts
# CapacitorUpdater.version, baked into the native project by `cap sync`.
# --short=8, NOT bare --short: core.abbrev defaults to auto, so git lengthens
# the SHA when 7 chars are ambiguous. Xcode Cloud and the deploy runner have
# different object databases, so the same commit was being stamped 7 chars here
# and 8 there — the device then saw a permanent phantom update. Both sides must
# pin the SAME length or the comparison is meaningless.
export OTA_BUNDLE_VERSION="$(git -C "$CI_PRIMARY_REPOSITORY_PATH" rev-parse --short=8 HEAD)"
echo "OTA_BUNDLE_VERSION=$OTA_BUNDLE_VERSION"

# VERIFY THE STAMP. capacitor.config.ts reads `process.env.OTA_BUNDLE_VERSION ||
# undefined`, so an empty value silently falls through and Capgo labels the
# builtin bundle with the NATIVE app version instead. A real device in the
# 2026-09-03 telemetry reports `builtin: "1.0"` from exactly that: it can never
# match a published SHA, so it is offered an update forever and re-downloads the
# whole bundle on every launch. Silent misconfiguration is what this build has
# been bitten by repeatedly (the mic usage strings, the app icon) — make it red.
if [ -z "$OTA_BUNDLE_VERSION" ]; then
  echo "ci_post_clone: FATAL — OTA_BUNDLE_VERSION is empty."
  echo "  The shipped bundle would be stamped with the native app version, and the"
  echo "  device would re-download the full OTA bundle on every single launch."
  exit 1
fi
case "$OTA_BUNDLE_VERSION" in
  [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]) ;;
  *)
    echo "ci_post_clone: FATAL — OTA_BUNDLE_VERSION='$OTA_BUNDLE_VERSION' is not an 8-char short SHA."
    echo "  The publisher pins --short=8; both sides must agree or the device sees a"
    echo "  permanent phantom update for the commit it is already running."
    exit 1
    ;;
esac

npx cap add ios
npx cap sync ios

# Regenerate the REAL app icon + splash from the committed sources in assets/.
# `cap add` scaffolds the DEFAULT Capacitor icon, so without this every build
# ships the placeholder icon (David's report 2026-06-13). The project's own
# asset pipeline builds the icon set into ios/App/App/Assets.xcassets.
npm run assets:generate

# Guard: FAIL the build if the brand icon wasn't actually applied. capacitor-
# assets can silently no-op for iOS (e.g. if it can't find the appiconset) and
# leave the white Capacitor placeholder — exactly what shipped in 2.8 (David
# 2026-06-14). This turns a wrong-icon ship into a red build.
node scripts/verify-app-icon.mjs

# Reapply the AVAudioSession AppDelegate patch (cap regenerates ios/).
cp ios-patches/App/AppDelegate.swift ios/App/App/AppDelegate.swift

# Pin the marketing version; Xcode Cloud auto-increments the build number
# (CFBundleVersion) to the build-run number every build on its own. Keeping ONE
# marketing version means each new build is the SAME version with a higher build
# number, so once this version clears Beta App Review the external testers get
# every subsequent build with NO re-review (David 2026-06-13). Bump this when you
# cut a real release; `cap add` scaffolds 1.0, which we must overwrite so it never
# regresses below the shipped 2.x line.
# NB (2026-06-22): builds #70/#71 were briefly rejected ("bundle version must be
# higher than previously uploaded") because the auto-increment counter had fallen
# behind the already-uploaded 2.8 build 72; it self-resolves once the run counter
# passes 72 (next build = 73 > 72). Do NOT try to override the build number here
# (epoch/agvtool tricks just fought the auto-increment and lost) — let Xcode Cloud
# own it.
# BUMP 2.8 → 3.0 (David 2026-07-08): 2.8 is RELEASED on the App Store, so Apple
# rejects any new build uploaded under that version ("must be a higher version").
# BUMP 3.0 → 3.1 (2026-07-11): 3.0 hit READY_FOR_SALE overnight (the nightly
# auto-submit released it), so Xcode Cloud runs #121/#122 died at
# PrepareBuildForAppStoreConnect — same released-version rejection as the 2.8
# incident. 3.1 carries the mic usage-string fix + half-duplex voice builds.
# (Nightly auto-submit is now disabled, so 3.1 won't self-release like 3.0 did.)
# BUMP 3.1 → 3.2 (David 2026-07-15): 3.1 is APPROVED on the App Store, so Apple
# rejects any new build uploaded under 3.1 ("must be a higher version"). 3.2
# carries the new openings + counter-repertoire recommender + freemium free-tier
# (start free, no card; 7-DAY FREE TRIAL for Pro).
# BUMP 3.2 → 3.3 (2026-07-22): Xcode Cloud runs #149-151 all died at
# "Preparing build for App Store Connect" with a clean archive — the exact
# released-version rejection signature from the 3.0 and 3.1 incidents (3.2 has
# since cleared the store). 3.3 carries the Danya-standard review rebuild:
# threats both directions (2-4 moves, verified), every-move teaching beats
# ([does]/[delta]/[eval]), the composed-advice doctrine (board-object-composed
# plans — no inventory/phase-blind advice), Pattern Recognition school, and the
# unified review chat.
# BUMP 3.3 → 3.4 (2026-07-31): 3.3 is READY_FOR_SALE on the App Store, so Apple
# rejects any new build uploaded under it — the same released-version signature
# as 2.8, 3.0, 3.1 and 3.2. Caught before the build this time: create-asc-version
# reported 3.3 already existed in state READY_FOR_SALE, so the in-flight 3.3
# build was cancelled rather than left to die at PrepareBuildForAppStoreConnect.
# 3.4 carries the coach-tab teaching rebuild: one continuous narrated lesson per
# opening, deterministic lead-the-eye arrows on every mentioned square, teaching
# memory across visits, resume-in-place at forks, back/forward navigation, a
# narrated middlegame play-out with an endgame step, and the Tier-2 baked
# narrations across every gap opening.
# BUMP 3.4 → 3.5 (2026-08-02): Apple rejected build 166 under 3.4 with the same
# released-version signature as 2.8, 3.0, 3.1, 3.2 and 3.3 (ITMS-90186 "the train
# version 3.4 is closed for new build submissions" + ITMS-90062 "must contain a
# higher version than the previously approved version 3.4"). 3.5 carries the
# lesson-scope fixes (a lesson can no longer be narrated with another opening's
# teaching), the stale-narration fix (beats repeating, the board resetting to
# move one under the play-out), traps wired to the curated gem lines, the coach
# speaking the student's language on every surface, the rating-matched opponent
# on iOS, and the training ledger that feeds the weakness profile again.
# BUMP 3.5 → 3.6 (2026-08-15): 3.5 has been RELEASED on the App Store since
# 2026-08-03 (iTunes lookup confirms it live), so Xcode Cloud run #171 died at
# "Preparing build for App Store Connect" — the SEVENTH released-version
# rejection (2.8, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5 all hit it). The Splash
# "3 unassigned children" line in that log is only a warning, not the cause.
# 3.6 carries the corpus expansion (Naroditsky farm 8,162 → 11,426 notes, the
# spoken-form bake at 91.8%), the position-verification G0 narrowing (a note
# may only claim a position the anchor pass verified), layered per-ply
# narration, the endgame surface wired into the farmed corpus, the coach Q&A
# lane fixes (opening-existence lookup, named-opening traps offer, five
# unreachable lanes threaded), and the tactics drill framing beats.
# BUMP 3.6 → 3.7 (David 2026-08-22): 3.6 is RELEASED on the App Store and shipped
# with VITE_PAYWALL_ENABLED baked TRUE, so it walled every user on launch — "no
# one is using the app." 3.7 branches from the exact 3.6 App Store source line
# and forces the paywall gate dormant in CODE (isPaywallGateEnabled → false), so
# the entire app is free regardless of the build env flag. It also strips the
# first-run pop-ups that greeted a fresh download (strength-picker bubble,
# page-help auto-open, "coach is free" toast) — the Apple-required AI-consent
# modal (5.1.1) stays. Branched from the 3.6 App Store line — deliberately NOT
# current main.
# BUMP 3.7 → 3.8 (David 2026-08-24): 3.7 is READY_FOR_SALE on the App Store, so
# Apple rejects new builds under it. 3.8 is the next release train — the URGENT
# crash hotfix that stops the eager "video-dump" teaching-corpus loads from
# OOM-crashing the app at boot (desktop tabs + iOS WKWebView Jetsam). Built from
# current main.
# BUMP 4.0.1 → 4.0.2 (David 2026-09-05): Apple closed the 4.0.1 train between
# build 187 (19:56, archived fine) and build 188 (20:32) — 4.0.1 was approved in
# that window, and an approved version stops accepting builds. Runs #188 and
# #189 were dead on arrival; the emailed rejection names it exactly:
#   ITMS-90186 "the train version '4.0.1' is closed for new build submissions"
#   ITMS-90062 "must contain a higher version than the previously approved 4.0.1"
# That is the NINTH time this line has gone stale the same way (2.8, 3.0, 3.1,
# 3.2, 3.3, 3.4, 3.5, 3.6/3.7, now 4.0.1). Nine identical incidents is not a
# stale constant, it is a missing preflight: the version is a hardcoded string
# that Apple can invalidate at any moment WITHOUT the repo changing, and the
# failure only surfaces ~9 minutes into an archive. The durable fix is to ask
# App Store Connect for the open train BEFORE triggering Xcode Cloud (the ASC
# credentials are already in the workflow, and scripts/ci/create-asc-version.mjs
# already knows how to query versions) — bumping this string again is the ninth
# symptom fix, not a cure. 4.0.2 carries the analysis split: sweep as a shallow
# draft, deep dive moved into the review, 4-worker phone pool, per-FEN eval
# cache, recent games on Weaknesses.
IOS_MARKETING_VERSION="4.0.2"
sed -i '' -e "s/MARKETING_VERSION = [^;]*;/MARKETING_VERSION = ${IOS_MARKETING_VERSION};/g" \
  ios/App/App.xcodeproj/project.pbxproj
echo "ci_post_clone: MARKETING_VERSION set to ${IOS_MARKETING_VERSION} (build ${CI_BUILD_NUMBER:-?})"

# Declare export compliance (standard HTTPS/TLS only = exempt encryption) so
# TestFlight never shows "Missing Compliance" and the build is installable for
# internal testers immediately, with no per-build encryption question. Guarded
# so a plist hiccup never aborts the archive.
PLIST="ios/App/App/Info.plist"
/usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" "$PLIST" 2>/dev/null \
  || /usr/libexec/PlistBuddy -c "Set :ITSAppUsesNonExemptEncryption false" "$PLIST" 2>/dev/null \
  || true

# Mic + speech-recognition usage strings — REQUIRED or the app crashes the
# instant @capacitor-community/speech-recognition requests permission (voice-to-
# coach in the native app — David 2026-06-18 "mic doesn't work in the iOS app").
# `cap add` regenerates Info.plist every build, so inject here (not in a
# committed plist). Add-then-Set so it's idempotent across re-runs.
#
# 🔒 ROOT CAUSE of the build-118 mic CRASH (David 2026-07-11, confirmed from the
# .ips): the crash was EXC_BREAKPOINT (brk 1) inside the plugin's
# `AVAudioSession.requestRecordPermission` completion — iOS's documented trap
# when a privacy API is called WITHOUT its Info.plist usage string. The old
# injection ended every line with `|| true`, so a wrong plist path or a
# PlistBuddy hiccup SILENTLY shipped a build with no usage string → guaranteed
# crash on the first mic tap. Never silent again: locate the real plist, inject,
# then VERIFY both keys are present and HARD-FAIL the build if either is missing.
MIC_MSG="Chess Academy uses the microphone so you can talk to your coach by voice."
SPEECH_MSG="Chess Academy uses speech recognition to turn what you say into messages for your coach."

# The plist path can drift with Capacitor versions; if the expected one is
# missing, find the real App Info.plist rather than inject into the void.
if [ ! -f "$PLIST" ]; then
  ALT_PLIST="$(find ios -name "Info.plist" -path "*App/App*" 2>/dev/null | head -1)"
  echo "ci_post_clone: expected $PLIST missing; discovered '$ALT_PLIST'"
  [ -n "$ALT_PLIST" ] && PLIST="$ALT_PLIST"
fi

/usr/libexec/PlistBuddy -c "Add :NSMicrophoneUsageDescription string \"$MIC_MSG\"" "$PLIST" 2>/dev/null \
  || /usr/libexec/PlistBuddy -c "Set :NSMicrophoneUsageDescription \"$MIC_MSG\"" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :NSSpeechRecognitionUsageDescription string \"$SPEECH_MSG\"" "$PLIST" 2>/dev/null \
  || /usr/libexec/PlistBuddy -c "Set :NSSpeechRecognitionUsageDescription \"$SPEECH_MSG\"" "$PLIST" 2>/dev/null || true

# VERIFY — read the keys back. If either is absent the app WILL crash on mic use,
# so make it a RED BUILD instead of a shipped crash.
MIC_CHECK="$(/usr/libexec/PlistBuddy -c "Print :NSMicrophoneUsageDescription" "$PLIST" 2>/dev/null || echo "")"
SPEECH_CHECK="$(/usr/libexec/PlistBuddy -c "Print :NSSpeechRecognitionUsageDescription" "$PLIST" 2>/dev/null || echo "")"
if [ -z "$MIC_CHECK" ] || [ -z "$SPEECH_CHECK" ]; then
  echo "ci_post_clone: FATAL — mic/speech usage strings NOT present in $PLIST"
  echo "  NSMicrophoneUsageDescription='$MIC_CHECK'"
  echo "  NSSpeechRecognitionUsageDescription='$SPEECH_CHECK'"
  echo "  The app would EXC_BREAKPOINT on the first mic tap (build-118 crash). Aborting."
  ls -la "$(dirname "$PLIST")" || true
  exit 1
fi
echo "ci_post_clone: verified mic + speech usage strings present in $PLIST"

# --- Swift Package resolution -------------------------------------------------
# Xcode Cloud archives with "only use versions from Package.resolved" forced ON
# globally (IDEPackageOnlyUseVersionsFromResolvedFile), so the Archive step
# REFUSES to resolve fresh and demands a resolved file at
#   App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
# Because the project is generated here, none is committed — so we must produce
# it now. (This global setting is why an explicit
# `xcodebuild -resolvePackageDependencies` alone failed with exit 74 — see
# swift-package-manager#6914.)
RESOLVED="ios/App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"

# Flip the global default OFF for this build user so xcodebuild can resolve,
# then resolve — this writes Package.resolved with the originHash xcodebuild
# expects for the .xcodeproj dependency graph.
defaults write com.apple.dt.Xcode IDEPackageOnlyUseVersionsFromResolvedFile -bool NO || true
xcodebuild -resolvePackageDependencies -project ios/App/App.xcodeproj -scheme App || true

# Fallback: if the above didn't produce the file (e.g. the default is enforced
# another way), resolve with the SwiftPM CLI — it ignores the com.apple.dt.Xcode
# default entirely — and place the result where the Archive step looks.
if [ ! -f "$RESOLVED" ]; then
  ( cd ios/App/CapApp-SPM && xcrun swift package resolve )
  mkdir -p "$(dirname "$RESOLVED")"
  cp ios/App/CapApp-SPM/Package.resolved "$RESOLVED"
fi

test -f "$RESOLVED" || { echo "ci_post_clone: FAILED to produce Package.resolved"; exit 1; }

echo "ci_post_clone: generated ios/App/App.xcodeproj + resolved SPM dependencies"
}
