#!/bin/sh

# Xcode Cloud post-clone hook.
#
# LOCATION MATTERS: this MUST live at ios/App/ci_scripts/ — adjacent to
# App.xcodeproj — because Xcode Cloud looks for the ci_scripts folder in the
# same directory as the Xcode project, NOT at the repository root. A repo-root
# ci_scripts/ is silently ignored when the project sits in a subdirectory, so
# the hook never runs and the Archive step fails with "Project App.xcodeproj
# does not exist at ios/App/App.xcodeproj".
#
# The Capacitor ios/ tree is gitignored and regenerated by `cap`, so we
# generate it (web bundle + native project) here before Xcode Cloud archives.
# Only this ci_scripts/ folder is committed under ios/; everything else is
# produced below.
#
# The entire body is wrapped in a `{ ... }` group on purpose: the shell reads
# the whole compound command off disk BEFORE executing any of it, so the
# `rm -rf ios` that deletes this very file can't truncate the running script.
{
set -e

# Repo root (Xcode Cloud exports this).
cd "$CI_PRIMARY_REPOSITORY_PATH"

# Node isn't preinstalled on the Xcode Cloud image — install via Homebrew.
brew install node
node -v
npm -v

# Drop the sparse committed ios/ (this ci_scripts folder is the only tracked
# part) so `cap add ios` starts clean instead of erroring "already exists".
rm -rf ios

# Web bundle + native iOS project (mirrors `npm run setup:ios`).
npm ci
npm run build
npx cap add ios
npx cap sync ios

# Reapply the AVAudioSession AppDelegate patch (cap regenerates ios/).
cp ios-patches/App/AppDelegate.swift ios/App/App/AppDelegate.swift

echo "ci_post_clone: generated ios/App/App.xcodeproj"
}
