#!/bin/sh

# Xcode Cloud post-clone hook.
#
# LOCATION MATTERS: this MUST live at ios/App/ci_scripts/ — adjacent to
# App.xcodeproj — because Xcode Cloud looks for the ci_scripts folder in the
# same directory as the Xcode project, NOT at the repository root. A repo-root
# ci_scripts/ is silently ignored when the project sits in a subdirectory, so
# the hook never runs and the Archive step fails with "Project App.xcodeproj
# does not exist at ios/App/App.xcodeproj".
#
# The Capacitor ios/ tree is gitignored and regenerated by `cap`, so we
# generate it (web bundle + native project) here before Xcode Cloud archives.
# Only this ci_scripts/ folder is committed under ios/; everything else is
# produced below.
#
# The entire body is wrapped in a `{ ... }` group on purpose: the shell reads
# the whole compound command off disk BEFORE executing any of it, so the
# `rm -rf ios` that deletes this very file can't truncate the running script.
{
set -e

# Repo root (Xcode Cloud exports this).
cd "$CI_PRIMARY_REPOSITORY_PATH"

# Node isn't preinstalled on the Xcode Cloud image — install via Homebrew.
brew install node
node -v
npm -v

# Drop the sparse committed ios/ (this ci_scripts folder is the only tracked
# part) so `cap add ios` starts clean instead of erroring "already exists".
rm -rf ios

# Web bundle + native iOS project (mirrors `npm run setup:ios`).
npm ci
npm run build
npx cap add ios
npx cap sync ios

# Regenerate the REAL app icon + splash from the committed sources in assets/.
# `cap add` scaffolds the DEFAULT Capacitor icon, so without this every build
# ships the placeholder icon (David's report 2026-06-13). The project's own
# asset pipeline builds the icon set into ios/App/App/Assets.xcassets.
npm run assets:generate

# Reapply the AVAudioSession AppDelegate patch (cap regenerates ios/).
cp ios-patches/App/AppDelegate.swift ios/App/App/AppDelegate.swift

# Auto-bump the marketing version every build (David 2026-06-13). `cap add`
# scaffolds at 1.0, which would REGRESS below the shipped 2.x line. Xcode Cloud
# stamps a monotonically increasing build number (CI_BUILD_NUMBER) and uses it
# for CFBundleVersion, so we derive the marketing minor from it:
# minor = CI_BUILD_NUMBER - 39  ->  build 43 = 2.4, 44 = 2.5, 45 = 2.6 ...
# a +0.1 bump every build, monotonic and stateless. Falls back to 2.4 when run
# outside Xcode Cloud (CI_BUILD_NUMBER unset).
IOS_MARKETING_VERSION="2.$(( ${CI_BUILD_NUMBER:-43} - 39 ))"
sed -i '' -e "s/MARKETING_VERSION = [^;]*;/MARKETING_VERSION = ${IOS_MARKETING_VERSION};/g" \
  ios/App/App.xcodeproj/project.pbxproj
echo "ci_post_clone: MARKETING_VERSION set to ${IOS_MARKETING_VERSION} (build ${CI_BUILD_NUMBER:-?})"

# Declare export compliance (standard HTTPS/TLS only = exempt encryption) so
# TestFlight never shows "Missing Compliance" and the build is installable for
# internal testers immediately, with no per-build encryption question. Guarded
# so a plist hiccup never aborts the archive.
PLIST="ios/App/App/Info.plist"
/usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" "$PLIST" 2>/dev/null \
  || /usr/libexec/PlistBuddy -c "Set :ITSAppUsesNonExemptEncryption false" "$PLIST" 2>/dev/null \
  || true

# --- Swift Package resolution -------------------------------------------------
# Xcode Cloud archives with "only use versions from Package.resolved" forced ON
# globally (IDEPackageOnlyUseVersionsFromResolvedFile), so the Archive step
# REFUSES to resolve fresh and demands a resolved file at
#   App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
# Because the project is generated here, none is committed — so we must produce
# it now. (This global setting is why an explicit
# `xcodebuild -resolvePackageDependencies` alone failed with exit 74 — see
# swift-package-manager#6914.)
RESOLVED="ios/App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"

# Flip the global default OFF for this build user so xcodebuild can resolve,
# then resolve — this writes Package.resolved with the originHash xcodebuild
# expects for the .xcodeproj dependency graph.
defaults write com.apple.dt.Xcode IDEPackageOnlyUseVersionsFromResolvedFile -bool NO || true
xcodebuild -resolvePackageDependencies -project ios/App/App.xcodeproj -scheme App || true

# Fallback: if the above didn't produce the file (e.g. the default is enforced
# another way), resolve with the SwiftPM CLI — it ignores the com.apple.dt.Xcode
# default entirely — and place the result where the Archive step looks.
if [ ! -f "$RESOLVED" ]; then
  ( cd ios/App/CapApp-SPM && xcrun swift package resolve )
  mkdir -p "$(dirname "$RESOLVED")"
  cp ios/App/CapApp-SPM/Package.resolved "$RESOLVED"
fi

test -f "$RESOLVED" || { echo "ci_post_clone: FAILED to produce Package.resolved"; exit 1; }

echo "ci_post_clone: generated ios/App/App.xcodeproj + resolved SPM dependencies"
}
