// Fast, deterministic per-move narration for the Play-vs-Coach board
// (David 2026-05-31: "i want the tts speech back … voice narration and
// thinking time between coach moves are too slow").
//
// WHY THIS EXISTS. On /coach/play the per-move spoken commentary was
// generated by an LLM (`generateMoveCommentary`, deepseek-chat with an
// ~18k-token envelope). The audit log measured that call at 4–15s PER
// MOVE, and because the coach's reply was gated behind it, every move
// stalled. Worse, the LLM streamed multiple sentences to Polly at once,
// flooding it until it dropped to the robotic Web Speech voice. This
// builder replaces that hot-path call with an INSTANT template line so
// the coach replies immediately and exactly one short utterance reaches
// Polly per move.
//
// The MOVES are always real (chess.js produced the SAN); this module
// only turns the already-computed move + tactic + classification data
// into a short spoken line. No invented chess content (G3).

import { describeMove } from '../services/tacticNarrationService';
import type { TacticPattern, HangingPiece } from '../types/tacticTypes';

/** Density knob, mirrors `resolveLlmNarrationDensity`:
 *  - 'none'      → silent (the unified "Silent" setting)
 *  - 'fast'      → brief / key-moments: speak only when something
 *                  concrete happened (tactic / hanging / blunder / check)
 *  - everything else ('unlimited', 'standard', …) → full: also dictate
 *    routine moves so full-narration users hear every move. */
export type FastNarrationDensity = 'none' | 'fast' | (string & {});

export interface FastMoveLineInput {
  /** SAN of the move that was just played (may carry +/#). */
  san: string;
  /** True when the side that just moved is White. */
  moverIsWhite: boolean;
  /** Classification of the move just played, if computed. */
  classification?: string;
  /** Real tactic motifs detected on the resulting position. */
  tactics?: TacticPattern[];
  /** Pieces left hanging on the resulting position. */
  hangingPieces?: HangingPiece[];
  /** Narration density resolved from the user's setting. */
  density: FastNarrationDensity;
  /** Per-game set of squares whose hanging-piece warning has ALREADY
   *  been spoken. A given square is narrated only once — while the same
   *  piece stays loose across several moves the warning must not repeat
   *  (David 2026-06-02: "only narrate the hanging pawn once"). The caller
   *  owns + resets this per game; when a fresh square is announced the
   *  builder adds it. Omit it (tests, callers without a game) to disable
   *  de-dup. */
  announcedHangingSquares?: Set<string>;
}

const KEY_CLASSIFICATIONS = new Set(['blunder', 'mistake', 'inaccuracy']);

function capitalizeFirst(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

const PIECE_WORD: Record<string, string> = {
  q: 'queen', r: 'rook', b: 'bishop', n: 'knight', p: 'pawn', k: 'king',
};

/** Spell a square so TTS reads it clearly: "f5" → "f 5". */
function spellSquare(sq: string): string {
  return /^[a-h][1-8]$/.test(sq) ? `${sq[0]} ${sq[1]}` : sq;
}

/**
 * Build a short, concrete spoken line for the move that was just played.
 * Returns '' when nothing is worth speaking (routine move under a
 * non-full density, or the silent setting) — the caller treats '' as
 * "say nothing for this move", which is sanctioned (narration voice
 * rule 4: silence is acceptable).
 *
 * Priority of what to say (most concrete first):
 *   1. A real tactic motif on the board now (fork / pin / skewer …) —
 *      `TacticPattern.description` is already concrete and board-true.
 *   2. A hanging piece the move exposed — name the piece + square.
 *   3. A key-moment classification (blunder / mistake / inaccuracy)
 *      with no detected motif — an honest "that gives ground" flag.
 *   4. Full density only: dictate the move ("Knight takes on f7,
 *      check") so every-move users still hear a beat.
 */
export function buildFastMoveLine(input: FastMoveLineInput): string {
  const { san, moverIsWhite, classification, tactics, hangingPieces, density, announcedHangingSquares } = input;
  if (density === 'none') return '';

  const realTactics = (tactics ?? []).filter((t) => t.type !== 'none' && t.description.trim());
  const isKey = !!classification && KEY_CLASSIFICATIONS.has(classification);

  // 1. Concrete tactic on the board — already human-readable + board-true.
  if (realTactics.length > 0) {
    let line = capitalizeFirst(realTactics[0].description.trim());
    if (!/[.!?]$/.test(line)) line += '.';
    return line;
  }

  // 2. Hanging piece the move exposed. Surface the side-to-move's own
  //    piece left hanging — the teachable consequence of the move — but
  //    speak a given square only ONCE per game. While the same piece
  //    stays loose across several moves the old "The pawn on d4 is
  //    hanging" line repeated every ply and tuned out fast (David
  //    2026-06-02: "only narrate the hanging pawn once"). When we do
  //    speak, name the CONSEQUENCE rather than just restating the board.
  const hanging = (hangingPieces ?? [])
    .slice()
    .sort((a, b) => pieceValue(b.piece) - pieceValue(a.piece));
  const moverColor: 'w' | 'b' = moverIsWhite ? 'w' : 'b';
  const ownHanging = hanging.find((h) => h.color === moverColor);
  if (ownHanging && (isKey || density !== 'fast')) {
    if (!announcedHangingSquares?.has(ownHanging.square)) {
      announcedHangingSquares?.add(ownHanging.square);
      const word = PIECE_WORD[ownHanging.piece.toLowerCase()] ?? 'piece';
      return `That leaves your ${word} on ${spellSquare(ownHanging.square)} hanging — it can be taken.`;
    }
    // Already announced this square once — don't repeat the warning.
    // Fall through to a key-moment flag or silence.
  }

  // 3. Key-moment classification with no detected motif.
  if (isKey) {
    if (classification === 'blunder') return 'That drops material.';
    if (classification === 'mistake') return 'That gives ground.';
    return 'A small slip — there was better.';
  }

  // 4. Full density: dictate the move so every-move users hear a beat.
  //    'fast' (brief / key-moments) stays silent on routine moves.
  if (density !== 'fast') {
    return `${describeMove(san, moverIsWhite)}.`;
  }

  return '';
}

function pieceValue(piece: string): number {
  switch (piece.toLowerCase()) {
    case 'q': return 9;
    case 'r': return 5;
    case 'b': return 3;
    case 'n': return 3;
    case 'p': return 1;
    default: return 0;
  }
}
