// The held-out phrasings for chatTurnEval. Written 2026-10-05 against the kind
// table's glosses, NOT against any detector regex — that is what makes them
// held out. Where an ask is honestly two kinds, both are accepted; where it is
// one, only one is. Add cases; never edit one to make a reader pass.
import type { ChatTurnEvalCase } from './chatTurnEval';

export const CHAT_TURN_EVAL_CASES: readonly ChatTurnEvalCase[] = [
  // ── the board, now ──
  { text: 'what would you play here if you were me', expect: ['best-move', 'what-should-i-play'], probe: 'indirect' },
  { text: 'whats the strongest continuation', expect: ['best-move', 'what-should-i-play'], probe: 'plain' },
  { text: 'bset move pls', expect: ['best-move', 'what-should-i-play'], probe: 'typo' },
  { text: 'cuál es la mejor jugada aquí', expect: ['best-move', 'what-should-i-play'], probe: 'language' },
  { text: 'why is that move the top choice', expect: ['why-best-move'], probe: 'plain' },
  { text: 'what makes the engine like that one so much', expect: ['why-best-move'], probe: 'indirect' },
  { text: 'give me a couple of other moves worth looking at', expect: ['alternatives'], probe: 'indirect' },
  { text: 'any other decent options besides that', expect: ['alternatives'], probe: 'plain' },
  { text: 'is Nf3 any good here', expect: ['candidate-move'], probe: 'referent' },
  { text: 'what happens if I go Bxh7+', expect: ['candidate-move'], probe: 'referent' },
  { text: 'would castling queenside be ok', expect: ['candidate-move'], probe: 'indirect' },
  { text: 'Qd2 or Qe2, which is better', expect: ['compare-moves'], probe: 'referent' },
  { text: 'should i play e5 or d5 here', expect: ['compare-moves'], probe: 'referent' },
  { text: 'what am I supposed to be doing in this position long term', expect: ['plan'], probe: 'indirect' },
  { text: 'whats the plan', expect: ['plan'], probe: 'plain' },
  { text: 'quel est le plan ici', expect: ['plan'], probe: 'language' },
  { text: 'just a nudge, dont tell me the move', expect: ['hint'], probe: 'indirect' },
  { text: 'hint?', expect: ['hint'], probe: 'plain' },
  { text: 'how should I even think about a position like this', expect: ['method'], probe: 'indirect' },
  { text: 'what should I look for first before moving', expect: ['method'], probe: 'plain' },
  { text: 'any tricks for me here', expect: ['tactics'], probe: 'indirect' },
  { text: 'is something hanging', expect: ['tactics', 'is-piece-loose'], probe: 'plain' },
  { text: 'are they threatening anything', expect: ['tactics', 'what-did-their-move-change'], probe: 'plain' },
  { text: 'gibt es hier eine taktik', expect: ['tactics'], probe: 'language' },
  { text: 'who is better right now', expect: ['position-assessment'], probe: 'plain' },
  { text: 'am i winning or what', expect: ['position-assessment'], probe: 'indirect' },
  { text: 'whos wining', expect: ['position-assessment'], probe: 'typo' },
  { text: 'quem está ganhando', expect: ['position-assessment'], probe: 'language' },
  { text: 'is it my move', expect: ['whose-turn'], probe: 'plain' },
  { text: 'which side am I on', expect: ['live-colour'], probe: 'indirect' },
  { text: 'can I checkmate them', expect: ['mate'], probe: 'plain' },
  { text: 'is there a forced mate', expect: ['mate'], probe: 'plain' },
  { text: 'is this dead drawn', expect: ['draw'], probe: 'plain' },
  { text: 'how do I convert this rook ending', expect: ['endgame'], probe: 'plain' },
  { text: 'what is the technique to win king and pawn vs king', expect: ['endgame', 'theory'], probe: 'plain' },
  { text: 'any weak squares in their camp', expect: ['positional'], probe: 'plain' },
  { text: 'where are the holes', expect: ['positional'], probe: 'indirect' },
  { text: 'what do grandmasters usually play from here', expect: ['master-play'], probe: 'indirect' },
  { text: 'what do strong players play in this spot', expect: ['master-play'], probe: 'plain' },
  { text: 'how does Magnus handle this line', expect: ['player-games'], probe: 'referent' },
  { text: 'couldnt they have just moved the queen away', expect: ['piece-options'], probe: 'indirect' },
  { text: 'where can my knight go', expect: ['piece-options'], probe: 'plain' },

  // ── moves already played ──
  { text: 'was that a good move', expect: ['move-rating', 'retrospective-move'], probe: 'plain' },
  { text: 'did i just blunder', expect: ['move-rating', 'retrospective-move'], probe: 'indirect' },
  { text: 'why was Nxe5 bad', expect: ['retrospective-move'], probe: 'referent' },
  { text: 'why did they play that', expect: ['opponent-move', 'what-did-their-move-change'], probe: 'plain' },
  { text: 'what is the idea behind their last move', expect: ['opponent-move', 'what-did-their-move-change'], probe: 'indirect' },
  { text: 'what did their move change', expect: ['what-did-their-move-change', 'opponent-move'], probe: 'plain' },
  { text: 'what just moved', expect: ['last-move'], probe: 'plain' },
  { text: 'why is your move better than what I played', expect: ['compare-my-move'], probe: 'referent' },
  { text: 'how was mine worse than yours', expect: ['compare-my-move'], probe: 'indirect' },

  // ── the student's own record ──
  { text: 'what am I actually good at', expect: ['strengths'], probe: 'plain' },
  { text: 'what is my rating now', expect: ['stats'], probe: 'plain' },
  { text: 'how accurate am I in the caro kann', expect: ['opening-accuracy'], probe: 'referent' },
  { text: 'any traps I can set in the London', expect: ['opening-traps'], probe: 'referent' },
  { text: 'what should I review today', expect: ['review-due'], probe: 'indirect' },
  { text: 'what mistakes do I keep making', expect: ['mistakes', 'misconceptions'], probe: 'plain' },
  { text: 'do i blunder more when im winning', expect: ['errors-by-situation'], probe: 'indirect' },
  { text: 'how strong are my tactics', expect: ['tactics-profile'], probe: 'plain' },
  { text: 'am I worse in the opening middlegame or endgame', expect: ['phase-profile'], probe: 'indirect' },
  { text: 'what should i play against the kings indian', expect: ['counter-repertoire'], probe: 'referent' },
  { text: 'what lines am i missing in my repertoire', expect: ['repertoire-gap'], probe: 'indirect' },
  { text: 'whats my average accuracy', expect: ['accuracy'], probe: 'plain' },
  { text: 'am i playing too fast', expect: ['time-trouble'], probe: 'plain' },
  { text: 'did i win my last game', expect: ['last-game'], probe: 'plain' },
  { text: 'what went wrong in my last game', expect: ['last-game-mistake', 'last-game'], probe: 'indirect' },
  { text: 'do I let winning positions slip', expect: ['converting'], probe: 'indirect' },
  { text: 'am i better with white or black', expect: ['color'], probe: 'plain' },
  { text: 'whats my best win ever', expect: ['records'], probe: 'plain' },
  { text: 'how do i score against the sicilian', expect: ['record-vs'], probe: 'referent' },
  { text: 'what is my puzzle rating', expect: ['puzzle-stats'], probe: 'plain' },
  { text: 'do my puzzle skills show up in my games', expect: ['transfer-gap'], probe: 'indirect' },
  { text: 'am i improving lately', expect: ['trend', 'progress'], probe: 'plain' },
  { text: 'which opening do i score best with', expect: ['opening-profile'], probe: 'plain' },
  { text: 'which endgames do i mess up', expect: ['endgame-weakness'], probe: 'indirect' },
  { text: 'set me up some rook endgame training', expect: ['training-request', 'command'], probe: 'plain' },
  { text: 'which weaknesses have i fixed', expect: ['weakness-lifecycle'], probe: 'plain' },

  // ── knowledge ──
  { text: 'what is a skewer', expect: ['concept'], probe: 'plain' },
  { text: 'whats zugzwang mean', expect: ['concept'], probe: 'typo' },
  { text: 'qué es una clavada', expect: ['concept'], probe: 'language' },
  { text: 'how do you play against an isolated queen pawn', expect: ['theory'], probe: 'plain' },
  { text: 'how would you teach me the french defense', expect: ['teaching-method'], probe: 'referent' },
  { text: 'is my voice turned on', expect: ['settings'], probe: 'indirect' },
  { text: 'how do I import my games', expect: ['app-help'], probe: 'plain' },
  { text: 'what opening is this', expect: ['name-opening'], probe: 'plain' },
  { text: 'what is the ponziani', expect: ['opening-identity'], probe: 'referent' },
  { text: 'is there such a thing as the hippo opening', expect: ['opening-existence', 'opening-identity'], probe: 'referent' },

  // ── lesson + dialogue ──
  { text: 'c6 and e5', expect: ['answer'], probe: 'referent' },
  { text: 'the knight on c6', expect: ['answer', 'what-about-piece'], probe: 'referent' },
  { text: 'i have no idea', expect: ['i-dont-know'], probe: 'plain' },
  { text: 'no sé', expect: ['i-dont-know'], probe: 'language' },
  { text: 'why is that knight a target', expect: ['why-is-it-a-target'], probe: 'referent' },
  { text: 'how many of my pieces attack it', expect: ['count-attackers'], probe: 'follow-up' },
  { text: 'and how many defend it', expect: ['count-defenders'], probe: 'follow-up' },
  { text: 'what about my bishop', expect: ['what-about-piece'], probe: 'referent' },
  { text: 'is my rook loose', expect: ['is-piece-loose', 'tactics'], probe: 'referent' },
  { text: 'teach me how to think', expect: ['start-thinking-lesson'], probe: 'plain' },

  // ── the books ──
  { text: 'what does capablanca say about rook endings', expect: ['book-teaching'], probe: 'referent' },
  { text: 'teach me the blockade from my system', expect: ['book-teaching'], probe: 'referent' },
  { text: 'what do the old books say about the centre', expect: ['book-teaching'], probe: 'indirect' },
  { text: 'que dice lasker sobre la defensa', expect: ['book-teaching'], probe: 'language' },

  // ── commands + conversation ──
  { text: 'take that move back', expect: ['command'], probe: 'plain' },
  { text: 'turn the voice off', expect: ['command'], probe: 'plain' },
  { text: 'shh', expect: ['stop'], probe: 'indirect' },
  { text: 'yes please', expect: ['conversational-reply'], probe: 'plain' },
  { text: 'thanks coach!', expect: ['chat'], probe: 'plain' },
  { text: 'hello', expect: ['chat'], probe: 'plain' },
];
